//! Autogenerated weights for `pallet_qbc_utxo`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARKING CLI.
//! Manual edits will be lost on regeneration.
//! Analytical estimates used until real benchmarks are run.

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use core::marker::PhantomData;

/// Weight functions needed for `pallet_qbc_utxo`.
pub trait WeightInfo {
    fn submit_transaction(i: u32, o: u32) -> Weight;
}

/// Weights for `pallet_qbc_utxo` using the Substrate node and recommended hardware.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
    /// Analytical weight for `submit_transaction`.
    ///
    /// Per-input cost: 1 storage read (25us) + 1 Dilithium5 verify (500us) + 1 storage delete (25us)
    /// Per-output cost: 1 storage write (25us) + balance update (25us)
    /// Base cost: fee accumulation (25us) + txid computation (10us) + event deposits
    ///
    /// Storage: UtxoSet (r: i, w: i+o), Balances (r: 0, w: i+o), SpentUtxos (r: i, w: i),
    ///          AccumulatedFees (r: 1, w: 1), CurrentHeight (r: 1, w: 0),
    ///          UtxoCount (r: 1, w: 1), TxCount (r: 1, w: 1)
    fn submit_transaction(i: u32, o: u32) -> Weight {
        // Base cost: ~35us for fee accumulation, txid, event deposits
        // Per-input: ~550us (read + Dilithium verify + delete + balance update)
        // Per-output: ~50us (write + balance update)
        Weight::from_parts(
            35_000u64
                .saturating_add(550_000u64.saturating_mul(i as u64))
                .saturating_add(50_000u64.saturating_mul(o as u64)),
            0,
        )
        .saturating_add(T::DbWeight::get().reads(4u64.saturating_add(2u64.saturating_mul(i as u64))))
        .saturating_add(T::DbWeight::get().writes(3u64.saturating_add(2u64.saturating_mul(i as u64)).saturating_add(2u64.saturating_mul(o as u64))))
    }
}

/// Default implementation for tests.
impl WeightInfo for () {
    fn submit_transaction(i: u32, o: u32) -> Weight {
        Weight::from_parts(
            35_000u64
                .saturating_add(550_000u64.saturating_mul(i as u64))
                .saturating_add(50_000u64.saturating_mul(o as u64)),
            0,
        )
        .saturating_add(RocksDbWeight::get().reads(4u64.saturating_add(2u64.saturating_mul(i as u64))))
        .saturating_add(RocksDbWeight::get().writes(3u64.saturating_add(2u64.saturating_mul(i as u64)).saturating_add(2u64.saturating_mul(o as u64))))
    }
}
