# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import aikgs_pb2 as aikgs__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in aikgs_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AikgsServiceStub(object):
    """═══════════════════ Service Definition ═══════════════════

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ProcessContribution = channel.unary_unary(
                '/aikgs.AikgsService/ProcessContribution',
                request_serializer=aikgs__pb2.ContributeRequest.SerializeToString,
                response_deserializer=aikgs__pb2.ContributionRecord.FromString,
                _registered_method=True)
        self.GetContribution = channel.unary_unary(
                '/aikgs.AikgsService/GetContribution',
                request_serializer=aikgs__pb2.GetContributionRequest.SerializeToString,
                response_deserializer=aikgs__pb2.ContributionRecord.FromString,
                _registered_method=True)
        self.GetContributorHistory = channel.unary_unary(
                '/aikgs.AikgsService/GetContributorHistory',
                request_serializer=aikgs__pb2.ContributorHistoryRequest.SerializeToString,
                response_deserializer=aikgs__pb2.ContributionListResponse.FromString,
                _registered_method=True)
        self.GetRecentContributions = channel.unary_unary(
                '/aikgs.AikgsService/GetRecentContributions',
                request_serializer=aikgs__pb2.RecentContributionsRequest.SerializeToString,
                response_deserializer=aikgs__pb2.ContributionListResponse.FromString,
                _registered_method=True)
        self.GetContributionLeaderboard = channel.unary_unary(
                '/aikgs.AikgsService/GetContributionLeaderboard',
                request_serializer=aikgs__pb2.LeaderboardRequest.SerializeToString,
                response_deserializer=aikgs__pb2.LeaderboardResponse.FromString,
                _registered_method=True)
        self.GetContributionStats = channel.unary_unary(
                '/aikgs.AikgsService/GetContributionStats',
                request_serializer=aikgs__pb2.Empty.SerializeToString,
                response_deserializer=aikgs__pb2.ContributionStats.FromString,
                _registered_method=True)
        self.GetRewardStats = channel.unary_unary(
                '/aikgs.AikgsService/GetRewardStats',
                request_serializer=aikgs__pb2.Empty.SerializeToString,
                response_deserializer=aikgs__pb2.RewardStats.FromString,
                _registered_method=True)
        self.GetContributorStreak = channel.unary_unary(
                '/aikgs.AikgsService/GetContributorStreak',
                request_serializer=aikgs__pb2.StreakRequest.SerializeToString,
                response_deserializer=aikgs__pb2.StreakInfo.FromString,
                _registered_method=True)
        self.FundPool = channel.unary_unary(
                '/aikgs.AikgsService/FundPool',
                request_serializer=aikgs__pb2.FundPoolRequest.SerializeToString,
                response_deserializer=aikgs__pb2.PoolBalance.FromString,
                _registered_method=True)
        self.RegisterAffiliate = channel.unary_unary(
                '/aikgs.AikgsService/RegisterAffiliate',
                request_serializer=aikgs__pb2.RegisterAffiliateRequest.SerializeToString,
                response_deserializer=aikgs__pb2.AffiliateInfo.FromString,
                _registered_method=True)
        self.GetAffiliateLink = channel.unary_unary(
                '/aikgs.AikgsService/GetAffiliateLink',
                request_serializer=aikgs__pb2.AffiliateLinkRequest.SerializeToString,
                response_deserializer=aikgs__pb2.AffiliateLinkResponse.FromString,
                _registered_method=True)
        self.GetAffiliate = channel.unary_unary(
                '/aikgs.AikgsService/GetAffiliate',
                request_serializer=aikgs__pb2.GetAffiliateRequest.SerializeToString,
                response_deserializer=aikgs__pb2.AffiliateInfo.FromString,
                _registered_method=True)
        self.GetAffiliateStats = channel.unary_unary(
                '/aikgs.AikgsService/GetAffiliateStats',
                request_serializer=aikgs__pb2.Empty.SerializeToString,
                response_deserializer=aikgs__pb2.AffiliateStats.FromString,
                _registered_method=True)
        self.CreateBounty = channel.unary_unary(
                '/aikgs.AikgsService/CreateBounty',
                request_serializer=aikgs__pb2.CreateBountyRequest.SerializeToString,
                response_deserializer=aikgs__pb2.BountyInfo.FromString,
                _registered_method=True)
        self.ListBounties = channel.unary_unary(
                '/aikgs.AikgsService/ListBounties',
                request_serializer=aikgs__pb2.ListBountiesRequest.SerializeToString,
                response_deserializer=aikgs__pb2.ListBountiesResponse.FromString,
                _registered_method=True)
        self.ClaimBounty = channel.unary_unary(
                '/aikgs.AikgsService/ClaimBounty',
                request_serializer=aikgs__pb2.ClaimBountyRequest.SerializeToString,
                response_deserializer=aikgs__pb2.BountyInfo.FromString,
                _registered_method=True)
        self.FulfillBounty = channel.unary_unary(
                '/aikgs.AikgsService/FulfillBounty',
                request_serializer=aikgs__pb2.FulfillBountyRequest.SerializeToString,
                response_deserializer=aikgs__pb2.FulfillBountyResponse.FromString,
                _registered_method=True)
        self.GetBountyStats = channel.unary_unary(
                '/aikgs.AikgsService/GetBountyStats',
                request_serializer=aikgs__pb2.Empty.SerializeToString,
                response_deserializer=aikgs__pb2.BountyStats.FromString,
                _registered_method=True)
        self.GetProfile = channel.unary_unary(
                '/aikgs.AikgsService/GetProfile',
                request_serializer=aikgs__pb2.ProfileRequest.SerializeToString,
                response_deserializer=aikgs__pb2.ContributorProfile.FromString,
                _registered_method=True)
        self.HasFeature = channel.unary_unary(
                '/aikgs.AikgsService/HasFeature',
                request_serializer=aikgs__pb2.HasFeatureRequest.SerializeToString,
                response_deserializer=aikgs__pb2.HasFeatureResponse.FromString,
                _registered_method=True)
        self.GetUnlocksLeaderboard = channel.unary_unary(
                '/aikgs.AikgsService/GetUnlocksLeaderboard',
                request_serializer=aikgs__pb2.UnlocksLeaderboardRequest.SerializeToString,
                response_deserializer=aikgs__pb2.UnlocksLeaderboardResponse.FromString,
                _registered_method=True)
        self.GetUnlocksStats = channel.unary_unary(
                '/aikgs.AikgsService/GetUnlocksStats',
                request_serializer=aikgs__pb2.Empty.SerializeToString,
                response_deserializer=aikgs__pb2.UnlocksStats.FromString,
                _registered_method=True)
        self.SubmitForCuration = channel.unary_unary(
                '/aikgs.AikgsService/SubmitForCuration',
                request_serializer=aikgs__pb2.SubmitForCurationRequest.SerializeToString,
                response_deserializer=aikgs__pb2.CurationRound.FromString,
                _registered_method=True)
        self.SubmitReview = channel.unary_unary(
                '/aikgs.AikgsService/SubmitReview',
                request_serializer=aikgs__pb2.SubmitReviewRequest.SerializeToString,
                response_deserializer=aikgs__pb2.CurationRound.FromString,
                _registered_method=True)
        self.GetPendingReviews = channel.unary_unary(
                '/aikgs.AikgsService/GetPendingReviews',
                request_serializer=aikgs__pb2.PendingReviewsRequest.SerializeToString,
                response_deserializer=aikgs__pb2.PendingReviewsResponse.FromString,
                _registered_method=True)
        self.GetCurationRound = channel.unary_unary(
                '/aikgs.AikgsService/GetCurationRound',
                request_serializer=aikgs__pb2.GetCurationRoundRequest.SerializeToString,
                response_deserializer=aikgs__pb2.CurationRound.FromString,
                _registered_method=True)
        self.GetCuratorStats = channel.unary_unary(
                '/aikgs.AikgsService/GetCuratorStats',
                request_serializer=aikgs__pb2.CuratorStatsRequest.SerializeToString,
                response_deserializer=aikgs__pb2.CuratorStats.FromString,
                _registered_method=True)
        self.GetCurationStats = channel.unary_unary(
                '/aikgs.AikgsService/GetCurationStats',
                request_serializer=aikgs__pb2.Empty.SerializeToString,
                response_deserializer=aikgs__pb2.CurationStats.FromString,
                _registered_method=True)
        self.StoreApiKey = channel.unary_unary(
                '/aikgs.AikgsService/StoreApiKey',
                request_serializer=aikgs__pb2.StoreKeyRequest.SerializeToString,
                response_deserializer=aikgs__pb2.StoreKeyResponse.FromString,
                _registered_method=True)
        self.GetApiKey = channel.unary_unary(
                '/aikgs.AikgsService/GetApiKey',
                request_serializer=aikgs__pb2.GetKeyRequest.SerializeToString,
                response_deserializer=aikgs__pb2.DecryptedKeyResponse.FromString,
                _registered_method=True)
        self.ListApiKeys = channel.unary_unary(
                '/aikgs.AikgsService/ListApiKeys',
                request_serializer=aikgs__pb2.ListKeysRequest.SerializeToString,
                response_deserializer=aikgs__pb2.ListKeysResponse.FromString,
                _registered_method=True)
        self.RevokeApiKey = channel.unary_unary(
                '/aikgs.AikgsService/RevokeApiKey',
                request_serializer=aikgs__pb2.RevokeKeyRequest.SerializeToString,
                response_deserializer=aikgs__pb2.StatusResponse.FromString,
                _registered_method=True)
        self.GetSharedKeyPool = channel.unary_unary(
                '/aikgs.AikgsService/GetSharedKeyPool',
                request_serializer=aikgs__pb2.SharedPoolRequest.SerializeToString,
                response_deserializer=aikgs__pb2.SharedPoolResponse.FromString,
                _registered_method=True)
        self.Disburse = channel.unary_unary(
                '/aikgs.AikgsService/Disburse',
                request_serializer=aikgs__pb2.DisburseRequest.SerializeToString,
                response_deserializer=aikgs__pb2.DisburseResponse.FromString,
                _registered_method=True)
        self.GetPendingDisbursements = channel.unary_unary(
                '/aikgs.AikgsService/GetPendingDisbursements',
                request_serializer=aikgs__pb2.Empty.SerializeToString,
                response_deserializer=aikgs__pb2.PendingDisbursementsResponse.FromString,
                _registered_method=True)
        self.GetFullStats = channel.unary_unary(
                '/aikgs.AikgsService/GetFullStats',
                request_serializer=aikgs__pb2.Empty.SerializeToString,
                response_deserializer=aikgs__pb2.AikgsFullStats.FromString,
                _registered_method=True)


class AikgsServiceServicer(object):
    """═══════════════════ Service Definition ═══════════════════

    """

    def ProcessContribution(self, request, context):
        """Contributions
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetContribution(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetContributorHistory(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetRecentContributions(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetContributionLeaderboard(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetContributionStats(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetRewardStats(self, request, context):
        """Rewards
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetContributorStreak(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FundPool(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RegisterAffiliate(self, request, context):
        """Affiliates
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAffiliateLink(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAffiliate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAffiliateStats(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateBounty(self, request, context):
        """Bounties
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListBounties(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ClaimBounty(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FulfillBounty(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetBountyStats(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetProfile(self, request, context):
        """Profiles / Progressive Unlocks
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HasFeature(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetUnlocksLeaderboard(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetUnlocksStats(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SubmitForCuration(self, request, context):
        """Curation
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SubmitReview(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPendingReviews(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCurationRound(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCuratorStats(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCurationStats(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StoreApiKey(self, request, context):
        """API Key Vault
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetApiKey(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListApiKeys(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RevokeApiKey(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSharedKeyPool(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Disburse(self, request, context):
        """Treasury
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPendingDisbursements(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetFullStats(self, request, context):
        """Aggregate
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AikgsServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ProcessContribution': grpc.unary_unary_rpc_method_handler(
                    servicer.ProcessContribution,
                    request_deserializer=aikgs__pb2.ContributeRequest.FromString,
                    response_serializer=aikgs__pb2.ContributionRecord.SerializeToString,
            ),
            'GetContribution': grpc.unary_unary_rpc_method_handler(
                    servicer.GetContribution,
                    request_deserializer=aikgs__pb2.GetContributionRequest.FromString,
                    response_serializer=aikgs__pb2.ContributionRecord.SerializeToString,
            ),
            'GetContributorHistory': grpc.unary_unary_rpc_method_handler(
                    servicer.GetContributorHistory,
                    request_deserializer=aikgs__pb2.ContributorHistoryRequest.FromString,
                    response_serializer=aikgs__pb2.ContributionListResponse.SerializeToString,
            ),
            'GetRecentContributions': grpc.unary_unary_rpc_method_handler(
                    servicer.GetRecentContributions,
                    request_deserializer=aikgs__pb2.RecentContributionsRequest.FromString,
                    response_serializer=aikgs__pb2.ContributionListResponse.SerializeToString,
            ),
            'GetContributionLeaderboard': grpc.unary_unary_rpc_method_handler(
                    servicer.GetContributionLeaderboard,
                    request_deserializer=aikgs__pb2.LeaderboardRequest.FromString,
                    response_serializer=aikgs__pb2.LeaderboardResponse.SerializeToString,
            ),
            'GetContributionStats': grpc.unary_unary_rpc_method_handler(
                    servicer.GetContributionStats,
                    request_deserializer=aikgs__pb2.Empty.FromString,
                    response_serializer=aikgs__pb2.ContributionStats.SerializeToString,
            ),
            'GetRewardStats': grpc.unary_unary_rpc_method_handler(
                    servicer.GetRewardStats,
                    request_deserializer=aikgs__pb2.Empty.FromString,
                    response_serializer=aikgs__pb2.RewardStats.SerializeToString,
            ),
            'GetContributorStreak': grpc.unary_unary_rpc_method_handler(
                    servicer.GetContributorStreak,
                    request_deserializer=aikgs__pb2.StreakRequest.FromString,
                    response_serializer=aikgs__pb2.StreakInfo.SerializeToString,
            ),
            'FundPool': grpc.unary_unary_rpc_method_handler(
                    servicer.FundPool,
                    request_deserializer=aikgs__pb2.FundPoolRequest.FromString,
                    response_serializer=aikgs__pb2.PoolBalance.SerializeToString,
            ),
            'RegisterAffiliate': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterAffiliate,
                    request_deserializer=aikgs__pb2.RegisterAffiliateRequest.FromString,
                    response_serializer=aikgs__pb2.AffiliateInfo.SerializeToString,
            ),
            'GetAffiliateLink': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAffiliateLink,
                    request_deserializer=aikgs__pb2.AffiliateLinkRequest.FromString,
                    response_serializer=aikgs__pb2.AffiliateLinkResponse.SerializeToString,
            ),
            'GetAffiliate': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAffiliate,
                    request_deserializer=aikgs__pb2.GetAffiliateRequest.FromString,
                    response_serializer=aikgs__pb2.AffiliateInfo.SerializeToString,
            ),
            'GetAffiliateStats': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAffiliateStats,
                    request_deserializer=aikgs__pb2.Empty.FromString,
                    response_serializer=aikgs__pb2.AffiliateStats.SerializeToString,
            ),
            'CreateBounty': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateBounty,
                    request_deserializer=aikgs__pb2.CreateBountyRequest.FromString,
                    response_serializer=aikgs__pb2.BountyInfo.SerializeToString,
            ),
            'ListBounties': grpc.unary_unary_rpc_method_handler(
                    servicer.ListBounties,
                    request_deserializer=aikgs__pb2.ListBountiesRequest.FromString,
                    response_serializer=aikgs__pb2.ListBountiesResponse.SerializeToString,
            ),
            'ClaimBounty': grpc.unary_unary_rpc_method_handler(
                    servicer.ClaimBounty,
                    request_deserializer=aikgs__pb2.ClaimBountyRequest.FromString,
                    response_serializer=aikgs__pb2.BountyInfo.SerializeToString,
            ),
            'FulfillBounty': grpc.unary_unary_rpc_method_handler(
                    servicer.FulfillBounty,
                    request_deserializer=aikgs__pb2.FulfillBountyRequest.FromString,
                    response_serializer=aikgs__pb2.FulfillBountyResponse.SerializeToString,
            ),
            'GetBountyStats': grpc.unary_unary_rpc_method_handler(
                    servicer.GetBountyStats,
                    request_deserializer=aikgs__pb2.Empty.FromString,
                    response_serializer=aikgs__pb2.BountyStats.SerializeToString,
            ),
            'GetProfile': grpc.unary_unary_rpc_method_handler(
                    servicer.GetProfile,
                    request_deserializer=aikgs__pb2.ProfileRequest.FromString,
                    response_serializer=aikgs__pb2.ContributorProfile.SerializeToString,
            ),
            'HasFeature': grpc.unary_unary_rpc_method_handler(
                    servicer.HasFeature,
                    request_deserializer=aikgs__pb2.HasFeatureRequest.FromString,
                    response_serializer=aikgs__pb2.HasFeatureResponse.SerializeToString,
            ),
            'GetUnlocksLeaderboard': grpc.unary_unary_rpc_method_handler(
                    servicer.GetUnlocksLeaderboard,
                    request_deserializer=aikgs__pb2.UnlocksLeaderboardRequest.FromString,
                    response_serializer=aikgs__pb2.UnlocksLeaderboardResponse.SerializeToString,
            ),
            'GetUnlocksStats': grpc.unary_unary_rpc_method_handler(
                    servicer.GetUnlocksStats,
                    request_deserializer=aikgs__pb2.Empty.FromString,
                    response_serializer=aikgs__pb2.UnlocksStats.SerializeToString,
            ),
            'SubmitForCuration': grpc.unary_unary_rpc_method_handler(
                    servicer.SubmitForCuration,
                    request_deserializer=aikgs__pb2.SubmitForCurationRequest.FromString,
                    response_serializer=aikgs__pb2.CurationRound.SerializeToString,
            ),
            'SubmitReview': grpc.unary_unary_rpc_method_handler(
                    servicer.SubmitReview,
                    request_deserializer=aikgs__pb2.SubmitReviewRequest.FromString,
                    response_serializer=aikgs__pb2.CurationRound.SerializeToString,
            ),
            'GetPendingReviews': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPendingReviews,
                    request_deserializer=aikgs__pb2.PendingReviewsRequest.FromString,
                    response_serializer=aikgs__pb2.PendingReviewsResponse.SerializeToString,
            ),
            'GetCurationRound': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCurationRound,
                    request_deserializer=aikgs__pb2.GetCurationRoundRequest.FromString,
                    response_serializer=aikgs__pb2.CurationRound.SerializeToString,
            ),
            'GetCuratorStats': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCuratorStats,
                    request_deserializer=aikgs__pb2.CuratorStatsRequest.FromString,
                    response_serializer=aikgs__pb2.CuratorStats.SerializeToString,
            ),
            'GetCurationStats': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCurationStats,
                    request_deserializer=aikgs__pb2.Empty.FromString,
                    response_serializer=aikgs__pb2.CurationStats.SerializeToString,
            ),
            'StoreApiKey': grpc.unary_unary_rpc_method_handler(
                    servicer.StoreApiKey,
                    request_deserializer=aikgs__pb2.StoreKeyRequest.FromString,
                    response_serializer=aikgs__pb2.StoreKeyResponse.SerializeToString,
            ),
            'GetApiKey': grpc.unary_unary_rpc_method_handler(
                    servicer.GetApiKey,
                    request_deserializer=aikgs__pb2.GetKeyRequest.FromString,
                    response_serializer=aikgs__pb2.DecryptedKeyResponse.SerializeToString,
            ),
            'ListApiKeys': grpc.unary_unary_rpc_method_handler(
                    servicer.ListApiKeys,
                    request_deserializer=aikgs__pb2.ListKeysRequest.FromString,
                    response_serializer=aikgs__pb2.ListKeysResponse.SerializeToString,
            ),
            'RevokeApiKey': grpc.unary_unary_rpc_method_handler(
                    servicer.RevokeApiKey,
                    request_deserializer=aikgs__pb2.RevokeKeyRequest.FromString,
                    response_serializer=aikgs__pb2.StatusResponse.SerializeToString,
            ),
            'GetSharedKeyPool': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSharedKeyPool,
                    request_deserializer=aikgs__pb2.SharedPoolRequest.FromString,
                    response_serializer=aikgs__pb2.SharedPoolResponse.SerializeToString,
            ),
            'Disburse': grpc.unary_unary_rpc_method_handler(
                    servicer.Disburse,
                    request_deserializer=aikgs__pb2.DisburseRequest.FromString,
                    response_serializer=aikgs__pb2.DisburseResponse.SerializeToString,
            ),
            'GetPendingDisbursements': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPendingDisbursements,
                    request_deserializer=aikgs__pb2.Empty.FromString,
                    response_serializer=aikgs__pb2.PendingDisbursementsResponse.SerializeToString,
            ),
            'GetFullStats': grpc.unary_unary_rpc_method_handler(
                    servicer.GetFullStats,
                    request_deserializer=aikgs__pb2.Empty.FromString,
                    response_serializer=aikgs__pb2.AikgsFullStats.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'aikgs.AikgsService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('aikgs.AikgsService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AikgsService(object):
    """═══════════════════ Service Definition ═══════════════════

    """

    @staticmethod
    def ProcessContribution(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aikgs.AikgsService/ProcessContribution',
            aikgs__pb2.ContributeRequest.SerializeToString,
            aikgs__pb2.ContributionRecord.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetContribution(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aikgs.AikgsService/GetContribution',
            aikgs__pb2.GetContributionRequest.SerializeToString,
            aikgs__pb2.ContributionRecord.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetContributorHistory(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aikgs.AikgsService/GetContributorHistory',
            aikgs__pb2.ContributorHistoryRequest.SerializeToString,
            aikgs__pb2.ContributionListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetRecentContributions(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aikgs.AikgsService/GetRecentContributions',
            aikgs__pb2.RecentContributionsRequest.SerializeToString,
            aikgs__pb2.ContributionListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetContributionLeaderboard(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aikgs.AikgsService/GetContributionLeaderboard',
            aikgs__pb2.LeaderboardRequest.SerializeToString,
            aikgs__pb2.LeaderboardResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetContributionStats(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aikgs.AikgsService/GetContributionStats',
            aikgs__pb2.Empty.SerializeToString,
            aikgs__pb2.ContributionStats.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetRewardStats(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aikgs.AikgsService/GetRewardStats',
            aikgs__pb2.Empty.SerializeToString,
            aikgs__pb2.RewardStats.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetContributorStreak(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aikgs.AikgsService/GetContributorStreak',
            aikgs__pb2.StreakRequest.SerializeToString,
            aikgs__pb2.StreakInfo.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def FundPool(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aikgs.AikgsService/FundPool',
            aikgs__pb2.FundPoolRequest.SerializeToString,
            aikgs__pb2.PoolBalance.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RegisterAffiliate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aikgs.AikgsService/RegisterAffiliate',
            aikgs__pb2.RegisterAffiliateRequest.SerializeToString,
            aikgs__pb2.AffiliateInfo.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAffiliateLink(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aikgs.AikgsService/GetAffiliateLink',
            aikgs__pb2.AffiliateLinkRequest.SerializeToString,
            aikgs__pb2.AffiliateLinkResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAffiliate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aikgs.AikgsService/GetAffiliate',
            aikgs__pb2.GetAffiliateRequest.SerializeToString,
            aikgs__pb2.AffiliateInfo.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAffiliateStats(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aikgs.AikgsService/GetAffiliateStats',
            aikgs__pb2.Empty.SerializeToString,
            aikgs__pb2.AffiliateStats.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateBounty(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aikgs.AikgsService/CreateBounty',
            aikgs__pb2.CreateBountyRequest.SerializeToString,
            aikgs__pb2.BountyInfo.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListBounties(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aikgs.AikgsService/ListBounties',
            aikgs__pb2.ListBountiesRequest.SerializeToString,
            aikgs__pb2.ListBountiesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ClaimBounty(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aikgs.AikgsService/ClaimBounty',
            aikgs__pb2.ClaimBountyRequest.SerializeToString,
            aikgs__pb2.BountyInfo.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def FulfillBounty(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aikgs.AikgsService/FulfillBounty',
            aikgs__pb2.FulfillBountyRequest.SerializeToString,
            aikgs__pb2.FulfillBountyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetBountyStats(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aikgs.AikgsService/GetBountyStats',
            aikgs__pb2.Empty.SerializeToString,
            aikgs__pb2.BountyStats.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetProfile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aikgs.AikgsService/GetProfile',
            aikgs__pb2.ProfileRequest.SerializeToString,
            aikgs__pb2.ContributorProfile.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def HasFeature(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aikgs.AikgsService/HasFeature',
            aikgs__pb2.HasFeatureRequest.SerializeToString,
            aikgs__pb2.HasFeatureResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetUnlocksLeaderboard(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aikgs.AikgsService/GetUnlocksLeaderboard',
            aikgs__pb2.UnlocksLeaderboardRequest.SerializeToString,
            aikgs__pb2.UnlocksLeaderboardResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetUnlocksStats(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aikgs.AikgsService/GetUnlocksStats',
            aikgs__pb2.Empty.SerializeToString,
            aikgs__pb2.UnlocksStats.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SubmitForCuration(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aikgs.AikgsService/SubmitForCuration',
            aikgs__pb2.SubmitForCurationRequest.SerializeToString,
            aikgs__pb2.CurationRound.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SubmitReview(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aikgs.AikgsService/SubmitReview',
            aikgs__pb2.SubmitReviewRequest.SerializeToString,
            aikgs__pb2.CurationRound.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetPendingReviews(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aikgs.AikgsService/GetPendingReviews',
            aikgs__pb2.PendingReviewsRequest.SerializeToString,
            aikgs__pb2.PendingReviewsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetCurationRound(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aikgs.AikgsService/GetCurationRound',
            aikgs__pb2.GetCurationRoundRequest.SerializeToString,
            aikgs__pb2.CurationRound.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetCuratorStats(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aikgs.AikgsService/GetCuratorStats',
            aikgs__pb2.CuratorStatsRequest.SerializeToString,
            aikgs__pb2.CuratorStats.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetCurationStats(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aikgs.AikgsService/GetCurationStats',
            aikgs__pb2.Empty.SerializeToString,
            aikgs__pb2.CurationStats.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StoreApiKey(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aikgs.AikgsService/StoreApiKey',
            aikgs__pb2.StoreKeyRequest.SerializeToString,
            aikgs__pb2.StoreKeyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetApiKey(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aikgs.AikgsService/GetApiKey',
            aikgs__pb2.GetKeyRequest.SerializeToString,
            aikgs__pb2.DecryptedKeyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListApiKeys(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aikgs.AikgsService/ListApiKeys',
            aikgs__pb2.ListKeysRequest.SerializeToString,
            aikgs__pb2.ListKeysResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RevokeApiKey(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aikgs.AikgsService/RevokeApiKey',
            aikgs__pb2.RevokeKeyRequest.SerializeToString,
            aikgs__pb2.StatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSharedKeyPool(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aikgs.AikgsService/GetSharedKeyPool',
            aikgs__pb2.SharedPoolRequest.SerializeToString,
            aikgs__pb2.SharedPoolResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Disburse(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aikgs.AikgsService/Disburse',
            aikgs__pb2.DisburseRequest.SerializeToString,
            aikgs__pb2.DisburseResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetPendingDisbursements(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aikgs.AikgsService/GetPendingDisbursements',
            aikgs__pb2.Empty.SerializeToString,
            aikgs__pb2.PendingDisbursementsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetFullStats(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aikgs.AikgsService/GetFullStats',
            aikgs__pb2.Empty.SerializeToString,
            aikgs__pb2.AikgsFullStats.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
