//! Abductive reasoning: hypothesis generation from observations.
//!
//! Given an observation (a fact that is true), abduction asks "what could
//! explain this?" by searching for rules whose consequent matches the
//! observation and proposing their antecedents as hypotheses.
//!
//! Hypotheses are scored by:
//! - **Simplicity**: fewer terms and variables = simpler = better (Occam's razor)
//! - **Consistency**: hypothesis does not contradict known facts
//! - **Explanatory power**: how many other observations the hypothesis also explains

use crate::formula::Formula;
use crate::knowledge_base::KnowledgeBase;
use crate::term::Term;
use crate::unify;
use serde::{Deserialize, Serialize};

/// A hypothesis generated by abductive reasoning.
#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct Hypothesis {
    /// The proposed explanation (a formula that, if true, would explain the observation).
    pub formula: Formula,
    /// Composite score in [0, 1]: higher = better hypothesis.
    pub score: f64,
    /// Other known facts that this hypothesis also explains.
    pub explains: Vec<Formula>,
    /// The original observation this hypothesis was generated for.
    pub observation: Formula,
}

/// Generate abductive hypotheses for an observation.
///
/// For each rule `(A -> B)` in the knowledge base, if `B` unifies with the
/// observation, then `A` (with the unifying substitution applied) is a
/// candidate hypothesis.
///
/// Hypotheses are ranked by a composite score:
/// `score = simplicity * 0.4 + consistency * 0.3 + explanatory_power * 0.3`
pub fn abduce(kb: &KnowledgeBase, observation: &Formula) -> Vec<Hypothesis> {
    let mut hypotheses = Vec::new();

    for rule in &kb.rules {
        if let Formula::Implies(antecedent, consequent) = rule {
            if let Some(sub) = unify::unify_atoms(observation, consequent) {
                let hypothesis_formula = antecedent.substitute(&sub);

                // Skip if the hypothesis is identical to the observation
                // (no explanatory value).
                if &hypothesis_formula == observation {
                    continue;
                }

                // Skip if the hypothesis is already a known fact
                // (trivial explanation).
                let already_known = kb
                    .facts
                    .iter()
                    .any(|f| unify::unify_atoms(&hypothesis_formula, f).is_some());
                if already_known {
                    continue;
                }

                let simplicity = simplicity_score(&hypothesis_formula);
                let consistency = consistency_score(&hypothesis_formula, kb);
                let (explanatory, explains) =
                    explanatory_power(&hypothesis_formula, kb, observation);

                let score = simplicity * 0.4 + consistency * 0.3 + explanatory * 0.3;

                hypotheses.push(Hypothesis {
                    formula: hypothesis_formula,
                    score,
                    explains,
                    observation: observation.clone(),
                });
            }
        }
    }

    // Sort by score descending.
    hypotheses.sort_by(|a, b| b.score.partial_cmp(&a.score).unwrap_or(std::cmp::Ordering::Equal));
    hypotheses
}

/// Simplicity: fewer terms and fewer variables = simpler.
/// Returns a score in (0, 1].
fn simplicity_score(formula: &Formula) -> f64 {
    let size = formula_size(formula);
    let vars = formula.free_variables().len();
    // Inverse of complexity: simpler formulas score higher.
    1.0 / (1.0 + size as f64 + vars as f64 * 0.5)
}

/// Count the total number of terms in a formula (rough measure of complexity).
fn formula_size(formula: &Formula) -> usize {
    match formula {
        Formula::Atom(_, terms) => terms.iter().map(|t| term_size(t)).sum::<usize>() + 1,
        Formula::Not(f) => formula_size(f) + 1,
        Formula::And(fs) | Formula::Or(fs) => {
            fs.iter().map(|f| formula_size(f)).sum::<usize>() + 1
        }
        Formula::Implies(a, b) => formula_size(a) + formula_size(b) + 1,
        Formula::ForAll(_, body) | Formula::Exists(_, body) => formula_size(body) + 1,
    }
}

fn term_size(term: &Term) -> usize {
    match term {
        Term::Variable(_) | Term::Constant(_) => 1,
        Term::Compound(_, args) => 1 + args.iter().map(|a| term_size(a)).sum::<usize>(),
    }
}

/// Consistency: check that the hypothesis does not contradict known facts.
/// Returns 1.0 if consistent, 0.0 if contradictory.
fn consistency_score(hypothesis: &Formula, kb: &KnowledgeBase) -> f64 {
    let negated = hypothesis.negate();
    for fact in &kb.facts {
        if unify::unify_atoms(&negated, fact).is_some() {
            return 0.0; // Directly contradicts a known fact.
        }
    }
    1.0
}

/// Explanatory power: how many other facts in the KB does this hypothesis explain?
/// Returns a score in [0, 1] and the list of explained facts.
fn explanatory_power(
    hypothesis: &Formula,
    kb: &KnowledgeBase,
    original_observation: &Formula,
) -> (f64, Vec<Formula>) {
    let mut explained = Vec::new();

    for rule in &kb.rules {
        if let Formula::Implies(antecedent, consequent) = rule {
            // If hypothesis unifies with the antecedent, the consequent is explained.
            if let Some(sub) = unify::unify_atoms(hypothesis, antecedent) {
                let derived = consequent.substitute(&sub);
                // Check if this matches any existing fact (besides the original observation).
                for fact in &kb.facts {
                    if unify::unify_atoms(&derived, fact).is_some()
                        && unify::unify_atoms(&derived, original_observation).is_none()
                    {
                        explained.push(fact.clone());
                    }
                }
            }
        }
    }

    let score = if kb.facts.is_empty() {
        0.0
    } else {
        (explained.len() as f64 / kb.facts.len() as f64).min(1.0)
    };
    (score, explained)
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;
    use crate::term::{Symbol, Term};

    fn sym(id: u32) -> Symbol {
        Symbol(id)
    }

    fn medical_kb() -> KnowledgeBase {
        let flu = sym(0);
        let fever = sym(1);
        let cough = sym(2);
        let cold = sym(3);
        let infection = sym(4);

        let mut kb = KnowledgeBase::new();

        // Facts: patient has fever and cough
        kb.add_fact(Formula::atom(fever, vec![Term::Constant(sym(10))])); // fever(patient)
        kb.add_fact(Formula::atom(cough, vec![Term::Constant(sym(10))])); // cough(patient)

        // Rules:
        // flu(X) -> fever(X)
        kb.add_rule(Formula::implies(
            Formula::atom(flu, vec![Term::var(0)]),
            Formula::atom(fever, vec![Term::var(0)]),
        ));
        // cold(X) -> cough(X)
        kb.add_rule(Formula::implies(
            Formula::atom(cold, vec![Term::var(0)]),
            Formula::atom(cough, vec![Term::var(0)]),
        ));
        // infection(X) -> fever(X)
        kb.add_rule(Formula::implies(
            Formula::atom(infection, vec![Term::var(0)]),
            Formula::atom(fever, vec![Term::var(0)]),
        ));
        // flu(X) -> cough(X)  (flu also explains cough)
        kb.add_rule(Formula::implies(
            Formula::atom(flu, vec![Term::var(0)]),
            Formula::atom(cough, vec![Term::var(0)]),
        ));

        kb
    }

    #[test]
    fn test_abduce_finds_hypotheses() {
        let kb = medical_kb();
        let fever = sym(1);
        let observation = Formula::atom(fever, vec![Term::Constant(sym(10))]);

        let hypotheses = abduce(&kb, &observation);
        assert!(
            !hypotheses.is_empty(),
            "Should find at least one hypothesis for fever"
        );

        // Should find flu(patient) and infection(patient) as hypotheses
        assert!(
            hypotheses.len() >= 2,
            "Expected at least 2 hypotheses, got {}",
            hypotheses.len()
        );
    }

    #[test]
    fn test_abduce_ranking() {
        let kb = medical_kb();
        let fever = sym(1);
        let observation = Formula::atom(fever, vec![Term::Constant(sym(10))]);

        let hypotheses = abduce(&kb, &observation);
        // Scores should be in descending order.
        for i in 1..hypotheses.len() {
            assert!(
                hypotheses[i - 1].score >= hypotheses[i].score,
                "Hypotheses not sorted by score"
            );
        }
    }

    #[test]
    fn test_abduce_explanatory_power() {
        let kb = medical_kb();
        let cough = sym(2);
        let observation = Formula::atom(cough, vec![Term::Constant(sym(10))]);

        let hypotheses = abduce(&kb, &observation);
        // flu(patient) should have higher explanatory power than cold(patient)
        // because flu also explains fever (which is a known fact).
        // Find flu hypothesis
        let flu = sym(0);
        let flu_hyp = hypotheses.iter().find(|h| {
            matches!(&h.formula, Formula::Atom(p, _) if *p == flu)
        });
        assert!(
            flu_hyp.is_some(),
            "Should find flu as hypothesis for cough"
        );
    }

    #[test]
    fn test_abduce_no_hypotheses_for_unknown() {
        let kb = medical_kb();
        // Query something with no matching rule consequent.
        let unknown = sym(99);
        let observation = Formula::atom(unknown, vec![Term::Constant(sym(10))]);
        let hypotheses = abduce(&kb, &observation);
        assert!(hypotheses.is_empty());
    }

    #[test]
    fn test_abduce_consistency_filters_contradictions() {
        let p = sym(0);
        let q = sym(1);
        let patient = sym(10);

        let mut kb = KnowledgeBase::new();
        kb.add_fact(Formula::atom(q, vec![Term::Constant(patient)]));
        // ~p(X) is a known fact
        kb.add_fact(Formula::not(Formula::atom(p, vec![Term::Constant(patient)])));
        // Rule: p(X) -> q(X)
        kb.add_rule(Formula::implies(
            Formula::atom(p, vec![Term::var(0)]),
            Formula::atom(q, vec![Term::var(0)]),
        ));

        let observation = Formula::atom(q, vec![Term::Constant(patient)]);
        let hypotheses = abduce(&kb, &observation);
        // p(patient) contradicts ~p(patient), so it should score 0 on consistency.
        for h in &hypotheses {
            if matches!(&h.formula, Formula::Atom(pred, _) if *pred == p) {
                assert!(
                    h.score < 0.5,
                    "Contradictory hypothesis should have low score, got {}",
                    h.score
                );
            }
        }
    }

    #[test]
    fn test_simplicity_prefers_simpler() {
        // A simpler hypothesis (fewer terms) should score higher on simplicity.
        let simple = Formula::atom(sym(0), vec![Term::Constant(sym(10))]);
        let complex = Formula::and(vec![
            Formula::atom(sym(0), vec![Term::Constant(sym(10))]),
            Formula::atom(sym(1), vec![Term::Constant(sym(10)), Term::Constant(sym(11))]),
        ]);
        let s1 = simplicity_score(&simple);
        let s2 = simplicity_score(&complex);
        assert!(s1 > s2, "Simpler formula should have higher simplicity score");
    }
}
