# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import graph_shard_pb2 as graph__shard__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in graph_shard_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class GraphShardServiceStub(object):
    """── Aether Graph Shard Service ──────────────────────────────────────
    Distributed knowledge graph with domain-based sharding.
    Designed for 1 trillion+ nodes across 10 Sephirot domains × 256 sub-shards.

    Architecture:
    Client → ShardRouter → DomainShard (RocksDB)
    → CrossShardQuery (scatter-gather)
    → IncrementalMerkle (per-shard roots → global root)

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.PutNode = channel.unary_unary(
                '/graph_shard.GraphShardService/PutNode',
                request_serializer=graph__shard__pb2.PutNodeRequest.SerializeToString,
                response_deserializer=graph__shard__pb2.PutNodeResponse.FromString,
                _registered_method=True)
        self.GetNode = channel.unary_unary(
                '/graph_shard.GraphShardService/GetNode',
                request_serializer=graph__shard__pb2.GetNodeRequest.SerializeToString,
                response_deserializer=graph__shard__pb2.GetNodeResponse.FromString,
                _registered_method=True)
        self.GetNodes = channel.unary_unary(
                '/graph_shard.GraphShardService/GetNodes',
                request_serializer=graph__shard__pb2.GetNodesRequest.SerializeToString,
                response_deserializer=graph__shard__pb2.GetNodesResponse.FromString,
                _registered_method=True)
        self.DeleteNode = channel.unary_unary(
                '/graph_shard.GraphShardService/DeleteNode',
                request_serializer=graph__shard__pb2.DeleteNodeRequest.SerializeToString,
                response_deserializer=graph__shard__pb2.DeleteNodeResponse.FromString,
                _registered_method=True)
        self.UpdateConfidence = channel.unary_unary(
                '/graph_shard.GraphShardService/UpdateConfidence',
                request_serializer=graph__shard__pb2.UpdateConfidenceRequest.SerializeToString,
                response_deserializer=graph__shard__pb2.UpdateConfidenceResponse.FromString,
                _registered_method=True)
        self.PutEdge = channel.unary_unary(
                '/graph_shard.GraphShardService/PutEdge',
                request_serializer=graph__shard__pb2.PutEdgeRequest.SerializeToString,
                response_deserializer=graph__shard__pb2.PutEdgeResponse.FromString,
                _registered_method=True)
        self.GetEdges = channel.unary_unary(
                '/graph_shard.GraphShardService/GetEdges',
                request_serializer=graph__shard__pb2.GetEdgesRequest.SerializeToString,
                response_deserializer=graph__shard__pb2.GetEdgesResponse.FromString,
                _registered_method=True)
        self.GetNeighbors = channel.unary_unary(
                '/graph_shard.GraphShardService/GetNeighbors',
                request_serializer=graph__shard__pb2.GetNeighborsRequest.SerializeToString,
                response_deserializer=graph__shard__pb2.GetNeighborsResponse.FromString,
                _registered_method=True)
        self.Search = channel.unary_unary(
                '/graph_shard.GraphShardService/Search',
                request_serializer=graph__shard__pb2.SearchRequest.SerializeToString,
                response_deserializer=graph__shard__pb2.SearchResponse.FromString,
                _registered_method=True)
        self.VectorSearch = channel.unary_unary(
                '/graph_shard.GraphShardService/VectorSearch',
                request_serializer=graph__shard__pb2.VectorSearchRequest.SerializeToString,
                response_deserializer=graph__shard__pb2.VectorSearchResponse.FromString,
                _registered_method=True)
        self.DomainSearch = channel.unary_unary(
                '/graph_shard.GraphShardService/DomainSearch',
                request_serializer=graph__shard__pb2.DomainSearchRequest.SerializeToString,
                response_deserializer=graph__shard__pb2.DomainSearchResponse.FromString,
                _registered_method=True)
        self.CrossDomainSearch = channel.unary_unary(
                '/graph_shard.GraphShardService/CrossDomainSearch',
                request_serializer=graph__shard__pb2.CrossDomainSearchRequest.SerializeToString,
                response_deserializer=graph__shard__pb2.CrossDomainSearchResponse.FromString,
                _registered_method=True)
        self.GetMerkleRoot = channel.unary_unary(
                '/graph_shard.GraphShardService/GetMerkleRoot',
                request_serializer=graph__shard__pb2.MerkleRootRequest.SerializeToString,
                response_deserializer=graph__shard__pb2.MerkleRootResponse.FromString,
                _registered_method=True)
        self.GetShardMerkleRoots = channel.unary_unary(
                '/graph_shard.GraphShardService/GetShardMerkleRoots',
                request_serializer=graph__shard__pb2.ShardMerkleRootsRequest.SerializeToString,
                response_deserializer=graph__shard__pb2.ShardMerkleRootsResponse.FromString,
                _registered_method=True)
        self.GetStats = channel.unary_unary(
                '/graph_shard.GraphShardService/GetStats',
                request_serializer=graph__shard__pb2.StatsRequest.SerializeToString,
                response_deserializer=graph__shard__pb2.StatsResponse.FromString,
                _registered_method=True)
        self.GetShardStats = channel.unary_unary(
                '/graph_shard.GraphShardService/GetShardStats',
                request_serializer=graph__shard__pb2.ShardStatsRequest.SerializeToString,
                response_deserializer=graph__shard__pb2.ShardStatsResponse.FromString,
                _registered_method=True)
        self.HealthCheck = channel.unary_unary(
                '/graph_shard.GraphShardService/HealthCheck',
                request_serializer=graph__shard__pb2.HealthRequest.SerializeToString,
                response_deserializer=graph__shard__pb2.HealthResponse.FromString,
                _registered_method=True)
        self.BulkPutNodes = channel.stream_unary(
                '/graph_shard.GraphShardService/BulkPutNodes',
                request_serializer=graph__shard__pb2.PutNodeRequest.SerializeToString,
                response_deserializer=graph__shard__pb2.BulkPutResponse.FromString,
                _registered_method=True)
        self.BulkPutEdges = channel.stream_unary(
                '/graph_shard.GraphShardService/BulkPutEdges',
                request_serializer=graph__shard__pb2.PutEdgeRequest.SerializeToString,
                response_deserializer=graph__shard__pb2.BulkPutResponse.FromString,
                _registered_method=True)
        self.StreamNodes = channel.unary_stream(
                '/graph_shard.GraphShardService/StreamNodes',
                request_serializer=graph__shard__pb2.StreamNodesRequest.SerializeToString,
                response_deserializer=graph__shard__pb2.NodeRecord.FromString,
                _registered_method=True)
        self.RebalanceShards = channel.unary_unary(
                '/graph_shard.GraphShardService/RebalanceShards',
                request_serializer=graph__shard__pb2.RebalanceRequest.SerializeToString,
                response_deserializer=graph__shard__pb2.RebalanceResponse.FromString,
                _registered_method=True)
        self.CompactShard = channel.unary_unary(
                '/graph_shard.GraphShardService/CompactShard',
                request_serializer=graph__shard__pb2.CompactRequest.SerializeToString,
                response_deserializer=graph__shard__pb2.CompactResponse.FromString,
                _registered_method=True)
        self.GetShardMap = channel.unary_unary(
                '/graph_shard.GraphShardService/GetShardMap',
                request_serializer=graph__shard__pb2.ShardMapRequest.SerializeToString,
                response_deserializer=graph__shard__pb2.ShardMapResponse.FromString,
                _registered_method=True)


class GraphShardServiceServicer(object):
    """── Aether Graph Shard Service ──────────────────────────────────────
    Distributed knowledge graph with domain-based sharding.
    Designed for 1 trillion+ nodes across 10 Sephirot domains × 256 sub-shards.

    Architecture:
    Client → ShardRouter → DomainShard (RocksDB)
    → CrossShardQuery (scatter-gather)
    → IncrementalMerkle (per-shard roots → global root)

    """

    def PutNode(self, request, context):
        """── Node Operations ────────────────────────────────────────────
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetNode(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetNodes(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteNode(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateConfidence(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PutEdge(self, request, context):
        """── Edge Operations ────────────────────────────────────────────
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetEdges(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetNeighbors(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Search(self, request, context):
        """── Search ─────────────────────────────────────────────────────
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def VectorSearch(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DomainSearch(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CrossDomainSearch(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetMerkleRoot(self, request, context):
        """── Merkle & Integrity ─────────────────────────────────────────
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetShardMerkleRoots(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetStats(self, request, context):
        """── Statistics & Health ────────────────────────────────────────
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetShardStats(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HealthCheck(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BulkPutNodes(self, request_iterator, context):
        """── Bulk Operations ────────────────────────────────────────────
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BulkPutEdges(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamNodes(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RebalanceShards(self, request, context):
        """── Shard Management ───────────────────────────────────────────
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CompactShard(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetShardMap(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GraphShardServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'PutNode': grpc.unary_unary_rpc_method_handler(
                    servicer.PutNode,
                    request_deserializer=graph__shard__pb2.PutNodeRequest.FromString,
                    response_serializer=graph__shard__pb2.PutNodeResponse.SerializeToString,
            ),
            'GetNode': grpc.unary_unary_rpc_method_handler(
                    servicer.GetNode,
                    request_deserializer=graph__shard__pb2.GetNodeRequest.FromString,
                    response_serializer=graph__shard__pb2.GetNodeResponse.SerializeToString,
            ),
            'GetNodes': grpc.unary_unary_rpc_method_handler(
                    servicer.GetNodes,
                    request_deserializer=graph__shard__pb2.GetNodesRequest.FromString,
                    response_serializer=graph__shard__pb2.GetNodesResponse.SerializeToString,
            ),
            'DeleteNode': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteNode,
                    request_deserializer=graph__shard__pb2.DeleteNodeRequest.FromString,
                    response_serializer=graph__shard__pb2.DeleteNodeResponse.SerializeToString,
            ),
            'UpdateConfidence': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateConfidence,
                    request_deserializer=graph__shard__pb2.UpdateConfidenceRequest.FromString,
                    response_serializer=graph__shard__pb2.UpdateConfidenceResponse.SerializeToString,
            ),
            'PutEdge': grpc.unary_unary_rpc_method_handler(
                    servicer.PutEdge,
                    request_deserializer=graph__shard__pb2.PutEdgeRequest.FromString,
                    response_serializer=graph__shard__pb2.PutEdgeResponse.SerializeToString,
            ),
            'GetEdges': grpc.unary_unary_rpc_method_handler(
                    servicer.GetEdges,
                    request_deserializer=graph__shard__pb2.GetEdgesRequest.FromString,
                    response_serializer=graph__shard__pb2.GetEdgesResponse.SerializeToString,
            ),
            'GetNeighbors': grpc.unary_unary_rpc_method_handler(
                    servicer.GetNeighbors,
                    request_deserializer=graph__shard__pb2.GetNeighborsRequest.FromString,
                    response_serializer=graph__shard__pb2.GetNeighborsResponse.SerializeToString,
            ),
            'Search': grpc.unary_unary_rpc_method_handler(
                    servicer.Search,
                    request_deserializer=graph__shard__pb2.SearchRequest.FromString,
                    response_serializer=graph__shard__pb2.SearchResponse.SerializeToString,
            ),
            'VectorSearch': grpc.unary_unary_rpc_method_handler(
                    servicer.VectorSearch,
                    request_deserializer=graph__shard__pb2.VectorSearchRequest.FromString,
                    response_serializer=graph__shard__pb2.VectorSearchResponse.SerializeToString,
            ),
            'DomainSearch': grpc.unary_unary_rpc_method_handler(
                    servicer.DomainSearch,
                    request_deserializer=graph__shard__pb2.DomainSearchRequest.FromString,
                    response_serializer=graph__shard__pb2.DomainSearchResponse.SerializeToString,
            ),
            'CrossDomainSearch': grpc.unary_unary_rpc_method_handler(
                    servicer.CrossDomainSearch,
                    request_deserializer=graph__shard__pb2.CrossDomainSearchRequest.FromString,
                    response_serializer=graph__shard__pb2.CrossDomainSearchResponse.SerializeToString,
            ),
            'GetMerkleRoot': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMerkleRoot,
                    request_deserializer=graph__shard__pb2.MerkleRootRequest.FromString,
                    response_serializer=graph__shard__pb2.MerkleRootResponse.SerializeToString,
            ),
            'GetShardMerkleRoots': grpc.unary_unary_rpc_method_handler(
                    servicer.GetShardMerkleRoots,
                    request_deserializer=graph__shard__pb2.ShardMerkleRootsRequest.FromString,
                    response_serializer=graph__shard__pb2.ShardMerkleRootsResponse.SerializeToString,
            ),
            'GetStats': grpc.unary_unary_rpc_method_handler(
                    servicer.GetStats,
                    request_deserializer=graph__shard__pb2.StatsRequest.FromString,
                    response_serializer=graph__shard__pb2.StatsResponse.SerializeToString,
            ),
            'GetShardStats': grpc.unary_unary_rpc_method_handler(
                    servicer.GetShardStats,
                    request_deserializer=graph__shard__pb2.ShardStatsRequest.FromString,
                    response_serializer=graph__shard__pb2.ShardStatsResponse.SerializeToString,
            ),
            'HealthCheck': grpc.unary_unary_rpc_method_handler(
                    servicer.HealthCheck,
                    request_deserializer=graph__shard__pb2.HealthRequest.FromString,
                    response_serializer=graph__shard__pb2.HealthResponse.SerializeToString,
            ),
            'BulkPutNodes': grpc.stream_unary_rpc_method_handler(
                    servicer.BulkPutNodes,
                    request_deserializer=graph__shard__pb2.PutNodeRequest.FromString,
                    response_serializer=graph__shard__pb2.BulkPutResponse.SerializeToString,
            ),
            'BulkPutEdges': grpc.stream_unary_rpc_method_handler(
                    servicer.BulkPutEdges,
                    request_deserializer=graph__shard__pb2.PutEdgeRequest.FromString,
                    response_serializer=graph__shard__pb2.BulkPutResponse.SerializeToString,
            ),
            'StreamNodes': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamNodes,
                    request_deserializer=graph__shard__pb2.StreamNodesRequest.FromString,
                    response_serializer=graph__shard__pb2.NodeRecord.SerializeToString,
            ),
            'RebalanceShards': grpc.unary_unary_rpc_method_handler(
                    servicer.RebalanceShards,
                    request_deserializer=graph__shard__pb2.RebalanceRequest.FromString,
                    response_serializer=graph__shard__pb2.RebalanceResponse.SerializeToString,
            ),
            'CompactShard': grpc.unary_unary_rpc_method_handler(
                    servicer.CompactShard,
                    request_deserializer=graph__shard__pb2.CompactRequest.FromString,
                    response_serializer=graph__shard__pb2.CompactResponse.SerializeToString,
            ),
            'GetShardMap': grpc.unary_unary_rpc_method_handler(
                    servicer.GetShardMap,
                    request_deserializer=graph__shard__pb2.ShardMapRequest.FromString,
                    response_serializer=graph__shard__pb2.ShardMapResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'graph_shard.GraphShardService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('graph_shard.GraphShardService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class GraphShardService(object):
    """── Aether Graph Shard Service ──────────────────────────────────────
    Distributed knowledge graph with domain-based sharding.
    Designed for 1 trillion+ nodes across 10 Sephirot domains × 256 sub-shards.

    Architecture:
    Client → ShardRouter → DomainShard (RocksDB)
    → CrossShardQuery (scatter-gather)
    → IncrementalMerkle (per-shard roots → global root)

    """

    @staticmethod
    def PutNode(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/graph_shard.GraphShardService/PutNode',
            graph__shard__pb2.PutNodeRequest.SerializeToString,
            graph__shard__pb2.PutNodeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetNode(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/graph_shard.GraphShardService/GetNode',
            graph__shard__pb2.GetNodeRequest.SerializeToString,
            graph__shard__pb2.GetNodeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetNodes(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/graph_shard.GraphShardService/GetNodes',
            graph__shard__pb2.GetNodesRequest.SerializeToString,
            graph__shard__pb2.GetNodesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteNode(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/graph_shard.GraphShardService/DeleteNode',
            graph__shard__pb2.DeleteNodeRequest.SerializeToString,
            graph__shard__pb2.DeleteNodeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateConfidence(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/graph_shard.GraphShardService/UpdateConfidence',
            graph__shard__pb2.UpdateConfidenceRequest.SerializeToString,
            graph__shard__pb2.UpdateConfidenceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PutEdge(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/graph_shard.GraphShardService/PutEdge',
            graph__shard__pb2.PutEdgeRequest.SerializeToString,
            graph__shard__pb2.PutEdgeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetEdges(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/graph_shard.GraphShardService/GetEdges',
            graph__shard__pb2.GetEdgesRequest.SerializeToString,
            graph__shard__pb2.GetEdgesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetNeighbors(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/graph_shard.GraphShardService/GetNeighbors',
            graph__shard__pb2.GetNeighborsRequest.SerializeToString,
            graph__shard__pb2.GetNeighborsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Search(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/graph_shard.GraphShardService/Search',
            graph__shard__pb2.SearchRequest.SerializeToString,
            graph__shard__pb2.SearchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def VectorSearch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/graph_shard.GraphShardService/VectorSearch',
            graph__shard__pb2.VectorSearchRequest.SerializeToString,
            graph__shard__pb2.VectorSearchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DomainSearch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/graph_shard.GraphShardService/DomainSearch',
            graph__shard__pb2.DomainSearchRequest.SerializeToString,
            graph__shard__pb2.DomainSearchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CrossDomainSearch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/graph_shard.GraphShardService/CrossDomainSearch',
            graph__shard__pb2.CrossDomainSearchRequest.SerializeToString,
            graph__shard__pb2.CrossDomainSearchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetMerkleRoot(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/graph_shard.GraphShardService/GetMerkleRoot',
            graph__shard__pb2.MerkleRootRequest.SerializeToString,
            graph__shard__pb2.MerkleRootResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetShardMerkleRoots(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/graph_shard.GraphShardService/GetShardMerkleRoots',
            graph__shard__pb2.ShardMerkleRootsRequest.SerializeToString,
            graph__shard__pb2.ShardMerkleRootsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetStats(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/graph_shard.GraphShardService/GetStats',
            graph__shard__pb2.StatsRequest.SerializeToString,
            graph__shard__pb2.StatsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetShardStats(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/graph_shard.GraphShardService/GetShardStats',
            graph__shard__pb2.ShardStatsRequest.SerializeToString,
            graph__shard__pb2.ShardStatsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def HealthCheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/graph_shard.GraphShardService/HealthCheck',
            graph__shard__pb2.HealthRequest.SerializeToString,
            graph__shard__pb2.HealthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def BulkPutNodes(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/graph_shard.GraphShardService/BulkPutNodes',
            graph__shard__pb2.PutNodeRequest.SerializeToString,
            graph__shard__pb2.BulkPutResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def BulkPutEdges(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/graph_shard.GraphShardService/BulkPutEdges',
            graph__shard__pb2.PutEdgeRequest.SerializeToString,
            graph__shard__pb2.BulkPutResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamNodes(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/graph_shard.GraphShardService/StreamNodes',
            graph__shard__pb2.StreamNodesRequest.SerializeToString,
            graph__shard__pb2.NodeRecord.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RebalanceShards(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/graph_shard.GraphShardService/RebalanceShards',
            graph__shard__pb2.RebalanceRequest.SerializeToString,
            graph__shard__pb2.RebalanceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CompactShard(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/graph_shard.GraphShardService/CompactShard',
            graph__shard__pb2.CompactRequest.SerializeToString,
            graph__shard__pb2.CompactResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetShardMap(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/graph_shard.GraphShardService/GetShardMap',
            graph__shard__pb2.ShardMapRequest.SerializeToString,
            graph__shard__pb2.ShardMapResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
