# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: p2p_service.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'p2p_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11p2p_service.proto\x12\x0bp2p_service\"0\n\x10\x42roadcastRequest\x12\x0e\n\x06height\x18\x01 \x01(\x04\x12\x0c\n\x04hash\x18\x02 \x01(\t\"$\n\x11\x42roadcastResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\"\x12\n\x10PeerStatsRequest\"\'\n\x11PeerStatsResponse\x12\x12\n\npeer_count\x18\x01 \x01(\r2\xa5\x01\n\x03P2P\x12O\n\x0e\x42roadcastBlock\x12\x1d.p2p_service.BroadcastRequest\x1a\x1e.p2p_service.BroadcastResponse\x12M\n\x0cGetPeerStats\x12\x1d.p2p_service.PeerStatsRequest\x1a\x1e.p2p_service.PeerStatsResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'p2p_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_BROADCASTREQUEST']._serialized_start=34
  _globals['_BROADCASTREQUEST']._serialized_end=82
  _globals['_BROADCASTRESPONSE']._serialized_start=84
  _globals['_BROADCASTRESPONSE']._serialized_end=120
  _globals['_PEERSTATSREQUEST']._serialized_start=122
  _globals['_PEERSTATSREQUEST']._serialized_end=140
  _globals['_PEERSTATSRESPONSE']._serialized_start=142
  _globals['_PEERSTATSRESPONSE']._serialized_end=181
  _globals['_P2P']._serialized_start=184
  _globals['_P2P']._serialized_end=349
# @@protoc_insertion_point(module_scope)
