# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import p2p_service_pb2 as p2p__service__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in p2p_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class P2PStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.BroadcastBlock = channel.unary_unary(
                '/p2p_service.P2P/BroadcastBlock',
                request_serializer=p2p__service__pb2.BroadcastRequest.SerializeToString,
                response_deserializer=p2p__service__pb2.BroadcastResponse.FromString,
                _registered_method=True)
        self.GetPeerStats = channel.unary_unary(
                '/p2p_service.P2P/GetPeerStats',
                request_serializer=p2p__service__pb2.PeerStatsRequest.SerializeToString,
                response_deserializer=p2p__service__pb2.PeerStatsResponse.FromString,
                _registered_method=True)


class P2PServicer(object):
    """Missing associated documentation comment in .proto file."""

    def BroadcastBlock(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPeerStats(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_P2PServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'BroadcastBlock': grpc.unary_unary_rpc_method_handler(
                    servicer.BroadcastBlock,
                    request_deserializer=p2p__service__pb2.BroadcastRequest.FromString,
                    response_serializer=p2p__service__pb2.BroadcastResponse.SerializeToString,
            ),
            'GetPeerStats': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPeerStats,
                    request_deserializer=p2p__service__pb2.PeerStatsRequest.FromString,
                    response_serializer=p2p__service__pb2.PeerStatsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'p2p_service.P2P', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('p2p_service.P2P', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class P2P(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def BroadcastBlock(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/p2p_service.P2P/BroadcastBlock',
            p2p__service__pb2.BroadcastRequest.SerializeToString,
            p2p__service__pb2.BroadcastResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetPeerStats(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/p2p_service.P2P/GetPeerStats',
            p2p__service__pb2.PeerStatsRequest.SerializeToString,
            p2p__service__pb2.PeerStatsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
