//! Autogenerated weights for `pallet_qbc_consensus`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARKING CLI.
//! Manual edits will be lost on regeneration.
//! Analytical estimates used until real benchmarks are run.

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use core::marker::PhantomData;

/// Weight functions needed for `pallet_qbc_consensus`.
pub trait WeightInfo {
    fn submit_mining_proof() -> Weight;
}

/// Weights for `pallet_qbc_consensus` using the Substrate node and recommended hardware.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
    /// Analytical weight for `submit_mining_proof`.
    ///
    /// Includes: Ed25519 signature verify (~50us), VQE energy recompute (~200us),
    /// Hamiltonian seed derivation (~10us), difficulty adjustment (~50us),
    /// coinbase creation + storage writes (~100us), SUSY solution storage (~25us),
    /// proof hash storage + pruning (~50us), bimetric phase computation (~25us),
    /// event deposits (~25us).
    ///
    /// Storage: CurrentDifficulty (r:1), BlockTimestamps (r:1, w:1),
    ///          CurrentHeight (r:1), SusySolutions (r:0, w:2),
    ///          RecentProofHashes (r:1, w:1+), LastMinerBlock (r:1, w:1),
    ///          NetworkTheta (r:1, w:1), NetworkAlpha (r:1, w:1),
    ///          LastMiner (w:1), BlocksMined (r:1, w:1),
    ///          + UTXO pallet reads/writes for coinbase + economics pallet
    fn submit_mining_proof() -> Weight {
        // Total analytical estimate: ~750us
        Weight::from_parts(750_000u64, 0)
            .saturating_add(T::DbWeight::get().reads(12))
            .saturating_add(T::DbWeight::get().writes(12))
    }
}

/// Default implementation for tests.
impl WeightInfo for () {
    fn submit_mining_proof() -> Weight {
        Weight::from_parts(750_000u64, 0)
            .saturating_add(RocksDbWeight::get().reads(12))
            .saturating_add(RocksDbWeight::get().writes(12))
    }
}
