//! Autogenerated weights for `pallet_qbc_dilithium`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARKING CLI.
//! Manual edits will be lost on regeneration.
//! Analytical estimates used until real benchmarks are run.

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use core::marker::PhantomData;

/// Weight functions needed for `pallet_qbc_dilithium`.
pub trait WeightInfo {
    fn register_key() -> Weight;
    fn revoke_key() -> Weight;
    fn sudo_register_key_for_address() -> Weight;
}

/// Weights for `pallet_qbc_dilithium` using the Substrate node and recommended hardware.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
    /// Analytical weight for `register_key`.
    ///
    /// SHA2-256 hash (10us) + 1 storage read (25us) + 1 storage read revoked (25us)
    /// + 1 storage write (25us) + key validation (~200us)
    /// Total: ~260us
    ///
    /// Storage: PublicKeys (r:1, w:1), RevokedKeys (r:1), TotalKeys (r:1, w:1)
    fn register_key() -> Weight {
        Weight::from_parts(260_000u64, 0)
            .saturating_add(T::DbWeight::get().reads(3))
            .saturating_add(T::DbWeight::get().writes(2))
    }

    /// Analytical weight for `revoke_key`.
    ///
    /// 1 Dilithium5 verify (~800us) + 3 storage reads + 3 storage writes
    /// Total: ~875us
    ///
    /// Storage: PublicKeys (r:1, w:1), RevokedKeys (r:1, w:1), TotalKeys (r:1, w:1)
    fn revoke_key() -> Weight {
        Weight::from_parts(875_000u64, 0)
            .saturating_add(T::DbWeight::get().reads(3))
            .saturating_add(T::DbWeight::get().writes(3))
    }

    /// Analytical weight for `sudo_register_key_for_address`.
    ///
    /// Same as register_key but called via sudo.
    fn sudo_register_key_for_address() -> Weight {
        Weight::from_parts(260_000u64, 0)
            .saturating_add(T::DbWeight::get().reads(3))
            .saturating_add(T::DbWeight::get().writes(2))
    }
}

/// Default implementation for tests.
impl WeightInfo for () {
    fn register_key() -> Weight {
        Weight::from_parts(260_000u64, 0)
            .saturating_add(RocksDbWeight::get().reads(3))
            .saturating_add(RocksDbWeight::get().writes(2))
    }

    fn revoke_key() -> Weight {
        Weight::from_parts(875_000u64, 0)
            .saturating_add(RocksDbWeight::get().reads(3))
            .saturating_add(RocksDbWeight::get().writes(3))
    }

    fn sudo_register_key_for_address() -> Weight {
        Weight::from_parts(260_000u64, 0)
            .saturating_add(RocksDbWeight::get().reads(3))
            .saturating_add(RocksDbWeight::get().writes(2))
    }
}
