# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import exchange_pb2 as exchange__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in exchange_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ExchangeStub(object):
    """─── Exchange Service ─────────────────────────────────────────────────
    gRPC bridge between Python blockchain node and Rust exchange engine.
    Handles order matching, synthetic assets, oracle pricing, collateral.

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.PlaceOrder = channel.unary_unary(
                '/exchange.Exchange/PlaceOrder',
                request_serializer=exchange__pb2.PlaceOrderRequest.SerializeToString,
                response_deserializer=exchange__pb2.PlaceOrderResponse.FromString,
                _registered_method=True)
        self.CancelOrder = channel.unary_unary(
                '/exchange.Exchange/CancelOrder',
                request_serializer=exchange__pb2.CancelOrderRequest.SerializeToString,
                response_deserializer=exchange__pb2.CancelOrderResponse.FromString,
                _registered_method=True)
        self.GetOrderBook = channel.unary_unary(
                '/exchange.Exchange/GetOrderBook',
                request_serializer=exchange__pb2.GetOrderBookRequest.SerializeToString,
                response_deserializer=exchange__pb2.OrderBookResponse.FromString,
                _registered_method=True)
        self.GetUserOrders = channel.unary_unary(
                '/exchange.Exchange/GetUserOrders',
                request_serializer=exchange__pb2.GetUserOrdersRequest.SerializeToString,
                response_deserializer=exchange__pb2.UserOrdersResponse.FromString,
                _registered_method=True)
        self.GetMarkets = channel.unary_unary(
                '/exchange.Exchange/GetMarkets',
                request_serializer=exchange__pb2.GetMarketsRequest.SerializeToString,
                response_deserializer=exchange__pb2.MarketsResponse.FromString,
                _registered_method=True)
        self.GetRecentTrades = channel.unary_unary(
                '/exchange.Exchange/GetRecentTrades',
                request_serializer=exchange__pb2.GetRecentTradesRequest.SerializeToString,
                response_deserializer=exchange__pb2.RecentTradesResponse.FromString,
                _registered_method=True)
        self.GetMarketSummary = channel.unary_unary(
                '/exchange.Exchange/GetMarketSummary',
                request_serializer=exchange__pb2.GetMarketSummaryRequest.SerializeToString,
                response_deserializer=exchange__pb2.MarketSummaryResponse.FromString,
                _registered_method=True)
        self.Deposit = channel.unary_unary(
                '/exchange.Exchange/Deposit',
                request_serializer=exchange__pb2.DepositRequest.SerializeToString,
                response_deserializer=exchange__pb2.BalanceResponse.FromString,
                _registered_method=True)
        self.Withdraw = channel.unary_unary(
                '/exchange.Exchange/Withdraw',
                request_serializer=exchange__pb2.WithdrawRequest.SerializeToString,
                response_deserializer=exchange__pb2.BalanceResponse.FromString,
                _registered_method=True)
        self.GetBalance = channel.unary_unary(
                '/exchange.Exchange/GetBalance',
                request_serializer=exchange__pb2.GetBalanceRequest.SerializeToString,
                response_deserializer=exchange__pb2.UserBalanceResponse.FromString,
                _registered_method=True)
        self.MintSynthetic = channel.unary_unary(
                '/exchange.Exchange/MintSynthetic',
                request_serializer=exchange__pb2.MintSyntheticRequest.SerializeToString,
                response_deserializer=exchange__pb2.MintSyntheticResponse.FromString,
                _registered_method=True)
        self.BurnSynthetic = channel.unary_unary(
                '/exchange.Exchange/BurnSynthetic',
                request_serializer=exchange__pb2.BurnSyntheticRequest.SerializeToString,
                response_deserializer=exchange__pb2.BurnSyntheticResponse.FromString,
                _registered_method=True)
        self.GetSyntheticAssets = channel.unary_unary(
                '/exchange.Exchange/GetSyntheticAssets',
                request_serializer=exchange__pb2.GetSyntheticAssetsRequest.SerializeToString,
                response_deserializer=exchange__pb2.SyntheticAssetsResponse.FromString,
                _registered_method=True)
        self.GetCollateralPosition = channel.unary_unary(
                '/exchange.Exchange/GetCollateralPosition',
                request_serializer=exchange__pb2.GetCollateralPositionRequest.SerializeToString,
                response_deserializer=exchange__pb2.CollateralPositionResponse.FromString,
                _registered_method=True)
        self.GetOraclePrices = channel.unary_unary(
                '/exchange.Exchange/GetOraclePrices',
                request_serializer=exchange__pb2.GetOraclePricesRequest.SerializeToString,
                response_deserializer=exchange__pb2.OraclePricesResponse.FromString,
                _registered_method=True)
        self.GetEngineStats = channel.unary_unary(
                '/exchange.Exchange/GetEngineStats',
                request_serializer=exchange__pb2.GetEngineStatsRequest.SerializeToString,
                response_deserializer=exchange__pb2.EngineStatsResponse.FromString,
                _registered_method=True)
        self.HealthCheck = channel.unary_unary(
                '/exchange.Exchange/HealthCheck',
                request_serializer=exchange__pb2.HealthCheckRequest.SerializeToString,
                response_deserializer=exchange__pb2.HealthCheckResponse.FromString,
                _registered_method=True)


class ExchangeServicer(object):
    """─── Exchange Service ─────────────────────────────────────────────────
    gRPC bridge between Python blockchain node and Rust exchange engine.
    Handles order matching, synthetic assets, oracle pricing, collateral.

    """

    def PlaceOrder(self, request, context):
        """── Order Management ─────────────────────────────────────────────
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CancelOrder(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetOrderBook(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetUserOrders(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetMarkets(self, request, context):
        """── Market Data ──────────────────────────────────────────────────
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetRecentTrades(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetMarketSummary(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Deposit(self, request, context):
        """── Balance Management ───────────────────────────────────────────
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Withdraw(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetBalance(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def MintSynthetic(self, request, context):
        """── Synthetic Assets ─────────────────────────────────────────────
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BurnSynthetic(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSyntheticAssets(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCollateralPosition(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetOraclePrices(self, request, context):
        """── Oracle ───────────────────────────────────────────────────────
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetEngineStats(self, request, context):
        """── Engine Stats ─────────────────────────────────────────────────
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HealthCheck(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ExchangeServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'PlaceOrder': grpc.unary_unary_rpc_method_handler(
                    servicer.PlaceOrder,
                    request_deserializer=exchange__pb2.PlaceOrderRequest.FromString,
                    response_serializer=exchange__pb2.PlaceOrderResponse.SerializeToString,
            ),
            'CancelOrder': grpc.unary_unary_rpc_method_handler(
                    servicer.CancelOrder,
                    request_deserializer=exchange__pb2.CancelOrderRequest.FromString,
                    response_serializer=exchange__pb2.CancelOrderResponse.SerializeToString,
            ),
            'GetOrderBook': grpc.unary_unary_rpc_method_handler(
                    servicer.GetOrderBook,
                    request_deserializer=exchange__pb2.GetOrderBookRequest.FromString,
                    response_serializer=exchange__pb2.OrderBookResponse.SerializeToString,
            ),
            'GetUserOrders': grpc.unary_unary_rpc_method_handler(
                    servicer.GetUserOrders,
                    request_deserializer=exchange__pb2.GetUserOrdersRequest.FromString,
                    response_serializer=exchange__pb2.UserOrdersResponse.SerializeToString,
            ),
            'GetMarkets': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMarkets,
                    request_deserializer=exchange__pb2.GetMarketsRequest.FromString,
                    response_serializer=exchange__pb2.MarketsResponse.SerializeToString,
            ),
            'GetRecentTrades': grpc.unary_unary_rpc_method_handler(
                    servicer.GetRecentTrades,
                    request_deserializer=exchange__pb2.GetRecentTradesRequest.FromString,
                    response_serializer=exchange__pb2.RecentTradesResponse.SerializeToString,
            ),
            'GetMarketSummary': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMarketSummary,
                    request_deserializer=exchange__pb2.GetMarketSummaryRequest.FromString,
                    response_serializer=exchange__pb2.MarketSummaryResponse.SerializeToString,
            ),
            'Deposit': grpc.unary_unary_rpc_method_handler(
                    servicer.Deposit,
                    request_deserializer=exchange__pb2.DepositRequest.FromString,
                    response_serializer=exchange__pb2.BalanceResponse.SerializeToString,
            ),
            'Withdraw': grpc.unary_unary_rpc_method_handler(
                    servicer.Withdraw,
                    request_deserializer=exchange__pb2.WithdrawRequest.FromString,
                    response_serializer=exchange__pb2.BalanceResponse.SerializeToString,
            ),
            'GetBalance': grpc.unary_unary_rpc_method_handler(
                    servicer.GetBalance,
                    request_deserializer=exchange__pb2.GetBalanceRequest.FromString,
                    response_serializer=exchange__pb2.UserBalanceResponse.SerializeToString,
            ),
            'MintSynthetic': grpc.unary_unary_rpc_method_handler(
                    servicer.MintSynthetic,
                    request_deserializer=exchange__pb2.MintSyntheticRequest.FromString,
                    response_serializer=exchange__pb2.MintSyntheticResponse.SerializeToString,
            ),
            'BurnSynthetic': grpc.unary_unary_rpc_method_handler(
                    servicer.BurnSynthetic,
                    request_deserializer=exchange__pb2.BurnSyntheticRequest.FromString,
                    response_serializer=exchange__pb2.BurnSyntheticResponse.SerializeToString,
            ),
            'GetSyntheticAssets': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSyntheticAssets,
                    request_deserializer=exchange__pb2.GetSyntheticAssetsRequest.FromString,
                    response_serializer=exchange__pb2.SyntheticAssetsResponse.SerializeToString,
            ),
            'GetCollateralPosition': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCollateralPosition,
                    request_deserializer=exchange__pb2.GetCollateralPositionRequest.FromString,
                    response_serializer=exchange__pb2.CollateralPositionResponse.SerializeToString,
            ),
            'GetOraclePrices': grpc.unary_unary_rpc_method_handler(
                    servicer.GetOraclePrices,
                    request_deserializer=exchange__pb2.GetOraclePricesRequest.FromString,
                    response_serializer=exchange__pb2.OraclePricesResponse.SerializeToString,
            ),
            'GetEngineStats': grpc.unary_unary_rpc_method_handler(
                    servicer.GetEngineStats,
                    request_deserializer=exchange__pb2.GetEngineStatsRequest.FromString,
                    response_serializer=exchange__pb2.EngineStatsResponse.SerializeToString,
            ),
            'HealthCheck': grpc.unary_unary_rpc_method_handler(
                    servicer.HealthCheck,
                    request_deserializer=exchange__pb2.HealthCheckRequest.FromString,
                    response_serializer=exchange__pb2.HealthCheckResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'exchange.Exchange', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('exchange.Exchange', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Exchange(object):
    """─── Exchange Service ─────────────────────────────────────────────────
    gRPC bridge between Python blockchain node and Rust exchange engine.
    Handles order matching, synthetic assets, oracle pricing, collateral.

    """

    @staticmethod
    def PlaceOrder(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/exchange.Exchange/PlaceOrder',
            exchange__pb2.PlaceOrderRequest.SerializeToString,
            exchange__pb2.PlaceOrderResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CancelOrder(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/exchange.Exchange/CancelOrder',
            exchange__pb2.CancelOrderRequest.SerializeToString,
            exchange__pb2.CancelOrderResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetOrderBook(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/exchange.Exchange/GetOrderBook',
            exchange__pb2.GetOrderBookRequest.SerializeToString,
            exchange__pb2.OrderBookResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetUserOrders(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/exchange.Exchange/GetUserOrders',
            exchange__pb2.GetUserOrdersRequest.SerializeToString,
            exchange__pb2.UserOrdersResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetMarkets(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/exchange.Exchange/GetMarkets',
            exchange__pb2.GetMarketsRequest.SerializeToString,
            exchange__pb2.MarketsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetRecentTrades(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/exchange.Exchange/GetRecentTrades',
            exchange__pb2.GetRecentTradesRequest.SerializeToString,
            exchange__pb2.RecentTradesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetMarketSummary(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/exchange.Exchange/GetMarketSummary',
            exchange__pb2.GetMarketSummaryRequest.SerializeToString,
            exchange__pb2.MarketSummaryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Deposit(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/exchange.Exchange/Deposit',
            exchange__pb2.DepositRequest.SerializeToString,
            exchange__pb2.BalanceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Withdraw(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/exchange.Exchange/Withdraw',
            exchange__pb2.WithdrawRequest.SerializeToString,
            exchange__pb2.BalanceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetBalance(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/exchange.Exchange/GetBalance',
            exchange__pb2.GetBalanceRequest.SerializeToString,
            exchange__pb2.UserBalanceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def MintSynthetic(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/exchange.Exchange/MintSynthetic',
            exchange__pb2.MintSyntheticRequest.SerializeToString,
            exchange__pb2.MintSyntheticResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def BurnSynthetic(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/exchange.Exchange/BurnSynthetic',
            exchange__pb2.BurnSyntheticRequest.SerializeToString,
            exchange__pb2.BurnSyntheticResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSyntheticAssets(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/exchange.Exchange/GetSyntheticAssets',
            exchange__pb2.GetSyntheticAssetsRequest.SerializeToString,
            exchange__pb2.SyntheticAssetsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetCollateralPosition(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/exchange.Exchange/GetCollateralPosition',
            exchange__pb2.GetCollateralPositionRequest.SerializeToString,
            exchange__pb2.CollateralPositionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetOraclePrices(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/exchange.Exchange/GetOraclePrices',
            exchange__pb2.GetOraclePricesRequest.SerializeToString,
            exchange__pb2.OraclePricesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetEngineStats(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/exchange.Exchange/GetEngineStats',
            exchange__pb2.GetEngineStatsRequest.SerializeToString,
            exchange__pb2.EngineStatsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def HealthCheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/exchange.Exchange/HealthCheck',
            exchange__pb2.HealthCheckRequest.SerializeToString,
            exchange__pb2.HealthCheckResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
