global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'cockroachdb-1'
    static_configs:
      - targets: ['cockroachdb-1:8080']
  - job_name: 'cockroachdb-2'
    static_configs:
      - targets: ['cockroachdb-2:8080']
  - job_name: 'cockroachdb-3'
    static_configs:
      - targets: ['cockroachdb-3:8080']
