// SPDX-License-Identifier: MIT
pragma solidity ^0.8.24;

/// @title Poseidon2 — ZK-Friendly Hash over the Goldilocks Prime Field
/// @notice Implements Poseidon2 using the QBC parameter set, identical to the Rust
///         implementation in `substrate-node/primitives/src/poseidon2.rs`.
///         Used by ZKBridgeVerifier to verify bridge commitments generated by the
///         off-chain relay (Rust node / agent) on any supported chain.
///
/// @dev Parameter set:
///   - Field:   Goldilocks prime  p = 2^64 - 2^32 + 1 = 0xFFFFFFFF00000001
///   - State:   t = 3  (rate = 2, capacity = 1)
///   - S-box:   x^5
///   - Rounds:  RF = 8 (4 before + 4 after partial), RP = 56
///   - MDS:     circulant([2, 1, 1])  ← invertible over any field (det = 4)
///   - RC:      80 constants from SHA-256 hash chain seeded with "QBC-Poseidon2-RC-v1"
///
/// @dev Round constant generation (matches Rust):
///   state_0  = SHA-256(b"QBC-Poseidon2-RC-v1")
///   state_i  = SHA-256(state_{i-1})                   for i = 1..80
///   RC[i-1]  = u64::from_le_bytes(state_i[0..8]) % p  (replace 0 → 1)
library Poseidon2 {

    // ── Field ─────────────────────────────────────────────────────────────
    uint64  internal constant P = 0xFFFFFFFF00000001;  // Goldilocks prime

    // ── Rounds ────────────────────────────────────────────────────────────
    uint256 internal constant FULL_ROUNDS_HALF = 4;   // 4 before + 4 after
    uint256 internal constant PARTIAL_ROUNDS   = 56;

    // ── Public API ────────────────────────────────────────────────────────

    /// @notice Hash two u64 field elements (2-to-1 sponge, rate=2, capacity=1).
    /// @param  left   First input  (must be < P)
    /// @param  right  Second input (must be < P)
    /// @return 32-byte commitment — Goldilocks field element, zero-padded to 32 bytes.
    function hashTwo(uint64 left, uint64 right) internal pure returns (bytes32) {
        uint64[3] memory s;
        s[0] = left;
        s[1] = right;
        s[2] = 0;
        _permute(s);
        return bytes32(uint256(s[0]));
    }

    /// @notice Hash four u64 field elements using a 2-pass sponge.
    /// @dev    Absorb [a,b] → permute → absorb [c,d] → permute → squeeze s[0].
    function hashFour(uint64 a, uint64 b, uint64 c, uint64 d) internal pure returns (bytes32) {
        uint64[3] memory s;
        // First absorption + permutation
        s[0] = a; s[1] = b; s[2] = 0;
        _permute(s);
        // Second absorption + permutation
        s[0] = _fadd(s[0], c);
        s[1] = _fadd(s[1], d);
        _permute(s);
        return bytes32(uint256(s[0]));
    }

    /// @notice Compute a Poseidon2 Merkle leaf commitment from a 32-byte value.
    /// @dev    Splits the bytes32 into two 128-bit halves, then reduces each half
    ///         into Goldilocks by taking the low 64 bits of the 128-bit value.
    ///         The same split is performed by the Rust relay when building proofs.
    function hashLeaf(bytes32 leaf) internal pure returns (bytes32) {
        uint256 v = uint256(leaf);
        uint64 lo = uint64(v);                   // lowest 64 bits
        uint64 hi = uint64(v >> 64);             // next 64 bits
        return hashTwo(lo % P, hi % P);
    }

    /// @notice Verify a Poseidon2 Merkle inclusion proof.
    /// @param  proof   Packed sibling data: each entry is 1-byte direction + 8-byte u64 sibling
    ///                 direction 0 = current is left child, 1 = current is right child
    /// @param  root    Expected root (bytes32, Poseidon2 output zero-padded)
    /// @param  leaf    Leaf commitment (bytes32, Poseidon2 output zero-padded)
    function verifyMerkleProof(
        bytes calldata proof,
        bytes32 root,
        bytes32 leaf
    ) internal pure returns (bool) {
        uint64 current = uint64(uint256(leaf));
        uint256 nSiblings = proof.length / 9; // 1 byte direction + 8 bytes sibling

        for (uint256 i = 0; i < nSiblings; i++) {
            uint256 off = i * 9;
            uint8  dir     = uint8(proof[off]);
            uint64 sibling = uint64(bytes8(proof[off + 1 : off + 9]));

            if (dir == 0) {
                current = uint64(uint256(hashTwo(current, sibling)));
            } else {
                current = uint64(uint256(hashTwo(sibling, current)));
            }
        }

        return bytes32(uint256(current)) == root;
    }

    // ── Permutation ───────────────────────────────────────────────────────

    /// @dev Full Poseidon2 permutation: 4 full → 56 partial → 4 full rounds.
    function _permute(uint64[3] memory s) internal pure {
        uint64[80] memory rc = _roundConstants();
        uint256 idx = 0;

        // ── Full rounds (before) ──
        for (uint256 r = 0; r < FULL_ROUNDS_HALF; r++) {
            // AddRoundConstants (full — all 3 elements)
            s[0] = _fadd(s[0], rc[idx++]);
            s[1] = _fadd(s[1], rc[idx++]);
            s[2] = _fadd(s[2], rc[idx++]);
            // S-box x^5 on all elements
            s[0] = _sbox(s[0]);
            s[1] = _sbox(s[1]);
            s[2] = _sbox(s[2]);
            // MDS multiply
            _mds(s);
        }

        // ── Partial rounds ──
        for (uint256 r = 0; r < PARTIAL_ROUNDS; r++) {
            // AddRoundConstant (partial — only element 0)
            s[0] = _fadd(s[0], rc[idx++]);
            // S-box on element 0 only
            s[0] = _sbox(s[0]);
            // MDS multiply
            _mds(s);
        }

        // ── Full rounds (after) ──
        for (uint256 r = 0; r < FULL_ROUNDS_HALF; r++) {
            s[0] = _fadd(s[0], rc[idx++]);
            s[1] = _fadd(s[1], rc[idx++]);
            s[2] = _fadd(s[2], rc[idx++]);
            s[0] = _sbox(s[0]);
            s[1] = _sbox(s[1]);
            s[2] = _sbox(s[2]);
            _mds(s);
        }
    }

    /// @dev MDS matrix multiplication: M = circulant([2, 1, 1])
    ///      Row 0: 2·s0 + s1 + s2
    ///      Row 1: s0 + 2·s1 + s2
    ///      Row 2: s0 + s1 + 2·s2
    function _mds(uint64[3] memory s) internal pure {
        uint64 s0 = s[0]; uint64 s1 = s[1]; uint64 s2 = s[2];
        s[0] = _fadd(_fadd(_fadd(s0, s0), s1), s2);  // 2·s0 + s1 + s2
        s[1] = _fadd(_fadd(s0, _fadd(s1, s1)), s2);  // s0 + 2·s1 + s2
        s[2] = _fadd(_fadd(s0, s1), _fadd(s2, s2));  // s0 + s1 + 2·s2
    }

    /// @dev S-box: x^5 mod p  (3 multiplications)
    function _sbox(uint64 x) internal pure returns (uint64) {
        uint64 x2 = _fmul(x,  x);
        uint64 x4 = _fmul(x2, x2);
        return      _fmul(x4, x);
    }

    // ── Field arithmetic (Goldilocks prime) ───────────────────────────────

    /// @dev a + b mod p.  Uses uint128 to avoid uint64 overflow.
    function _fadd(uint64 a, uint64 b) internal pure returns (uint64) {
        uint128 s = uint128(a) + uint128(b);
        if (s >= uint128(P)) s -= uint128(P);
        return uint64(s);
    }

    /// @dev a * b mod p.  Product fits in uint128, safe from overflow.
    function _fmul(uint64 a, uint64 b) internal pure returns (uint64) {
        return uint64((uint128(a) * uint128(b)) % uint128(P));
    }

    // ── Round constants ───────────────────────────────────────────────────
    // Generated via SHA-256 hash chain from seed b"QBC-Poseidon2-RC-v1":
    //   state[0]  = SHA-256(seed)
    //   state[i]  = SHA-256(state[i-1])
    //   RC[i]     = u64_le(state[i][0:8]) % P  (if 0, use 1)
    //
    // To verify: run scripts/verify_poseidon2_constants.py

    function _roundConstants() internal pure returns (uint64[80] memory rc) {
        rc[ 0] = 0xc31f1d88755f1d15;
        rc[ 1] = 0xd01a09d178861919;
        rc[ 2] = 0xeeded1e5ed80cb3e;
        rc[ 3] = 0x12ae088de715364d;
        rc[ 4] = 0x28a03a4278670669;
        rc[ 5] = 0x8b77a49c583ad0e8;
        rc[ 6] = 0x7653973dbc5465d0;
        rc[ 7] = 0xc48eb9e66f8ed76b;
        rc[ 8] = 0x1352b84fe1fe8e7f;
        rc[ 9] = 0x178a153a1e5ebe8c;
        rc[10] = 0xf1dd20f677dfc76a;
        rc[11] = 0xfb0f83c0974ac1a4;
        rc[12] = 0x84e156351b56e0b9;
        rc[13] = 0x7a75cd1e5b0107c5;
        rc[14] = 0x67d550b215add6ae;
        rc[15] = 0x48e98e48bad62d26;
        rc[16] = 0x1764f6634c87eb9c;
        rc[17] = 0x06297c8f6de607db;
        rc[18] = 0xbb39bcd2f9adb130;
        rc[19] = 0x5aa45016cd87eb21;
        rc[20] = 0xb1c9a47fa4f727a4;
        rc[21] = 0x3cba2840b800d1c0;
        rc[22] = 0xf0daa0a341ee27ab;
        rc[23] = 0x82207f2248610ca5;
        rc[24] = 0x1ea5555457142bd6;
        rc[25] = 0x80a97b1079c1d5e2;
        rc[26] = 0xc9ee5fdfc0cb744b;
        rc[27] = 0x6a9fba8a7b0f9dae;
        rc[28] = 0x1ab12898161d5bc6;
        rc[29] = 0x4ff3f7ad8336161b;
        rc[30] = 0x84bdfdd5ddadb9c2;
        rc[31] = 0x3f3aa0dac982285a;
        rc[32] = 0xedd0036d91a622ca;
        rc[33] = 0xeaf4b4b12dcfb207;
        rc[34] = 0x13e65bb0c5903163;
        rc[35] = 0x49f1ac0f6d3e133f;
        rc[36] = 0x3928815c977ab168;
        rc[37] = 0xb008c53e86aa6628;
        rc[38] = 0xd26387c3692d60ca;
        rc[39] = 0xba3a9a30cc4fab0f;
        rc[40] = 0x3a28bacd9e6cffc8;
        rc[41] = 0xde6f7b0c595da67d;
        rc[42] = 0x9d133c4bbdefaeb9;
        rc[43] = 0xff69e5c19e938160;
        rc[44] = 0x734b9480efc05a06;
        rc[45] = 0xbaebfe9d20b0bdbb;
        rc[46] = 0xdeb706e0d423b8a3;
        rc[47] = 0x5a39ab8a7fe7677c;
        rc[48] = 0x04bcd60fdba29a92;
        rc[49] = 0x1858ae04ed6c8391;
        rc[50] = 0x35cb79b601324f74;
        rc[51] = 0x59d32c75bfba9b6a;
        rc[52] = 0xc658b7b8e96db76e;
        rc[53] = 0xf4766e0d09f5c365;
        rc[54] = 0xfd12f3d6b17f846c;
        rc[55] = 0x4d098122c8b49b87;
        rc[56] = 0xa7542c9710d905db;
        rc[57] = 0x6474d0241bea543a;
        rc[58] = 0x7fd7b4d6b38bf7a4;
        rc[59] = 0x78cbf28673f04e0e;
        rc[60] = 0xe1fba67cd7019e9d;
        rc[61] = 0x9f78d6c2f910a673;
        rc[62] = 0xf3ba6515bf2bca7a;
        rc[63] = 0xb1cf61fa47515439;
        rc[64] = 0xb1e5412074ab8632;
        rc[65] = 0x0d0979f895afe48e;
        rc[66] = 0xcd586704abf8bbe3;
        rc[67] = 0x441e171c4b421e9d;
        rc[68] = 0x2680ea2560794ef2;
        rc[69] = 0x11c99521549e7143;
        rc[70] = 0x8bc167910bb1b457;
        rc[71] = 0xd8e96520c8985e3c;
        rc[72] = 0x5a940139e0c4ad76;
        rc[73] = 0x1440640a003c5c1b;
        rc[74] = 0x2494a03df146a049;
        rc[75] = 0x15410bb991559072;
        rc[76] = 0xdc8ea33f9c4665da;
        rc[77] = 0xa96e95031251ce55;
        rc[78] = 0x4ebf046f2a210f7f;
        rc[79] = 0xb139233d20d4c78b;
    }
}
