//! CRUD + queries for the `conversation_sessions`, `conversation_messages`,
//! `user_memory`, and `conversation_insights` tables.
//!
//! Provides institutional-grade persistent conversation memory for the Aether
//! Tree AGI chat system. Supports per-user sessions, cross-session context,
//! sliding context windows, and conversation insight extraction.

use chrono::{NaiveDateTime, Utc};
use serde_json::Value as JsonValue;
use sqlx::PgPool;
use tracing::{debug, info, instrument, warn};
use uuid::Uuid;

use crate::error::Result;
use crate::models::{
    ConversationInsightRow, ConversationMessageRow, ConversationSessionRow,
    UserMemoryRow,
};

/// Maximum messages to return in a context window.
const MAX_CONTEXT_WINDOW: i64 = 20;
/// Maximum summary length in characters.
const MAX_SUMMARY_LENGTH: usize = 2000;

// ─── Table Creation ──────────────────────────────────────────────────────

/// Ensure all conversation tables exist. Safe to call repeatedly.
pub async fn ensure_tables(pool: &PgPool) -> Result<()> {
    sqlx::query(
        r#"
        CREATE TABLE IF NOT EXISTS conversation_sessions (
            session_id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
            user_id VARCHAR(128) NOT NULL,
            user_address VARCHAR(128) NOT NULL DEFAULT '',
            title VARCHAR(256) NOT NULL DEFAULT '',
            created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
            last_activity TIMESTAMPTZ NOT NULL DEFAULT now(),
            expires_at TIMESTAMPTZ NOT NULL DEFAULT (now() + INTERVAL '30 days'),
            message_count INT NOT NULL DEFAULT 0,
            fees_paid_atoms BIGINT NOT NULL DEFAULT 0,
            status VARCHAR(20) NOT NULL DEFAULT 'active',
            context_summary TEXT NOT NULL DEFAULT '',
            primary_topic VARCHAR(128) NOT NULL DEFAULT '',
            topics JSONB NOT NULL DEFAULT '[]'
        )
        "#,
    )
    .execute(pool)
    .await?;

    sqlx::query(
        r#"
        CREATE TABLE IF NOT EXISTS conversation_messages (
            id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
            session_id UUID NOT NULL,
            role VARCHAR(20) NOT NULL,
            content TEXT NOT NULL,
            content_hash VARCHAR(64) NOT NULL DEFAULT '',
            created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
            reasoning_trace JSONB NOT NULL DEFAULT '[]',
            phi_at_response FLOAT NOT NULL DEFAULT 0.0,
            knowledge_nodes_referenced JSONB NOT NULL DEFAULT '[]',
            proof_of_thought_hash VARCHAR(128) NOT NULL DEFAULT '',
            quality_score FLOAT NOT NULL DEFAULT 0.0,
            intent VARCHAR(64) NOT NULL DEFAULT '',
            entities JSONB NOT NULL DEFAULT '{}'
        )
        "#,
    )
    .execute(pool)
    .await?;

    sqlx::query(
        r#"
        CREATE TABLE IF NOT EXISTS user_memory (
            id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
            user_id VARCHAR(128) NOT NULL,
            memory_key VARCHAR(128) NOT NULL,
            memory_value TEXT NOT NULL,
            created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
            updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
            source VARCHAR(64) NOT NULL DEFAULT 'chat',
            UNIQUE (user_id, memory_key)
        )
        "#,
    )
    .execute(pool)
    .await?;

    sqlx::query(
        r#"
        CREATE TABLE IF NOT EXISTS conversation_insights (
            id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
            session_id UUID NOT NULL,
            user_id VARCHAR(128) NOT NULL,
            insight_type VARCHAR(64) NOT NULL,
            content TEXT NOT NULL,
            confidence FLOAT NOT NULL DEFAULT 0.5,
            knowledge_node_id BIGINT,
            created_at TIMESTAMPTZ NOT NULL DEFAULT now()
        )
        "#,
    )
    .execute(pool)
    .await?;

    // Create indexes (idempotent with IF NOT EXISTS)
    let indexes = [
        "CREATE INDEX IF NOT EXISTS idx_conv_user ON conversation_sessions (user_id, last_activity DESC)",
        "CREATE INDEX IF NOT EXISTS idx_conv_status ON conversation_sessions (status, last_activity DESC)",
        "CREATE INDEX IF NOT EXISTS idx_msg_session ON conversation_messages (session_id, created_at ASC)",
        "CREATE INDEX IF NOT EXISTS idx_umem_user ON user_memory (user_id)",
        "CREATE INDEX IF NOT EXISTS idx_insight_user ON conversation_insights (user_id, created_at DESC)",
        "CREATE INDEX IF NOT EXISTS idx_insight_session ON conversation_insights (session_id)",
    ];
    for idx_sql in &indexes {
        if let Err(e) = sqlx::query(idx_sql).execute(pool).await {
            debug!("Index creation note: {e}");
        }
    }

    info!("Conversation tables verified");
    Ok(())
}

// ─── Session Repository ─────────────────────────────────────────────────

/// Repository for `conversation_sessions`.
pub struct ConversationSessionRepo;

impl ConversationSessionRepo {
    /// Create a new session. Returns the session row.
    #[instrument(skip(pool), fields(user_id = %user_id))]
    pub async fn create(
        pool: &PgPool,
        user_id: &str,
        user_address: &str,
    ) -> Result<ConversationSessionRow> {
        let session_id = Uuid::new_v4();
        let row = sqlx::query_as::<_, ConversationSessionRow>(
            r#"
            INSERT INTO conversation_sessions (session_id, user_id, user_address)
            VALUES ($1, $2, $3)
            RETURNING *
            "#,
        )
        .bind(session_id)
        .bind(user_id)
        .bind(user_address)
        .fetch_one(pool)
        .await?;
        debug!("Created session {}", session_id);
        Ok(row)
    }

    /// Get a session by ID.
    #[instrument(skip(pool))]
    pub async fn get_by_id(
        pool: &PgPool,
        session_id: Uuid,
    ) -> Result<Option<ConversationSessionRow>> {
        let row = sqlx::query_as::<_, ConversationSessionRow>(
            "SELECT * FROM conversation_sessions WHERE session_id = $1",
        )
        .bind(session_id)
        .fetch_optional(pool)
        .await?;
        Ok(row)
    }

    /// List sessions for a user, ordered by most recent activity.
    #[instrument(skip(pool), fields(user_id = %user_id))]
    pub async fn list_by_user(
        pool: &PgPool,
        user_id: &str,
        status: &str,
        limit: i64,
    ) -> Result<Vec<ConversationSessionRow>> {
        let rows = sqlx::query_as::<_, ConversationSessionRow>(
            r#"
            SELECT * FROM conversation_sessions
            WHERE user_id = $1 AND status = $2
            ORDER BY last_activity DESC
            LIMIT $3
            "#,
        )
        .bind(user_id)
        .bind(status)
        .bind(limit)
        .fetch_all(pool)
        .await?;
        Ok(rows)
    }

    /// Update session metadata (last_activity is always updated).
    #[instrument(skip(pool))]
    pub async fn update(
        pool: &PgPool,
        session_id: Uuid,
        title: Option<&str>,
        primary_topic: Option<&str>,
        context_summary: Option<&str>,
        topics: Option<&JsonValue>,
    ) -> Result<()> {
        // Build dynamic update
        let mut sets = vec!["last_activity = now()".to_string()];
        let mut idx = 2usize; // $1 is session_id

        if title.is_some() {
            sets.push(format!("title = ${idx}"));
            idx += 1;
        }
        if primary_topic.is_some() {
            sets.push(format!("primary_topic = ${idx}"));
            idx += 1;
        }
        if context_summary.is_some() {
            sets.push(format!("context_summary = ${idx}"));
            idx += 1;
        }
        if topics.is_some() {
            sets.push(format!("topics = ${idx}"));
        }

        let sql = format!(
            "UPDATE conversation_sessions SET {} WHERE session_id = $1",
            sets.join(", ")
        );

        let mut query = sqlx::query(&sql).bind(session_id);
        if let Some(t) = title {
            query = query.bind(t);
        }
        if let Some(pt) = primary_topic {
            query = query.bind(pt);
        }
        if let Some(cs) = context_summary {
            let truncated = if cs.len() > MAX_SUMMARY_LENGTH {
                &cs[..MAX_SUMMARY_LENGTH]
            } else {
                cs
            };
            query = query.bind(truncated);
        }
        if let Some(tp) = topics {
            query = query.bind(tp);
        }

        query.execute(pool).await?;
        Ok(())
    }

    /// Archive a session (soft delete).
    #[instrument(skip(pool))]
    pub async fn archive(pool: &PgPool, session_id: Uuid) -> Result<()> {
        sqlx::query(
            "UPDATE conversation_sessions SET status = 'archived' WHERE session_id = $1",
        )
        .bind(session_id)
        .execute(pool)
        .await?;
        Ok(())
    }

    /// Expire old sessions. Returns count of sessions expired.
    #[instrument(skip(pool))]
    pub async fn expire_old(pool: &PgPool) -> Result<u64> {
        let result = sqlx::query(
            "UPDATE conversation_sessions SET status = 'expired' WHERE status = 'active' AND expires_at < now()",
        )
        .execute(pool)
        .await?;
        let count = result.rows_affected();
        if count > 0 {
            info!("Expired {count} old conversation sessions");
        }
        Ok(count)
    }

    /// Count total sessions.
    #[instrument(skip(pool))]
    pub async fn count(pool: &PgPool) -> Result<i64> {
        let row = sqlx::query_scalar::<_, i64>(
            "SELECT COUNT(*) FROM conversation_sessions",
        )
        .fetch_one(pool)
        .await?;
        Ok(row)
    }

    /// Count active sessions.
    #[instrument(skip(pool))]
    pub async fn count_active(pool: &PgPool) -> Result<i64> {
        let row = sqlx::query_scalar::<_, i64>(
            "SELECT COUNT(*) FROM conversation_sessions WHERE status = 'active'",
        )
        .fetch_one(pool)
        .await?;
        Ok(row)
    }

    /// Count unique users.
    #[instrument(skip(pool))]
    pub async fn count_unique_users(pool: &PgPool) -> Result<i64> {
        let row = sqlx::query_scalar::<_, i64>(
            "SELECT COUNT(DISTINCT user_id) FROM conversation_sessions",
        )
        .fetch_one(pool)
        .await?;
        Ok(row)
    }
}

// ─── Message Repository ─────────────────────────────────────────────────

/// Repository for `conversation_messages`.
pub struct ConversationMessageRepo;

impl ConversationMessageRepo {
    /// Insert a message and return its auto-generated ID.
    #[instrument(skip(pool, row), fields(session_id = %row.session_id, role = %row.role))]
    pub async fn insert(pool: &PgPool, row: &ConversationMessageRow) -> Result<i64> {
        let id = sqlx::query_scalar::<_, i64>(
            r#"
            INSERT INTO conversation_messages
                (session_id, role, content, content_hash, created_at,
                 reasoning_trace, phi_at_response, knowledge_nodes_referenced,
                 proof_of_thought_hash, quality_score, intent, entities)
            VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12)
            RETURNING id
            "#,
        )
        .bind(row.session_id)
        .bind(&row.role)
        .bind(&row.content)
        .bind(&row.content_hash)
        .bind(row.created_at)
        .bind(&row.reasoning_trace)
        .bind(row.phi_at_response)
        .bind(&row.knowledge_nodes_referenced)
        .bind(&row.proof_of_thought_hash)
        .bind(row.quality_score)
        .bind(&row.intent)
        .bind(&row.entities)
        .fetch_one(pool)
        .await?;

        // Increment session message count
        sqlx::query(
            "UPDATE conversation_sessions SET message_count = message_count + 1, last_activity = now() WHERE session_id = $1",
        )
        .bind(row.session_id)
        .execute(pool)
        .await?;

        Ok(id)
    }

    /// Get messages for a session in chronological order.
    #[instrument(skip(pool))]
    pub async fn list_by_session(
        pool: &PgPool,
        session_id: Uuid,
        limit: i64,
        offset: i64,
    ) -> Result<Vec<ConversationMessageRow>> {
        let rows = sqlx::query_as::<_, ConversationMessageRow>(
            r#"
            SELECT * FROM conversation_messages
            WHERE session_id = $1
            ORDER BY id ASC
            LIMIT $2 OFFSET $3
            "#,
        )
        .bind(session_id)
        .bind(limit)
        .bind(offset)
        .fetch_all(pool)
        .await?;
        Ok(rows)
    }

    /// Get the most recent N messages for a session (for context window).
    #[instrument(skip(pool))]
    pub async fn recent(
        pool: &PgPool,
        session_id: Uuid,
        count: i64,
    ) -> Result<Vec<ConversationMessageRow>> {
        // Fetch in descending order then reverse for chronological
        let mut rows = sqlx::query_as::<_, ConversationMessageRow>(
            r#"
            SELECT * FROM conversation_messages
            WHERE session_id = $1
            ORDER BY id DESC
            LIMIT $2
            "#,
        )
        .bind(session_id)
        .bind(count)
        .fetch_all(pool)
        .await?;
        rows.reverse();
        Ok(rows)
    }

    /// Count total messages across all sessions.
    #[instrument(skip(pool))]
    pub async fn count_total(pool: &PgPool) -> Result<i64> {
        let row = sqlx::query_scalar::<_, i64>(
            "SELECT COUNT(*) FROM conversation_messages",
        )
        .fetch_one(pool)
        .await?;
        Ok(row)
    }

    /// Count total messages for a specific user across all sessions.
    #[instrument(skip(pool))]
    pub async fn count_by_user(pool: &PgPool, user_id: &str) -> Result<i64> {
        let row = sqlx::query_scalar::<_, i64>(
            r#"
            SELECT COALESCE(SUM(message_count), 0)
            FROM conversation_sessions
            WHERE user_id = $1
            "#,
        )
        .bind(user_id)
        .fetch_one(pool)
        .await?;
        Ok(row)
    }
}

// ─── User Memory Repository ────────────────────────────────────────────

/// Repository for `user_memory`.
pub struct UserMemoryRepo;

impl UserMemoryRepo {
    /// Upsert a user memory (insert or update on conflict).
    #[instrument(skip(pool), fields(user_id = %user_id, key = %key))]
    pub async fn remember(
        pool: &PgPool,
        user_id: &str,
        key: &str,
        value: &str,
        source: &str,
    ) -> Result<()> {
        sqlx::query(
            r#"
            INSERT INTO user_memory (user_id, memory_key, memory_value, source, updated_at)
            VALUES ($1, $2, $3, $4, now())
            ON CONFLICT (user_id, memory_key)
            DO UPDATE SET memory_value = $3, updated_at = now(), source = $4
            "#,
        )
        .bind(user_id)
        .bind(key)
        .bind(value)
        .bind(source)
        .execute(pool)
        .await?;
        Ok(())
    }

    /// Recall a specific memory.
    #[instrument(skip(pool))]
    pub async fn recall(
        pool: &PgPool,
        user_id: &str,
        key: &str,
    ) -> Result<Option<String>> {
        let row = sqlx::query_scalar::<_, String>(
            "SELECT memory_value FROM user_memory WHERE user_id = $1 AND memory_key = $2",
        )
        .bind(user_id)
        .bind(key)
        .fetch_optional(pool)
        .await?;
        Ok(row)
    }

    /// Get all memories for a user.
    #[instrument(skip(pool), fields(user_id = %user_id))]
    pub async fn get_all(pool: &PgPool, user_id: &str) -> Result<Vec<UserMemoryRow>> {
        let rows = sqlx::query_as::<_, UserMemoryRow>(
            "SELECT * FROM user_memory WHERE user_id = $1 ORDER BY updated_at DESC",
        )
        .bind(user_id)
        .fetch_all(pool)
        .await?;
        Ok(rows)
    }

    /// Delete a specific memory.
    #[instrument(skip(pool))]
    pub async fn forget(pool: &PgPool, user_id: &str, key: &str) -> Result<()> {
        sqlx::query("DELETE FROM user_memory WHERE user_id = $1 AND memory_key = $2")
            .bind(user_id)
            .bind(key)
            .execute(pool)
            .await?;
        Ok(())
    }

    /// Delete all memories for a user.
    #[instrument(skip(pool))]
    pub async fn forget_all(pool: &PgPool, user_id: &str) -> Result<()> {
        sqlx::query("DELETE FROM user_memory WHERE user_id = $1")
            .bind(user_id)
            .execute(pool)
            .await?;
        Ok(())
    }

    /// Count total memories.
    #[instrument(skip(pool))]
    pub async fn count(pool: &PgPool) -> Result<i64> {
        let row = sqlx::query_scalar::<_, i64>("SELECT COUNT(*) FROM user_memory")
            .fetch_one(pool)
            .await?;
        Ok(row)
    }
}

// ─── Insight Repository ─────────────────────────────────────────────────

/// Repository for `conversation_insights`.
pub struct ConversationInsightRepo;

impl ConversationInsightRepo {
    /// Insert a conversation insight.
    #[instrument(skip(pool, row))]
    pub async fn insert(pool: &PgPool, row: &ConversationInsightRow) -> Result<i64> {
        let id = sqlx::query_scalar::<_, i64>(
            r#"
            INSERT INTO conversation_insights
                (session_id, user_id, insight_type, content, confidence, knowledge_node_id)
            VALUES ($1, $2, $3, $4, $5, $6)
            RETURNING id
            "#,
        )
        .bind(row.session_id)
        .bind(&row.user_id)
        .bind(&row.insight_type)
        .bind(&row.content)
        .bind(row.confidence)
        .bind(row.knowledge_node_id)
        .fetch_one(pool)
        .await?;
        Ok(id)
    }

    /// Get recent insights for a user.
    #[instrument(skip(pool))]
    pub async fn list_by_user(
        pool: &PgPool,
        user_id: &str,
        limit: i64,
    ) -> Result<Vec<ConversationInsightRow>> {
        let rows = sqlx::query_as::<_, ConversationInsightRow>(
            r#"
            SELECT * FROM conversation_insights
            WHERE user_id = $1
            ORDER BY created_at DESC
            LIMIT $2
            "#,
        )
        .bind(user_id)
        .bind(limit)
        .fetch_all(pool)
        .await?;
        Ok(rows)
    }

    /// Count total insights.
    #[instrument(skip(pool))]
    pub async fn count(pool: &PgPool) -> Result<i64> {
        let row = sqlx::query_scalar::<_, i64>(
            "SELECT COUNT(*) FROM conversation_insights",
        )
        .fetch_one(pool)
        .await?;
        Ok(row)
    }
}
