"""Expanded topic list for knowledge seeder — 3000+ topics across 20 domains."""
from typing import Dict, List

TOPICS_BY_DOMAIN: Dict[str, List[str]] = {
    "quantum_physics": [
        "Quantum mechanics",
        "Wave-particle duality",
        "Heisenberg uncertainty principle",
        "Schrodinger equation",
        "Quantum superposition",
        "Quantum entanglement",
        "Quantum decoherence",
        "Quantum tunneling",
        "Quantum harmonic oscillator",
        "Hydrogen atom quantum model",
        "Spin (physics)",
        "Pauli exclusion principle",
        "Dirac equation",
        "Klein-Gordon equation",
        "Quantum field theory",
        "Quantum electrodynamics",
        "Quantum chromodynamics",
        "Renormalization",
        "Feynman diagrams",
        "Path integral formulation",
        "Variational quantum eigensolver",
        "Quantum approximate optimization algorithm",
        "Grover's algorithm",
        "Shor's algorithm",
        "Quantum error correction",
        "Surface code (quantum computing)",
        "Topological quantum computing",
        "Majorana fermion",
        "Anyons",
        "Quantum teleportation",
        "Bell's theorem",
        "CHSH inequality",
        "EPR paradox",
        "Quantum nonlocality",
        "Density matrix",
        "Von Neumann entropy",
        "Quantum mutual information",
        "Quantum discord",
        "Quantum state tomography",
        "Quantum process tomography",
        "No-cloning theorem",
        "Quantum Zeno effect",
        "Aharonov-Bohm effect",
        "Casimir effect",
        "Lamb shift",
        "Quantum vacuum",
        "Zero-point energy",
        "Squeezed states of light",
        "Coherent states",
        "Fock states",
        "Quantum optics",
        "Hong-Ou-Mandel effect",
        "Quantum key distribution",
        "BB84 protocol",
        "Quantum random number generation",
        "Qubit",
        "Bloch sphere",
        "Quantum gate",
        "Hadamard gate",
        "CNOT gate",
        "Toffoli gate",
        "Quantum circuit model",
        "Measurement-based quantum computation",
        "Adiabatic quantum computation",
        "Quantum annealing",
        "Quantum supremacy",
        "Noisy intermediate-scale quantum era",
        "Quantum volume",
        "Superconducting qubit",
        "Trapped ion quantum computing",
        "Photonic quantum computing",
        "Neutral atom quantum computing",
        "Nitrogen-vacancy center",
        "Quantum dot",
        "Josephson junction",
        "Transmon qubit",
        "Quantum spin liquid",
        "Fractional quantum Hall effect",
        "Integer quantum Hall effect",
        "Bose-Einstein condensate",
        "Fermi gas",
        "Cooper pairs",
        "BCS theory",
        "Superfluidity",
        "Quantum phase transition",
        "Quantum critical point",
        "Many-body localization",
        "Tensor network states",
        "Matrix product states",
        "Density functional theory",
        "Hartree-Fock method",
        "Configuration interaction",
        "Coupled cluster theory",
        "Second quantization",
        "Creation and annihilation operators",
        "Fock space",
        "Wick's theorem",
        "LSZ reduction formula",
        "S-matrix",
        "Optical theorem",
        "Crossing symmetry",
        "Ward-Takahashi identity",
        "Anomaly (physics)",
        "Chiral anomaly",
        "Instantons",
        "Solitons in quantum field theory",
        "Kondo effect",
        "Anderson localization",
        "Quantum Monte Carlo method",
        "Variational Monte Carlo",
        "Diffusion Monte Carlo",
        "Quantum walk",
        "Boson sampling",
        "Quantum complexity theory",
        "BQP complexity class",
        "Quantum interactive proofs",
        "Quantum communication complexity",
        "Quantum repeater",
        "Quantum memory",
        "Quantum network",
        "Quantum internet",
        "Decoherence-free subspace",
        "Dynamical decoupling",
        "Quantum fault tolerance",
        "Stabilizer codes",
        "Steane code",
        "Color code (quantum computing)",
        "Bacon-Shor code",
        "Magic state distillation",
        "Clifford gates",
        "Gottesman-Knill theorem",
        "Solovay-Kitaev theorem",
        "Quantum simulation",
        "Digital quantum simulation",
        "Analog quantum simulation",
        "Hamiltonian simulation",
        "Trotterization",
        "Quantum phase estimation",
        "Quantum amplitude estimation",
        "Quantum machine learning",
        "Variational quantum classifier",
        "Quantum kernel methods",
        "Quantum convolutional neural network",
        "Barren plateau (quantum computing)",
        "Parameterized quantum circuit",
        "Quantum optimal control",
        "GRAPE algorithm",
        "Lindblad master equation",
        "Open quantum systems",
        "Wigner function",
        "Husimi Q representation",
        "Glauber-Sudarshan P representation",
        "Quantum Fisher information",
        "Quantum metrology",
        "Quantum sensing",
        "Quantum radar",
        "Quantum illumination",
        "Quantum thermodynamics",
        "Fluctuation theorem",
        "Jarzynski equality",
        "Crooks fluctuation theorem",
        "Quantum heat engine",
        "Quantum refrigerator",
        "Quantum battery",
        "Entanglement witness",
        "Entanglement distillation",
        "Entanglement swapping",
        "GHZ state",
        "W state",
        "Cluster state",
        "Graph state (quantum computing)",
        "Quantum contextuality",
        "Kochen-Specker theorem",
        "Leggett-Garg inequality",
        "Weak measurement",
        "Post-selection (quantum mechanics)",
        "Quantum steering",
        "Einstein-Podolsky-Rosen steering",
        "Quantum coherence (resource theory)",
        "Resource theory of entanglement",
        "Quantum channel capacity",
        "Quantum dense coding",
        "Superdense coding",
        "Quantum computing hardware comparison",
        "Quantum error mitigation",
        "Zero-noise extrapolation",
        "Probabilistic error cancellation",
        "Quantum approximate counting",
        "HHL algorithm",
        "Quantum principal component analysis",
        "Quantum support vector machine",
        "Quantum Boltzmann machine",
        "Quantum reservoir computing",
        "Quantum generative adversarial network",
        "Topological order",
        "Topological entanglement entropy",
        "Symmetry-protected topological phase",
    ],
    "ai_machine_learning": [
        "Artificial neural network",
        "Perceptron",
        "Multilayer perceptron",
        "Backpropagation",
        "Gradient descent",
        "Stochastic gradient descent",
        "Adam optimizer",
        "Learning rate scheduling",
        "Batch normalization",
        "Layer normalization",
        "Dropout (neural networks)",
        "Residual neural network",
        "Convolutional neural network",
        "Recurrent neural network",
        "Long short-term memory",
        "Gated recurrent unit",
        "Transformer (machine learning model)",
        "Attention mechanism",
        "Multi-head attention",
        "Self-attention",
        "BERT (language model)",
        "GPT (language model)",
        "T5 (language model)",
        "Large language model",
        "Prompt engineering",
        "In-context learning",
        "Chain-of-thought prompting",
        "Retrieval-augmented generation",
        "Fine-tuning (machine learning)",
        "Transfer learning",
        "Domain adaptation",
        "Few-shot learning",
        "Zero-shot learning",
        "Meta-learning (computer science)",
        "Model-agnostic meta-learning",
        "Reinforcement learning",
        "Q-learning",
        "Deep Q-network",
        "Policy gradient methods",
        "REINFORCE algorithm",
        "Proximal policy optimization",
        "Actor-critic methods",
        "Advantage actor-critic",
        "Soft actor-critic",
        "Multi-agent reinforcement learning",
        "Inverse reinforcement learning",
        "Reward shaping",
        "Curiosity-driven exploration",
        "Monte Carlo tree search",
        "AlphaGo",
        "AlphaFold",
        "Diffusion model (machine learning)",
        "Denoising diffusion probabilistic model",
        "Score matching",
        "Latent diffusion model",
        "Generative adversarial network",
        "Wasserstein GAN",
        "StyleGAN",
        "Variational autoencoder",
        "Autoencoder",
        "Sparse autoencoder",
        "Contrastive learning",
        "SimCLR",
        "CLIP (model)",
        "Vision transformer",
        "Image segmentation",
        "Object detection",
        "YOLO (object detection)",
        "Faster R-CNN",
        "Feature pyramid network",
        "Semantic segmentation",
        "Instance segmentation",
        "Panoptic segmentation",
        "Optical flow estimation",
        "Depth estimation",
        "3D reconstruction from images",
        "Neural radiance field",
        "Gaussian splatting",
        "Point cloud processing",
        "Graph neural network",
        "Graph attention network",
        "Message passing neural network",
        "Graph convolutional network",
        "Spectral graph theory in ML",
        "Equivariant neural network",
        "Geometric deep learning",
        "Natural language processing",
        "Word embedding",
        "Word2Vec",
        "GloVe (embedding)",
        "Byte pair encoding",
        "SentencePiece tokenizer",
        "Named entity recognition",
        "Part-of-speech tagging",
        "Dependency parsing",
        "Coreference resolution",
        "Machine translation",
        "Text summarization",
        "Question answering (NLP)",
        "Sentiment analysis",
        "Topic modeling",
        "Latent Dirichlet allocation",
        "Text generation",
        "Speech recognition",
        "Text-to-speech synthesis",
        "WaveNet",
        "Whisper (speech model)",
        "Support vector machine",
        "Decision tree learning",
        "Random forest",
        "Gradient boosting",
        "XGBoost",
        "LightGBM",
        "K-nearest neighbors algorithm",
        "Naive Bayes classifier",
        "Logistic regression",
        "Linear regression",
        "Ridge regression",
        "Lasso regression",
        "Elastic net regularization",
        "Principal component analysis",
        "t-SNE",
        "UMAP (dimensionality reduction)",
        "K-means clustering",
        "DBSCAN",
        "Hierarchical clustering",
        "Gaussian mixture model",
        "Expectation-maximization algorithm",
        "Hidden Markov model",
        "Conditional random field",
        "Bayesian optimization",
        "Hyperparameter optimization",
        "Neural architecture search",
        "AutoML",
        "Ensemble learning",
        "Bagging (machine learning)",
        "Boosting (machine learning)",
        "Stacking (machine learning)",
        "Cross-validation (statistics)",
        "Bias-variance tradeoff",
        "Overfitting",
        "Regularization (mathematics)",
        "Data augmentation",
        "Curriculum learning",
        "Knowledge distillation",
        "Model pruning",
        "Quantization (neural networks)",
        "Mixed-precision training",
        "Federated learning",
        "Differential privacy in ML",
        "Fairness in machine learning",
        "Explainable artificial intelligence",
        "SHAP (machine learning)",
        "LIME (machine learning)",
        "Attention visualization",
        "Saliency map",
        "Adversarial machine learning",
        "Adversarial examples",
        "Robustness (machine learning)",
        "Certified defense",
        "AI alignment",
        "Reward hacking",
        "Specification gaming",
        "Constitutional AI",
        "Reinforcement learning from human feedback",
        "Direct preference optimization",
        "AI safety",
        "Instrumental convergence",
        "Orthogonality thesis",
        "Corrigibility (AI)",
        "Scalable oversight",
        "Mechanistic interpretability",
        "Sparse autoencoders for interpretability",
        "Activation patching",
        "Causal scrubbing",
        "Linear probing",
        "Representation engineering",
        "Emergent abilities of large language models",
        "Scaling laws (neural networks)",
        "Chinchilla scaling laws",
        "Mixture of experts",
        "Sparse mixture of experts",
        "State space model (deep learning)",
        "Mamba (deep learning architecture)",
        "Kolmogorov-Arnold network",
        "Hopfield network",
        "Boltzmann machine",
        "Restricted Boltzmann machine",
        "Echo state network",
        "Liquid neural network",
        "Capsule neural network",
        "Neural ordinary differential equation",
        "Physics-informed neural network",
        "Symbolic regression",
        "Neuro-symbolic AI",
        "Inductive logic programming",
        "Probabilistic programming",
        "Bayesian neural network",
        "Gaussian process regression",
        "Active learning (machine learning)",
        "Semi-supervised learning",
        "Self-supervised learning",
        "Multi-task learning",
        "Continual learning",
        "Catastrophic forgetting",
        "Online learning (machine learning)",
        "Imitation learning",
        "Offline reinforcement learning",
        "World model (AI)",
        "Model-based reinforcement learning",
        "Dreamer (world model)",
        "MuZero",
        "Decision transformer",
        "Hindsight experience replay",
        "Prioritized experience replay",
        "Rainbow (deep reinforcement learning)",
        "Distributional reinforcement learning",
        "Goal-conditioned reinforcement learning",
        "Hierarchical reinforcement learning",
        "Options framework (RL)",
        "Intrinsic motivation (RL)",
        "Count-based exploration",
        "Random network distillation",
        "Multi-objective optimization (ML)",
        "Neural architecture search (NAS)",
        "EfficientNet",
        "MobileNet",
        "DenseNet",
        "U-Net",
        "Transformer XL",
        "Longformer",
        "Performer (attention)",
        "Flash attention",
        "Rotary positional embedding",
        "Grouped query attention",
        "Low-rank adaptation (LoRA)",
        "Prefix tuning",
        "Adapter (fine-tuning)",
        "Instruction tuning",
        "Tool use (language models)",
        "Function calling (AI)",
        "Multimodal learning",
        "Vision-language model",
        "Audio-language model",
        "Speculative decoding",
        "KV-cache optimization",
        "Tokenizer (NLP)",
        "Beam search",
        "Nucleus sampling",
        "Temperature sampling (LLM)",
    ],
    "mathematics": [
        "Set theory",
        "Zermelo-Fraenkel set theory",
        "Axiom of choice",
        "Cantor's diagonal argument",
        "Cardinal number",
        "Ordinal number",
        "Continuum hypothesis",
        "Boolean algebra",
        "Lattice theory",
        "Group theory",
        "Abelian group",
        "Cyclic group",
        "Symmetric group",
        "Lie group",
        "Representation theory",
        "Ring theory",
        "Ideal (ring theory)",
        "Field (mathematics)",
        "Galois theory",
        "Vector space",
        "Linear algebra",
        "Eigenvalue and eigenvector",
        "Singular value decomposition",
        "Matrix decomposition",
        "Jordan normal form",
        "Tensor (mathematics)",
        "Multilinear algebra",
        "Module (mathematics)",
        "Homological algebra",
        "Category theory",
        "Functor",
        "Natural transformation",
        "Adjoint functors",
        "Monad (category theory)",
        "Topos",
        "Yoneda lemma",
        "Sheaf (mathematics)",
        "Algebraic geometry",
        "Scheme (mathematics)",
        "Variety (algebraic geometry)",
        "Commutative algebra",
        "Noetherian ring",
        "Algebraic number theory",
        "Class field theory",
        "p-adic numbers",
        "Elliptic curve",
        "Modular form",
        "Langlands program",
        "Riemann hypothesis",
        "Prime number theorem",
        "Distribution of prime numbers",
        "Analytic number theory",
        "Sieve theory",
        "Diophantine equation",
        "Fermat's Last Theorem",
        "ABC conjecture",
        "Goldbach's conjecture",
        "Twin prime conjecture",
        "Quadratic reciprocity",
        "Real analysis",
        "Measure theory",
        "Lebesgue integration",
        "Functional analysis",
        "Banach space",
        "Hilbert space",
        "Operator theory",
        "Spectral theory",
        "Distribution (mathematics)",
        "Sobolev space",
        "Complex analysis",
        "Cauchy's integral theorem",
        "Riemann mapping theorem",
        "Conformal mapping",
        "Analytic continuation",
        "Riemann surface",
        "Several complex variables",
        "Harmonic analysis",
        "Fourier analysis",
        "Fourier transform",
        "Wavelet transform",
        "Laplace transform",
        "Partial differential equations",
        "Heat equation",
        "Wave equation",
        "Navier-Stokes equations",
        "Elliptic partial differential equation",
        "Finite element method",
        "Ordinary differential equations",
        "Dynamical systems theory",
        "Bifurcation theory",
        "Lyapunov stability",
        "Ergodic theory",
        "Calculus of variations",
        "Optimal control theory",
        "Topology",
        "General topology",
        "Compactness",
        "Connectedness (topology)",
        "Algebraic topology",
        "Fundamental group",
        "Homology theory",
        "Cohomology",
        "Homotopy theory",
        "Fibration",
        "Fiber bundle",
        "Characteristic class",
        "K-theory",
        "Cobordism",
        "Manifold",
        "Differentiable manifold",
        "Riemannian geometry",
        "Curvature (mathematics)",
        "Geodesic",
        "Ricci flow",
        "Poincare conjecture",
        "Symplectic geometry",
        "Contact geometry",
        "Knot theory",
        "Braid group",
        "Low-dimensional topology",
        "Morse theory",
        "Differential forms",
        "De Rham cohomology",
        "Stokes' theorem",
        "Probability theory",
        "Central limit theorem",
        "Law of large numbers",
        "Martingale (probability theory)",
        "Markov chain",
        "Brownian motion",
        "Stochastic calculus",
        "Ito's lemma",
        "Stochastic differential equation",
        "Random matrix theory",
        "Percolation theory",
        "Bayesian statistics",
        "Frequentist inference",
        "Maximum likelihood estimation",
        "Hypothesis testing",
        "Confidence interval",
        "Regression analysis",
        "Nonparametric statistics",
        "Time series analysis",
        "Survival analysis",
        "Causal inference (statistics)",
        "Combinatorics",
        "Graph theory",
        "Ramsey theory",
        "Extremal graph theory",
        "Matroid theory",
        "Generating function",
        "Polya enumeration theorem",
        "Discrete mathematics",
        "Number theory",
        "Cryptographic hash function theory",
        "Computational complexity theory",
        "P versus NP problem",
        "NP-completeness",
        "Approximation algorithm",
        "Randomized algorithm",
        "Automata theory",
        "Formal language theory",
        "Lambda calculus",
        "Type theory",
        "Homotopy type theory",
        "Constructive mathematics",
        "Intuitionistic logic",
        "Mathematical logic",
        "First-order logic",
        "Model theory",
        "Proof theory",
        "Godel's incompleteness theorems",
        "Recursion theory",
        "Numerical analysis",
        "Numerical linear algebra",
        "Interpolation",
        "Quadrature (numerical integration)",
        "Monte Carlo method",
        "Optimization (mathematics)",
        "Convex optimization",
        "Linear programming",
        "Semidefinite programming",
        "Integer programming",
        "Constraint satisfaction problem",
        "Game theory (mathematics)",
        "Nash equilibrium",
        "Minimax theorem",
        "Cooperative game theory",
        "Fixed-point theorem",
        "Brouwer fixed-point theorem",
        "Banach fixed-point theorem",
        "Fractal geometry",
        "Hausdorff dimension",
        "Chaos theory (mathematics)",
        "Strange attractor",
        "Information geometry",
        "Tropical geometry",
        "Noncommutative geometry",
        "Algebraic K-theory",
        "Derived category",
        "Spectral sequence",
        "Etale cohomology",
        "Weil conjectures",
        "Berkovich space",
        "Perfectoid space",
        "Motivic cohomology",
        "Arakelov geometry",
        "Iwasawa theory",
        "Modular arithmetic",
        "Quadratic form",
        "Lattice (order)",
        "Boolean satisfiability problem",
        "Constraint logic programming",
        "Constructive type theory",
        "Martin-Lof type theory",
        "Univalent foundations",
        "Cubical type theory",
        "Operads",
        "Higher category theory",
        "Infinity category",
        "Kan extension",
        "Grothendieck topology",
        "Algebraic number field",
        "Dedekind domain",
        "Valuation (algebra)",
        "Henselian ring",
        "Berkovich analytification",
        "Deligne-Mumford stack",
        "Moduli space",
    ],
    "philosophy_of_mind": [
        "Philosophy of mind",
        "Consciousness",
        "Hard problem of consciousness",
        "Qualia",
        "Intentionality",
        "Mental representation",
        "Functionalism (philosophy of mind)",
        "Computational theory of mind",
        "Mind-body problem",
        "Substance dualism",
        "Property dualism",
        "Physicalism",
        "Identity theory of mind",
        "Eliminative materialism",
        "Anomalous monism",
        "Epiphenomenalism",
        "Neutral monism",
        "Panpsychism",
        "Panprotopsychism",
        "Integrated information theory",
        "Global workspace theory",
        "Higher-order theories of consciousness",
        "Attention schema theory",
        "Recurrent processing theory",
        "Predictive processing",
        "Free energy principle",
        "Embodied cognition",
        "Extended mind thesis",
        "Enactivism",
        "Phenomenology (philosophy)",
        "Husserlian phenomenology",
        "Heidegger's ontology",
        "Merleau-Ponty's philosophy of perception",
        "Phenomenal consciousness",
        "Access consciousness",
        "Neural correlates of consciousness",
        "Blindsight",
        "Change blindness",
        "Inattentional blindness",
        "Binocular rivalry",
        "Dreams and consciousness",
        "Lucid dreaming",
        "Altered states of consciousness",
        "Meditation and consciousness",
        "Psychedelic consciousness",
        "Unconscious mind",
        "Subconsciousness",
        "Chinese room argument",
        "Turing test",
        "Philosophical zombie",
        "Mary's room thought experiment",
        "What is it like to be a bat",
        "Inverted qualia",
        "Absent qualia",
        "Multiple realizability",
        "Mental causation",
        "Supervenience (philosophy of mind)",
        "Emergence (philosophy)",
        "Strong emergence",
        "Weak emergence",
        "Downward causation",
        "Folk psychology",
        "Theory of mind (philosophy)",
        "Simulation theory (philosophy of mind)",
        "Mirror neuron theory of mind reading",
        "Self-consciousness",
        "Introspection",
        "First-person perspective",
        "Subjectivity",
        "Intersubjectivity",
        "Other minds problem",
        "Personal identity (philosophy)",
        "Narrative identity",
        "Bundle theory of self",
        "No-self doctrine (Anatta)",
        "Free will",
        "Determinism",
        "Compatibilism",
        "Libertarianism (philosophy)",
        "Agent causation",
        "Mental content",
        "Narrow content",
        "Wide content",
        "Externalism (philosophy of mind)",
        "Internalism (philosophy of mind)",
        "Disjunctivism (philosophy of perception)",
        "Sense-data theory",
        "Naive realism (philosophy)",
        "Representationalism (philosophy of mind)",
        "Indirect realism",
        "Perception (philosophy)",
        "Philosophy of emotion",
        "Somatic marker hypothesis",
        "Cognitive penetration of perception",
        "Animal consciousness",
        "Machine consciousness",
        "Artificial general intelligence (philosophy)",
        "Sentience",
        "Sapience",
        "Moral status of AI",
        "Consciousness and quantum mechanics",
        "Orchestrated objective reduction",
        "Russellian monism",
        "Illusionism (consciousness)",
        "Heterophenomenology",
        "Neurophenomenology",
        "Dennett's multiple drafts model",
        "Tononi's phi theory",
        "Biological naturalism",
        "Mysterianism",
        "New mysterianism",
        "Cognitive closure (philosophy)",
        "Explanatory gap",
        "Knowledge argument",
        "Conceivability argument",
        "Zombie argument",
        "Thought experiment",
        "Spectrum inversion",
        "Swampman",
        "Brain in a vat",
    ],
    "neuroscience": [
        "Neuroscience",
        "Neuron",
        "Action potential",
        "Synapse",
        "Synaptic plasticity",
        "Long-term potentiation",
        "Long-term depression (neuroscience)",
        "Hebbian theory",
        "Spike-timing-dependent plasticity",
        "Dendrite",
        "Axon",
        "Myelin sheath",
        "Nodes of Ranvier",
        "Saltatory conduction",
        "Neurotransmitter",
        "Dopamine",
        "Serotonin",
        "Glutamate (neurotransmitter)",
        "GABA (neurotransmitter)",
        "Acetylcholine",
        "Norepinephrine",
        "Endorphins",
        "Neuropeptides",
        "Receptor (biochemistry)",
        "Ion channel",
        "Voltage-gated ion channel",
        "Ligand-gated ion channel",
        "NMDA receptor",
        "AMPA receptor",
        "G protein-coupled receptor",
        "Cerebral cortex",
        "Prefrontal cortex",
        "Motor cortex",
        "Somatosensory cortex",
        "Visual cortex",
        "Auditory cortex",
        "Broca's area",
        "Wernicke's area",
        "Hippocampus",
        "Amygdala",
        "Thalamus",
        "Hypothalamus",
        "Basal ganglia",
        "Cerebellum",
        "Brainstem",
        "Reticular formation",
        "Corpus callosum",
        "Limbic system",
        "Insular cortex",
        "Cingulate cortex",
        "Default mode network",
        "Salience network",
        "Central executive network",
        "Connectome",
        "White matter tracts",
        "Diffusion tensor imaging",
        "Functional magnetic resonance imaging",
        "Electroencephalography",
        "Magnetoencephalography",
        "Transcranial magnetic stimulation",
        "Optogenetics",
        "Calcium imaging",
        "Patch clamp technique",
        "Two-photon microscopy",
        "Brain-computer interface",
        "Neuroprosthetics",
        "Deep brain stimulation",
        "Neuroplasticity",
        "Critical period (neuroscience)",
        "Neurogenesis",
        "Adult neurogenesis",
        "Neural stem cells",
        "Glial cells",
        "Astrocyte",
        "Oligodendrocyte",
        "Microglia",
        "Blood-brain barrier",
        "Neurovascular coupling",
        "Computational neuroscience",
        "Hodgkin-Huxley model",
        "Integrate-and-fire model",
        "Neural coding",
        "Rate coding",
        "Temporal coding",
        "Population coding",
        "Sparse coding (neuroscience)",
        "Predictive coding (neuroscience)",
        "Neural oscillation",
        "Gamma oscillation",
        "Theta rhythm",
        "Alpha wave",
        "Neural synchrony",
        "Binding problem (neuroscience)",
        "Attractor network",
        "Winner-take-all network",
        "Recurrent neural network (neuroscience)",
        "Cortical column",
        "Cortical layers",
        "Canonical microcircuit",
        "Recurrent excitation",
        "Lateral inhibition",
        "Receptive field",
        "Feature detection (neuroscience)",
        "Place cell",
        "Grid cell",
        "Head direction cell",
        "Entorhinal cortex",
        "Memory consolidation",
        "Systems consolidation",
        "Synaptic consolidation",
        "Working memory (neuroscience)",
        "Episodic memory",
        "Semantic memory",
        "Procedural memory",
        "Memory reconsolidation",
        "Pattern separation (neuroscience)",
        "Pattern completion (neuroscience)",
        "Hippocampal replay",
        "Sharp-wave ripple",
        "Sleep and memory",
        "REM sleep",
        "Slow-wave sleep",
        "Circadian rhythm",
        "Suprachiasmatic nucleus",
        "Reward system",
        "Dopaminergic pathway",
        "Ventral tegmental area",
        "Nucleus accumbens",
        "Prefrontal-limbic connectivity",
        "Mirror neuron",
        "Motor planning",
        "Sensorimotor integration",
        "Proprioception",
        "Vestibular system",
        "Somatotopic organization",
        "Retinotopic organization",
        "Tonotopic organization",
        "Multisensory integration",
        "Neuroinflammation",
        "Excitotoxicity",
        "Apoptosis (neuroscience)",
        "Wallerian degeneration",
        "Traumatic brain injury",
        "Neurodegenerative disease",
        "Alzheimer's disease pathology",
        "Parkinson's disease pathology",
        "Amyotrophic lateral sclerosis",
        "Multiple sclerosis pathology",
        "Epilepsy (neuroscience)",
        "Stroke pathophysiology",
        "Pain neuroscience",
        "Nociception",
        "Neuroethology",
        "Birdsong neuroscience",
        "Olfactory system",
        "Gustatory system",
        "Retina",
        "Lateral geniculate nucleus",
        "Superior colliculus",
        "Prefrontal-striatal circuit",
        "Cortico-basal ganglia-thalamo-cortical loop",
        "Cerebellum-dependent learning",
        "Spinal cord",
        "Central pattern generator",
        "Motor unit",
        "Neuromuscular junction",
        "Autonomic nervous system",
        "Sympathetic nervous system",
        "Parasympathetic nervous system",
        "Enteric nervous system",
        "Neuroanatomy",
        "Brodmann area",
        "Cytoarchitecture",
        "Connectomics",
        "Brainbow",
        "CLARITY (neuroscience technique)",
        "Neural ensemble",
        "Population dynamics (neuroscience)",
        "Decision making (neuroscience)",
        "Neuroeconomics",
    ],
    "physics_general": [
        "Classical mechanics",
        "Newton's laws of motion",
        "Lagrangian mechanics",
        "Hamiltonian mechanics",
        "Principle of least action",
        "Noether's theorem",
        "Conservation of energy",
        "Conservation of momentum",
        "Conservation of angular momentum",
        "Rigid body dynamics",
        "Euler's equations (rigid body dynamics)",
        "Central force problem",
        "Two-body problem",
        "Three-body problem",
        "Kepler's laws of planetary motion",
        "Orbital mechanics",
        "Gravitational potential",
        "Tidal forces",
        "Continuum mechanics",
        "Fluid dynamics",
        "Navier-Stokes equations (physics)",
        "Turbulence",
        "Reynolds number",
        "Bernoulli's principle",
        "Vorticity",
        "Boundary layer",
        "Electromagnetism",
        "Maxwell's equations",
        "Coulomb's law",
        "Gauss's law",
        "Faraday's law of induction",
        "Ampere's circuital law",
        "Electromagnetic radiation",
        "Electromagnetic spectrum",
        "Polarization (waves)",
        "Interference (wave propagation)",
        "Diffraction",
        "Waveguide",
        "Antenna theory",
        "Plasma physics",
        "Magnetohydrodynamics",
        "Thermodynamics",
        "Laws of thermodynamics",
        "Entropy (thermodynamics)",
        "Free energy (thermodynamics)",
        "Phase transition",
        "Critical phenomena",
        "Carnot cycle",
        "Heat engine",
        "Statistical mechanics",
        "Boltzmann distribution",
        "Partition function (statistical mechanics)",
        "Fermi-Dirac statistics",
        "Bose-Einstein statistics",
        "Ising model",
        "Phase transition (statistical mechanics)",
        "Renormalization group",
        "Universality (physics)",
        "Mean field theory",
        "Monte Carlo methods in physics",
        "Special relativity",
        "Lorentz transformation",
        "Time dilation",
        "Length contraction",
        "Relativistic mechanics",
        "Four-vector",
        "Minkowski spacetime",
        "General relativity",
        "Einstein field equations",
        "Schwarzschild metric",
        "Kerr metric",
        "Gravitational lensing",
        "Gravitational waves",
        "LIGO",
        "Geodesic equation",
        "Christoffel symbols",
        "Riemann curvature tensor",
        "Ricci tensor",
        "Stress-energy tensor",
        "Cosmological constant",
        "De Sitter space",
        "Anti-de Sitter space",
        "Frame dragging",
        "Gravitomagnetism",
        "Standard Model (physics)",
        "Quarks",
        "Leptons",
        "Gauge boson",
        "Higgs boson",
        "Higgs mechanism",
        "Electroweak interaction",
        "Strong interaction",
        "Weak interaction",
        "Quantum gravity",
        "Loop quantum gravity",
        "String theory",
        "M-theory",
        "Superstring theory",
        "Compactification (physics)",
        "Extra dimensions",
        "Kaluza-Klein theory",
        "Supersymmetry",
        "Grand Unified Theory",
        "Proton decay",
        "Magnetic monopole",
        "CP violation",
        "Neutrino oscillation",
        "Neutrino mass",
        "Dark matter",
        "Dark energy",
        "Cosmological inflation",
        "Big Bang",
        "Cosmic microwave background",
        "Baryon acoustic oscillations",
        "Nucleosynthesis",
        "Baryogenesis",
        "Leptogenesis",
        "Cosmic string",
        "Black hole thermodynamics",
        "Hawking radiation",
        "Information paradox (black hole)",
        "Holographic principle",
        "AdS/CFT correspondence",
        "Condensed matter physics",
        "Solid-state physics",
        "Band theory",
        "Semiconductor physics",
        "Superconductivity",
        "Type-I superconductor",
        "Type-II superconductor",
        "High-temperature superconductivity",
        "Topological insulator",
        "Weyl semimetal",
        "Dirac semimetal",
        "Phonon",
        "Magnon",
        "Polaron",
        "Exciton",
        "Spintronics",
        "Magnetism",
        "Ferromagnetism",
        "Antiferromagnetism",
        "Spin glass",
        "Metamaterial",
        "Photonic crystal",
        "Nonlinear optics",
        "Nuclear physics",
        "Nuclear force",
        "Nuclear fission",
        "Nuclear fusion",
        "Radioactive decay",
        "Neutron star physics",
        "Quark-gluon plasma",
        "Parton model",
        "Deep inelastic scattering",
        "Jets (particle physics)",
        "Hadron collider",
        "Large Hadron Collider",
        "Higgs boson discovery",
        "Pentaquark",
        "Tetraquark",
        "Color confinement",
        "Asymptotic freedom",
        "Running coupling constant",
        "Beta function (physics)",
        "Anomalous magnetic moment",
        "Muon g-2 anomaly",
        "Dark photon",
        "Axion",
        "Sterile neutrino",
        "Weakly interacting massive particle",
        "Direct detection (dark matter)",
        "Graviton",
        "Planck scale",
        "Planck length",
        "Wheeler-DeWitt equation",
        "Spin foam",
        "Causal dynamical triangulation",
        "Causal sets",
        "Noncommutative spacetime",
        "Doubly special relativity",
    ],
    "cryptography": [
        "Cryptography",
        "Symmetric-key cryptography",
        "Advanced Encryption Standard",
        "Data Encryption Standard",
        "ChaCha20",
        "Salsa20",
        "Block cipher",
        "Stream cipher",
        "Block cipher mode of operation",
        "Counter mode (cryptography)",
        "Galois/Counter Mode",
        "Authenticated encryption",
        "Public-key cryptography",
        "RSA cryptosystem",
        "Diffie-Hellman key exchange",
        "Elliptic-curve cryptography",
        "Elliptic Curve Diffie-Hellman",
        "Edwards-curve Digital Signature Algorithm",
        "Digital Signature Algorithm",
        "Schnorr signature",
        "BLS signature",
        "Threshold signature scheme",
        "Multi-signature (cryptography)",
        "Ring signature",
        "Blind signature",
        "Group signature",
        "Hash function (cryptography)",
        "SHA-2",
        "SHA-3",
        "Keccak (hash function)",
        "BLAKE2",
        "BLAKE3",
        "Merkle tree",
        "Merkle-Damgard construction",
        "Sponge construction",
        "Hash-based message authentication code",
        "Key derivation function",
        "PBKDF2",
        "Argon2",
        "scrypt",
        "Zero-knowledge proof",
        "zk-SNARK",
        "zk-STARK",
        "Bulletproofs",
        "Plonk (proof system)",
        "Groth16",
        "Interactive proof system",
        "Fiat-Shamir heuristic",
        "Sigma protocol",
        "Pedersen commitment",
        "Homomorphic commitment",
        "Accumulator (cryptography)",
        "Verifiable random function",
        "Verifiable delay function",
        "Homomorphic encryption",
        "Fully homomorphic encryption",
        "Partially homomorphic encryption",
        "Lattice-based cryptography",
        "Learning with errors",
        "Ring learning with errors",
        "NTRU",
        "CRYSTALS-Kyber",
        "CRYSTALS-Dilithium",
        "SPHINCS+",
        "FALCON (signature scheme)",
        "Post-quantum cryptography",
        "Hash-based signature scheme",
        "XMSS",
        "Lamport signature",
        "Merkle signature scheme",
        "Code-based cryptography",
        "McEliece cryptosystem",
        "Multivariate cryptography",
        "Isogeny-based cryptography",
        "Secure multi-party computation",
        "Oblivious transfer",
        "Garbled circuit",
        "Secret sharing",
        "Shamir's secret sharing",
        "Threshold cryptosystem",
        "Oblivious RAM",
        "Private information retrieval",
        "Differential privacy",
        "Functional encryption",
        "Attribute-based encryption",
        "Identity-based encryption",
        "Proxy re-encryption",
        "Broadcast encryption",
        "Key encapsulation mechanism",
        "Transport Layer Security",
        "Signal protocol",
        "Double ratchet algorithm",
        "X3DH key agreement",
        "End-to-end encryption",
        "Perfect forward secrecy",
        "Random oracle model",
        "Provable security",
        "Semantic security",
        "Indistinguishability under chosen-ciphertext attack",
        "Side-channel attack",
        "Timing attack",
        "Power analysis attack",
        "Electromagnetic analysis attack",
        "Fault injection attack",
        "Cold boot attack",
        "Rowhammer attack",
        "Spectre (vulnerability)",
        "Meltdown (vulnerability)",
        "Cryptanalysis",
        "Birthday attack",
        "Meet-in-the-middle attack",
        "Padding oracle attack",
        "Length extension attack",
        "Related-key attack",
        "Chosen-ciphertext attack",
        "Chosen-plaintext attack",
        "Ciphertext-only attack",
        "Key management",
        "Public key infrastructure",
        "Certificate authority",
        "Web of trust",
        "Distributed key generation",
        "Threshold ECDSA",
        "Post-quantum TLS",
        "Hybrid key exchange",
        "Noise protocol framework",
        "Verifiable computation",
        "Succinct argument of knowledge",
        "Recursive proof composition",
        "Incrementally verifiable computation",
    ],
    "blockchain_fundamentals": [
        "Blockchain",
        "Distributed ledger technology",
        "Bitcoin",
        "Ethereum",
        "Proof of work",
        "Proof of stake",
        "Delegated proof of stake",
        "Proof of authority",
        "Proof of space",
        "Proof of history",
        "Byzantine fault tolerance",
        "Practical Byzantine fault tolerance",
        "Tendermint consensus",
        "HotStuff (consensus)",
        "Nakamoto consensus",
        "Consensus mechanism",
        "Finality (blockchain)",
        "Fork (blockchain)",
        "Longest chain rule",
        "GHOST protocol",
        "Casper (Ethereum)",
        "Gasper (Ethereum consensus)",
        "Smart contract",
        "Solidity (programming language)",
        "Ethereum Virtual Machine",
        "Gas (Ethereum)",
        "Account abstraction",
        "ERC-20 token standard",
        "ERC-721 token standard",
        "ERC-1155 token standard",
        "Decentralized application",
        "Decentralized finance",
        "Automated market maker",
        "Constant product market maker",
        "Concentrated liquidity",
        "Uniswap",
        "Liquidity pool",
        "Yield farming",
        "Liquidity mining",
        "Flash loan",
        "Lending protocol (DeFi)",
        "Stablecoin",
        "Algorithmic stablecoin",
        "Collateralized debt position",
        "Overcollateralization",
        "Decentralized exchange",
        "Order book (decentralized)",
        "Impermanent loss",
        "Slippage (trading)",
        "Maximal extractable value",
        "Front-running (blockchain)",
        "Sandwich attack",
        "Flashbots",
        "Proposer-builder separation",
        "Layer 2 (blockchain)",
        "Optimistic rollup",
        "ZK-rollup",
        "Validium",
        "Plasma (blockchain)",
        "State channels",
        "Lightning Network",
        "Cross-chain bridge",
        "Atomic swap",
        "Hash time-locked contract",
        "Wrapped token",
        "Oracle (blockchain)",
        "Chainlink",
        "TWAP oracle",
        "Verifiable random function (blockchain)",
        "Merkle Patricia trie",
        "State trie (Ethereum)",
        "Receipt trie",
        "Transaction trie",
        "Block header (blockchain)",
        "Uncle block",
        "Mempool",
        "Transaction ordering",
        "Priority fee (EIP-1559)",
        "Base fee (EIP-1559)",
        "EIP-1559",
        "Account model vs UTXO model",
        "UTXO (Unspent Transaction Output)",
        "Sharding (blockchain)",
        "Data availability",
        "Danksharding",
        "Proto-danksharding (EIP-4844)",
        "Blob transaction",
        "Verkle tree",
        "Decentralized autonomous organization",
        "Governance token",
        "On-chain governance",
        "Multisig wallet",
        "Hardware wallet",
        "Hierarchical deterministic wallet",
        "BIP-39 mnemonic",
        "Tokenomics",
        "Token vesting",
        "Token bonding curve",
        "Soulbound token",
        "Non-fungible token",
        "Decentralized identity",
        "Decentralized storage",
        "Interplanetary File System",
        "Filecoin",
        "Arweave",
        "Substrate (blockchain framework)",
        "Cosmos SDK",
        "Polkadot",
        "Avalanche (blockchain)",
        "Solana (blockchain)",
        "Move (programming language)",
        "Vyper (programming language)",
        "Cairo (programming language)",
        "Intent-based transactions",
        "Chain abstraction",
        "Restaking",
        "Liquid staking",
        "Eigenlayer",
        "Sequencer (rollup)",
        "Based rollup",
        "Sovereign rollup",
        "Modular blockchain",
        "Data availability sampling",
        "Erasure coding (blockchain)",
        "Fraud proof",
        "Validity proof",
        "Recursive rollup",
        "Appchain",
        "Shared sequencing",
    ],
    "complexity_science": [
        "Complex system",
        "Emergence",
        "Self-organization",
        "Autopoiesis",
        "Dissipative structure",
        "Edge of chaos",
        "Criticality (physics)",
        "Self-organized criticality",
        "Power law",
        "Scale-free network",
        "Small-world network",
        "Preferential attachment",
        "Barabasi-Albert model",
        "Erdos-Renyi model",
        "Watts-Strogatz model",
        "Network science",
        "Community detection (networks)",
        "Modularity (networks)",
        "Centrality measures",
        "Betweenness centrality",
        "PageRank",
        "Network robustness",
        "Percolation (network theory)",
        "Epidemic spreading on networks",
        "Cellular automaton",
        "Conway's Game of Life",
        "Rule 110",
        "Elementary cellular automaton",
        "Wolfram classification",
        "Agent-based model",
        "Multi-agent system",
        "Swarm intelligence",
        "Ant colony optimization",
        "Particle swarm optimization",
        "Boids",
        "Flocking behavior",
        "Stigmergy",
        "Chaos theory",
        "Logistic map",
        "Lorenz system",
        "Butterfly effect",
        "Lyapunov exponent",
        "Poincare recurrence theorem",
        "Fractal",
        "Mandelbrot set",
        "Julia set",
        "Self-similarity",
        "Box-counting dimension",
        "Feedback loop",
        "Positive feedback",
        "Negative feedback",
        "Cybernetics",
        "Systems thinking",
        "System dynamics",
        "Causal loop diagram",
        "Stock and flow model",
        "Resilience (complex systems)",
        "Tipping point (complex systems)",
        "Regime shift",
        "Hysteresis",
        "Path dependence",
        "Lock-in effect",
        "Phase space",
        "State space (dynamical systems)",
        "Attractor",
        "Basin of attraction",
        "Limit cycle",
        "Bifurcation diagram",
        "Period doubling",
        "Feigenbaum constants",
        "Synchronization (nonlinear dynamics)",
        "Kuramoto model",
        "Coupled oscillators",
        "Reaction-diffusion system",
        "Turing pattern",
        "Belousov-Zhabotinsky reaction",
        "Excitable medium",
        "Evolutionary dynamics",
        "Evolutionary game theory",
        "Replicator dynamics",
        "Fitness landscape",
        "Red Queen hypothesis",
        "Neutral theory of biodiversity",
        "Santa Fe Institute",
        "Artificial life",
        "Tierra (artificial life)",
        "Genetic algorithm",
        "Evolutionary computation",
        "Genetic programming",
        "Evolutionary strategy",
        "Coevolution",
        "Punctuated equilibrium",
        "NK model",
        "Boolean network",
        "Random Boolean network",
        "Kauffman's NK model",
        "Sandpile model",
        "Forest fire model",
        "Percolation theory (physics)",
        "Universality class",
        "Renormalization group (complex systems)",
        "Information cascade",
        "Herding behavior",
        "Voter model",
        "Opinion dynamics",
        "Schelling segregation model",
        "Axelrod model of culture",
        "Prisoner's dilemma on networks",
        "Cooperation evolution",
        "Tragedy of the commons (complexity)",
        "Common-pool resource",
        "Ostrom's design principles",
        "Socio-ecological system",
        "Adaptive management",
        "Panarchy",
        "Adaptive cycle",
        "Robustness-fragility tradeoff",
        "Highly optimized tolerance",
        "Catastrophe theory",
        "Cusp catastrophe",
        "Swallowtail catastrophe",
        "Structural stability",
        "Topological entropy",
        "Symbolic dynamics",
        "Cantor set",
        "Sierpinski triangle",
        "Koch snowflake",
        "Multifractal analysis",
    ],
    "information_theory": [
        "Information theory",
        "Entropy (information theory)",
        "Shannon entropy",
        "Conditional entropy",
        "Joint entropy",
        "Mutual information",
        "Pointwise mutual information",
        "Channel capacity",
        "Shannon's source coding theorem",
        "Shannon's channel coding theorem",
        "Noisy-channel coding theorem",
        "Rate-distortion theory",
        "Data compression",
        "Huffman coding",
        "Arithmetic coding",
        "Lempel-Ziv-Welch compression",
        "Kolmogorov complexity",
        "Algorithmic information theory",
        "Minimum description length",
        "Solomonoff's theory of inductive inference",
        "Error-correcting code",
        "Hamming code",
        "Reed-Solomon code",
        "Turbo code",
        "Low-density parity-check code",
        "Polar code (coding theory)",
        "Convolutional code",
        "Viterbi algorithm",
        "Trellis (coding theory)",
        "Maximum a posteriori estimation",
        "Binary symmetric channel",
        "Binary erasure channel",
        "Additive white Gaussian noise channel",
        "Fading channel",
        "MIMO (telecommunications)",
        "Capacity of wireless channels",
        "Ergodic capacity",
        "Outage capacity",
        "Network information theory",
        "Network coding",
        "Max-flow min-cut theorem",
        "Slepian-Wolf coding",
        "Wyner-Ziv coding",
        "Distributed source coding",
        "Multiple access channel",
        "Broadcast channel (information theory)",
        "Relay channel",
        "Interference channel",
        "Fisher information",
        "Cramer-Rao bound",
        "Kullback-Leibler divergence",
        "Jensen-Shannon divergence",
        "Renyi entropy",
        "Tsallis entropy",
        "Cross-entropy",
        "Entropy rate",
        "Typical set",
        "Asymptotic equipartition property",
        "Source coding theorem",
        "Kraft inequality",
        "Prefix code",
        "Universal code (data compression)",
        "Data processing inequality",
        "Sufficient statistic",
        "Fano's inequality",
        "Gibbs inequality",
        "Maximum entropy principle",
        "Maximum entropy probability distribution",
        "Jaynes's maximum entropy",
        "Entropy power inequality",
        "De Bruijn identity",
        "Quantum information theory",
        "Quantum channel",
        "Quantum error-correcting code",
        "Quantum capacity",
        "Holevo bound",
        "Quantum data compression",
        "Entanglement entropy",
        "Quantum relative entropy",
        "Quantum mutual information (formal)",
        "Quantum key distribution theory",
        "Quantum Shannon theory",
        "Classical capacity of quantum channel",
        "Entanglement-assisted capacity",
        "Information-theoretic security",
        "One-time pad",
        "Perfect secrecy",
        "Wiretap channel",
        "Physical layer security",
        "Secrecy capacity",
        "Rate-distortion function",
        "Blahut-Arimoto algorithm",
        "Information bottleneck method",
        "Predictive information",
        "Causal entropy",
        "Transfer entropy",
        "Granger causality",
        "Integrated information (mathematics)",
        "Partial information decomposition",
        "Directed information",
        "Lossless data compression",
        "Lossy data compression",
        "Lossless source coding bound",
        "Capacity-achieving code",
        "Successive cancellation decoding",
        "Belief propagation decoding",
        "Expander code",
        "Locally decodable code",
        "List decoding",
        "Fountain code",
        "Raptor code",
        "Digital watermarking",
        "Steganography",
        "Fingerprinting (information security)",
        "Multi-user information theory",
        "CEO problem (information theory)",
        "Distributed compression",
        "Information-theoretic learning",
        "Minimum entropy coupling",
        "Common information",
        "Exact common information",
        "Wyner common information",
        "Total correlation",
        "Dual total correlation",
        "O-information",
        "Synergy (information theory)",
        "Redundancy (information theory)",
        "Partial information decomposition (formal)",
        "Information geometry (formal)",
        "Natural gradient",
    ],
    "computer_science": [
        "Algorithm",
        "Algorithm analysis",
        "Big O notation",
        "Sorting algorithm",
        "Quicksort",
        "Merge sort",
        "Heapsort",
        "Radix sort",
        "Timsort",
        "Binary search algorithm",
        "Depth-first search",
        "Breadth-first search",
        "Dijkstra's algorithm",
        "A* search algorithm",
        "Bellman-Ford algorithm",
        "Floyd-Warshall algorithm",
        "Minimum spanning tree",
        "Kruskal's algorithm",
        "Prim's algorithm",
        "Maximum flow problem",
        "Ford-Fulkerson algorithm",
        "Hungarian algorithm",
        "Dynamic programming",
        "Greedy algorithm",
        "Divide and conquer algorithm",
        "Branch and bound",
        "Backtracking",
        "Hashing (computer science)",
        "Hash table",
        "Bloom filter",
        "Cuckoo hashing",
        "Consistent hashing",
        "Data structure",
        "Array (data structure)",
        "Linked list",
        "Stack (abstract data type)",
        "Queue (abstract data type)",
        "Priority queue",
        "Binary heap",
        "Fibonacci heap",
        "Binary search tree",
        "AVL tree",
        "Red-black tree",
        "B-tree",
        "B+ tree",
        "Trie",
        "Suffix tree",
        "Segment tree",
        "Fenwick tree",
        "Skip list",
        "Disjoint-set data structure",
        "Graph (data structure)",
        "Adjacency matrix",
        "Adjacency list",
        "Operating system",
        "Process (computing)",
        "Thread (computing)",
        "Context switch",
        "Scheduling (computing)",
        "Virtual memory",
        "Page replacement algorithm",
        "Memory management",
        "Garbage collection (computer science)",
        "File system",
        "POSIX",
        "System call",
        "Interrupt",
        "Deadlock",
        "Mutex",
        "Semaphore (programming)",
        "Monitor (synchronization)",
        "Read-copy-update",
        "Compiler",
        "Lexical analysis",
        "Parsing",
        "Abstract syntax tree",
        "Intermediate representation",
        "Code optimization",
        "Register allocation",
        "Just-in-time compilation",
        "Ahead-of-time compilation",
        "LLVM",
        "WebAssembly",
        "Relational database",
        "SQL",
        "Database normalization",
        "ACID (computer science)",
        "Transaction processing",
        "Concurrency control",
        "Two-phase locking",
        "Multiversion concurrency control",
        "B-tree index",
        "Query optimization",
        "NoSQL database",
        "Key-value store",
        "Document-oriented database",
        "Column-family store",
        "Graph database",
        "CAP theorem",
        "Eventual consistency",
        "Consensus (computer science)",
        "Paxos (computer science)",
        "Raft (algorithm)",
        "Two-phase commit protocol",
        "Distributed hash table",
        "MapReduce",
        "Apache Spark",
        "Stream processing",
        "Distributed systems",
        "Remote procedure call",
        "Microservices architecture",
        "Service mesh",
        "Load balancing (computing)",
        "Consistent hashing (distributed systems)",
        "Vector clock",
        "Lamport timestamp",
        "Gossip protocol",
        "Content delivery network",
        "Domain Name System",
        "TCP/IP",
        "HTTP",
        "REST (architectural style)",
        "gRPC",
        "WebSocket",
        "Programming language theory",
        "Type system",
        "Hindley-Milner type system",
        "Dependent type",
        "Linear type system",
        "Effect system",
        "Continuation",
        "Closure (computer programming)",
        "Coroutine",
        "Async/await",
        "Functional programming",
        "Monad (functional programming)",
        "Immutable data structure",
        "Persistent data structure",
        "Object-oriented programming",
        "Design patterns",
        "SOLID principles",
        "Software architecture",
        "Domain-driven design",
        "Event-driven architecture",
        "Command Query Responsibility Segregation",
        "Event sourcing",
        "Formal verification",
        "Model checking",
        "Theorem proving",
        "Abstract interpretation",
        "Static analysis",
        "Symbolic execution",
        "Fuzzing",
        "Concolic testing",
        "Property-based testing",
        "Differential testing",
        "Mutation testing",
        "Code coverage",
        "Branch coverage",
        "Path coverage",
        "Container (computing)",
        "Docker (software)",
        "Kubernetes",
        "Serverless computing",
        "Function as a service",
        "Infrastructure as code",
        "Continuous integration",
        "Continuous deployment",
        "GitOps",
        "Observability (software)",
        "Distributed tracing",
        "Log aggregation",
        "Metrics (monitoring)",
        "Site reliability engineering",
        "Chaos engineering",
        "Circuit breaker pattern",
        "Bulkhead pattern",
        "Saga pattern",
        "Outbox pattern",
        "Change data capture",
        "Write-ahead log",
        "Log-structured merge-tree",
        "Bloom filter (data structure)",
        "Count-min sketch",
        "HyperLogLog",
        "Approximate counting algorithm",
        "Space-efficient probabilistic data structure",
        "Linear hashing",
        "Extendible hashing",
        "R-tree",
        "k-d tree",
        "Locality-sensitive hashing",
        "Nearest neighbor search",
        "Approximate nearest neighbor",
        "HNSW algorithm",
        "Product quantization",
        "Inverted index",
    ],
    "biology_evolution": [
        "Evolution",
        "Natural selection",
        "Charles Darwin",
        "Modern evolutionary synthesis",
        "Genetic drift",
        "Gene flow",
        "Mutation (biology)",
        "Speciation",
        "Adaptive radiation",
        "Convergent evolution",
        "Divergent evolution",
        "Coevolution (biology)",
        "Sexual selection",
        "Kin selection",
        "Inclusive fitness",
        "Hamilton's rule",
        "Group selection",
        "Multilevel selection",
        "Neutral theory of molecular evolution",
        "Molecular clock",
        "Phylogenetics",
        "Cladistics",
        "Molecular phylogenetics",
        "Last universal common ancestor",
        "Tree of life (biology)",
        "Horizontal gene transfer",
        "Endosymbiotic theory",
        "DNA",
        "RNA",
        "Protein",
        "Gene",
        "Genome",
        "Chromosome",
        "DNA replication",
        "Transcription (biology)",
        "Translation (biology)",
        "Genetic code",
        "Codon",
        "Transfer RNA",
        "Ribosome",
        "Messenger RNA",
        "Gene expression",
        "Gene regulation",
        "Promoter (genetics)",
        "Enhancer (genetics)",
        "Transcription factor",
        "Epigenetics",
        "DNA methylation",
        "Histone modification",
        "Chromatin",
        "Non-coding RNA",
        "MicroRNA",
        "Long non-coding RNA",
        "CRISPR gene editing",
        "Cas9",
        "Restriction enzyme",
        "Polymerase chain reaction",
        "DNA sequencing",
        "Next-generation sequencing",
        "Genomics",
        "Proteomics",
        "Metabolomics",
        "Transcriptomics",
        "Systems biology",
        "Synthetic biology",
        "Genetic engineering",
        "Gene therapy",
        "Recombinant DNA technology",
        "Plasmid",
        "Bacteriophage",
        "Cell biology",
        "Cell membrane",
        "Mitochondrion",
        "Endoplasmic reticulum",
        "Golgi apparatus",
        "Nucleus (cell biology)",
        "Cytoskeleton",
        "Cell division",
        "Mitosis",
        "Meiosis",
        "Cell signaling",
        "Signal transduction",
        "G protein",
        "Kinase",
        "Apoptosis",
        "Autophagy",
        "Stem cell",
        "Embryonic development",
        "Morphogenesis",
        "Homeobox gene",
        "Hox gene",
        "Ecology",
        "Ecosystem",
        "Food web",
        "Trophic level",
        "Keystone species",
        "Biodiversity",
        "Species richness",
        "Ecological niche",
        "Competitive exclusion principle",
        "Ecological succession",
        "Island biogeography",
        "Metapopulation",
        "Population ecology",
        "Carrying capacity",
        "Logistic growth",
        "Lotka-Volterra equations",
        "Predator-prey dynamics",
        "Mutualism (biology)",
        "Parasitism",
        "Symbiosis",
        "Microbiome",
        "Gut microbiota",
        "Antibiotic resistance",
        "Bacteriology",
        "Virology",
        "Prion",
        "Immunology (biology)",
        "Innate immune system",
        "Adaptive immune system",
        "Antibody",
        "T cell",
        "B cell",
        "Major histocompatibility complex",
        "Photosynthesis",
        "Cellular respiration",
        "Krebs cycle",
        "Electron transport chain",
        "ATP synthase",
        "Glycolysis",
        "Calvin cycle",
        "Bioinformatics",
        "Sequence alignment",
        "BLAST (bioinformatics)",
        "Hidden Markov model (bioinformatics)",
        "Protein structure prediction",
        "Gene ontology",
        "Metagenomics",
        "Single-cell sequencing",
        "Spatial transcriptomics",
        "Abiogenesis",
        "RNA world hypothesis",
        "Miller-Urey experiment",
        "Extremophile",
        "Astrobiology",
        "Cambrian explosion",
        "Mass extinction",
        "Permian-Triassic extinction event",
        "Cretaceous-Paleogene extinction event",
        "Great Oxidation Event",
        "Snowball Earth",
        "Ediacaran biota",
        "Burgess Shale",
        "Devonian period",
        "Carboniferous period",
        "Dinosaur",
        "Archaeopteryx",
        "Whale evolution",
        "Human evolution",
        "Australopithecus",
        "Homo erectus",
        "Homo sapiens (evolution)",
        "Neanderthal",
        "Denisovan",
        "Out of Africa hypothesis",
        "Genetic bottleneck",
        "Founder effect",
        "Hardy-Weinberg principle",
        "Population genetics",
        "Coalescent theory",
        "Effective population size",
        "Selective sweep",
        "Balancing selection",
        "Frequency-dependent selection",
        "Epistasis",
        "Pleiotropy",
        "Quantitative genetics",
        "Heritability",
        "Genome-wide association study (biology)",
    ],
    "economics_game_theory": [
        "Game theory",
        "Nash equilibrium (economics)",
        "Prisoner's dilemma",
        "Coordination game",
        "Battle of the sexes (game theory)",
        "Chicken (game theory)",
        "Stag hunt",
        "Repeated game",
        "Folk theorem (game theory)",
        "Subgame perfect equilibrium",
        "Bayesian game",
        "Perfect Bayesian equilibrium",
        "Sequential game",
        "Extensive-form game",
        "Normal-form game",
        "Mixed strategy",
        "Dominant strategy",
        "Correlated equilibrium",
        "Mechanism design",
        "Revelation principle",
        "Vickrey-Clarke-Groves mechanism",
        "Incentive compatibility",
        "Individual rationality",
        "Auction theory",
        "English auction",
        "Dutch auction",
        "Sealed-bid auction",
        "Vickrey auction",
        "Revenue equivalence theorem",
        "Winner's curse",
        "Combinatorial auction",
        "Market design",
        "Matching theory (economics)",
        "Stable matching",
        "Gale-Shapley algorithm",
        "Kidney exchange",
        "School choice mechanism",
        "Social choice theory",
        "Arrow's impossibility theorem",
        "Gibbard-Satterthwaite theorem",
        "Voting theory",
        "Condorcet paradox",
        "Median voter theorem",
        "Behavioral economics",
        "Prospect theory",
        "Loss aversion",
        "Framing effect",
        "Anchoring (cognitive bias)",
        "Endowment effect",
        "Status quo bias",
        "Hyperbolic discounting",
        "Present bias",
        "Bounded rationality",
        "Satisficing",
        "Nudge theory",
        "Mental accounting",
        "Disposition effect",
        "Overconfidence effect (economics)",
        "Herd behavior (economics)",
        "Market microstructure",
        "Bid-ask spread",
        "Order book (finance)",
        "Market maker",
        "Limit order",
        "Market impact",
        "Price discovery",
        "High-frequency trading",
        "Algorithmic trading",
        "Dark pool",
        "Flash crash",
        "Efficient-market hypothesis",
        "Capital asset pricing model",
        "Arbitrage pricing theory",
        "Black-Scholes model",
        "Options pricing",
        "Volatility smile",
        "Value at risk",
        "Expected shortfall",
        "Risk-neutral measure",
        "General equilibrium theory",
        "Walrasian equilibrium",
        "Pareto efficiency",
        "Welfare economics",
        "Externality",
        "Public good (economics)",
        "Tragedy of the commons",
        "Coase theorem",
        "Moral hazard",
        "Adverse selection",
        "Principal-agent problem",
        "Information asymmetry",
        "Signaling (economics)",
        "Screening (economics)",
        "Contract theory",
        "Incomplete contract theory",
        "Network economics",
        "Platform economics",
        "Two-sided market",
        "Network externality",
        "Switching cost",
        "Natural monopoly",
        "Oligopoly",
        "Cournot competition",
        "Bertrand competition",
        "Stackelberg competition",
        "Price discrimination",
        "Bundling (economics)",
        "Predatory pricing",
        "Antitrust law (economics)",
        "Monetary policy",
        "Fiscal policy",
        "Inflation",
        "Interest rate theory",
        "Yield curve",
        "Central banking",
        "Money supply",
        "Quantity theory of money",
        "Phillips curve",
        "Rational expectations",
        "Lucas critique",
        "Dynamic stochastic general equilibrium",
        "Real business cycle theory",
        "New Keynesian economics",
        "Mechanism design theory",
        "Implementation theory",
        "Cheap talk (game theory)",
        "Bayesian persuasion",
        "Information design",
        "Evolutionary game theory (economics)",
    ],
    "philosophy_general": [
        "Epistemology",
        "Justified true belief",
        "Gettier problem",
        "Foundationalism",
        "Coherentism",
        "Reliabilism",
        "Virtue epistemology",
        "Skepticism (philosophy)",
        "Problem of induction",
        "Empiricism",
        "Rationalism",
        "A priori and a posteriori",
        "Analytic-synthetic distinction",
        "Pragmatism",
        "Logical positivism",
        "Verificationism",
        "Falsifiability",
        "Underdetermination",
        "Theory-ladenness of observation",
        "Scientific realism",
        "Anti-realism",
        "Constructive empiricism",
        "Kuhn's paradigm shift",
        "Lakatos's research programme",
        "Feyerabend's epistemological anarchism",
        "Ethics",
        "Metaethics",
        "Normative ethics",
        "Applied ethics",
        "Consequentialism",
        "Utilitarianism",
        "Deontological ethics",
        "Kantian ethics",
        "Categorical imperative",
        "Virtue ethics",
        "Aristotelian ethics",
        "Care ethics",
        "Contractualism",
        "Moral realism",
        "Moral anti-realism",
        "Error theory (ethics)",
        "Expressivism",
        "Moral relativism",
        "Moral particularism",
        "Trolley problem",
        "Effective altruism (philosophy)",
        "Animal rights (philosophy)",
        "Environmental ethics",
        "Bioethics",
        "Just war theory",
        "Metaphysics",
        "Ontology",
        "Existence",
        "Universals",
        "Nominalism",
        "Platonism",
        "Trope theory",
        "Mereology",
        "Modal logic",
        "Possible worlds",
        "Counterfactual conditional",
        "Causation (philosophy)",
        "Regularity theory of causation",
        "Counterfactual theory of causation",
        "Personal identity (metaphysics)",
        "Philosophy of time",
        "Presentism (philosophy of time)",
        "Eternalism (philosophy of time)",
        "Growing block universe",
        "Philosophy of language",
        "Sense and reference",
        "Speech act theory",
        "Pragmatics (philosophy)",
        "Truth (philosophy)",
        "Correspondence theory of truth",
        "Coherence theory of truth",
        "Deflationary theory of truth",
        "Logic",
        "Propositional logic",
        "Predicate logic",
        "Modal logic (formal)",
        "Deontic logic",
        "Epistemic logic",
        "Temporal logic (philosophy)",
        "Paraconsistent logic",
        "Fuzzy logic",
        "Informal logic",
        "Fallacy",
        "Political philosophy",
        "Social contract",
        "Rawls's theory of justice",
        "Libertarianism (political philosophy)",
        "Communitarianism",
        "Republicanism (political philosophy)",
        "Deliberative democracy",
        "Philosophy of science",
        "Scientific explanation",
        "Laws of nature (philosophy)",
        "Natural kind",
        "Reductionism",
        "Emergentism (philosophy)",
        "Holism",
        "Supervenience (philosophy)",
        "Multiple realizability (philosophy of science)",
        "Philosophy of mathematics",
        "Mathematical Platonism",
        "Formalism (philosophy of mathematics)",
        "Intuitionism (mathematics)",
        "Structuralism (philosophy of mathematics)",
        "Philosophy of physics",
        "Philosophy of space and time",
        "Substantivalism",
        "Relationalism",
        "Determinism (philosophy of physics)",
        "Indeterminism",
        "Problem of evil",
        "Theodicy",
        "Cosmological argument",
        "Ontological argument",
        "Teleological argument",
        "Existentialism",
        "Phenomenology of spirit",
        "Hermeneutics",
        "Post-structuralism",
        "Deconstruction",
        "Critical theory",
        "Frankfurt School",
        "Habermas's communicative action",
        "Rawlsian veil of ignorance",
    ],
    "cognitive_science": [
        "Cognitive science",
        "Cognitive psychology",
        "Perception",
        "Visual perception",
        "Gestalt psychology",
        "Color perception",
        "Depth perception",
        "Motion perception",
        "Auditory perception",
        "Haptic perception",
        "Multisensory perception",
        "Perceptual illusion",
        "Attention (cognitive science)",
        "Selective attention",
        "Divided attention",
        "Sustained attention",
        "Attentional blink",
        "Executive attention",
        "Attention and consciousness",
        "Working memory",
        "Baddeley's model of working memory",
        "Phonological loop",
        "Visuospatial sketchpad",
        "Central executive",
        "Episodic buffer",
        "Long-term memory (cognitive science)",
        "Declarative memory",
        "Procedural memory (cognitive science)",
        "Prospective memory",
        "Autobiographical memory",
        "False memory",
        "Memory encoding",
        "Memory retrieval",
        "Spacing effect",
        "Testing effect",
        "Levels of processing theory",
        "Dual-process theory",
        "System 1 and System 2",
        "Heuristics and biases",
        "Availability heuristic",
        "Representativeness heuristic",
        "Confirmation bias",
        "Cognitive dissonance",
        "Decision making (cognitive science)",
        "Prospect theory (cognitive science)",
        "Expected utility theory",
        "Bounded rationality (cognitive science)",
        "Ecological rationality",
        "Fast and frugal heuristics",
        "Recognition heuristic",
        "Problem solving",
        "Means-ends analysis",
        "Analogical reasoning",
        "Mental model",
        "Schema (psychology)",
        "Script theory (cognitive science)",
        "Categorization",
        "Prototype theory",
        "Exemplar theory",
        "Conceptual spaces",
        "Language acquisition",
        "Universal grammar",
        "Critical period hypothesis (language)",
        "Statistical learning (language)",
        "Phonological development",
        "Syntactic development",
        "Bilingualism and cognition",
        "Linguistic relativity",
        "Language and thought",
        "Reading comprehension",
        "Sentence processing",
        "Cognitive development",
        "Piaget's theory of cognitive development",
        "Vygotsky's zone of proximal development",
        "Theory of mind (cognitive science)",
        "Executive function",
        "Inhibitory control",
        "Cognitive flexibility",
        "Planning (cognitive science)",
        "Metacognition (cognitive science)",
        "Feeling of knowing",
        "Judgment of learning",
        "Cognitive load theory",
        "Expertise (cognitive science)",
        "Deliberate practice",
        "Chunking (psychology)",
        "Cognitive architecture",
        "ACT-R",
        "SOAR (cognitive architecture)",
        "Global workspace theory (cognitive science)",
        "Predictive processing (cognitive science)",
        "Bayesian brain hypothesis",
        "Active inference",
        "Embodied cognition (cognitive science)",
        "Situated cognition",
        "Distributed cognition",
        "Cultural cognition",
        "Numeracy (cognition)",
        "Spatial cognition",
        "Cognitive map",
        "Mental rotation",
        "Numerical cognition",
        "Subitizing",
        "Approximate number system",
        "Weber's law (cognition)",
        "Cross-modal correspondence",
        "Synesthesia",
        "Cognitive aging",
        "Cognitive reserve",
        "Intelligence (cognitive science)",
        "Fluid intelligence",
        "Crystallized intelligence",
        "Multiple intelligences theory",
        "Creativity (cognitive science)",
        "Insight problem solving",
        "Incubation effect",
        "Mind wandering",
        "Daydreaming",
        "Flow state",
        "Cognitive control",
        "Task switching",
        "Stroop effect",
        "Simon effect",
        "Flanker task",
        "Go/no-go task",
        "N-back task",
        "Iowa gambling task",
        "Delay discounting",
        "Risk perception",
        "Emotional regulation",
        "Embodied emotion theory",
    ],
    "engineering_systems": [
        "Control theory",
        "Feedback control",
        "PID controller",
        "State-space representation",
        "Transfer function",
        "Bode plot",
        "Nyquist stability criterion",
        "Root locus method",
        "Controllability",
        "Observability",
        "Kalman filter",
        "Extended Kalman filter",
        "Linear-quadratic regulator",
        "Model predictive control",
        "Adaptive control",
        "Robust control",
        "H-infinity control",
        "Nonlinear control",
        "Sliding mode control",
        "Lyapunov stability theory",
        "Signal processing",
        "Discrete Fourier transform",
        "Fast Fourier transform",
        "Convolution",
        "Digital filter",
        "Finite impulse response filter",
        "Infinite impulse response filter",
        "Butterworth filter",
        "Chebyshev filter",
        "Sampling theorem",
        "Nyquist-Shannon sampling theorem",
        "Aliasing",
        "Analog-to-digital converter",
        "Digital-to-analog converter",
        "Compressed sensing",
        "Sparse signal recovery",
        "Matched filter",
        "Wiener filter",
        "Adaptive filter",
        "Least mean squares filter",
        "Systems engineering",
        "Systems theory",
        "Reliability engineering",
        "Fault tolerance",
        "Redundancy (engineering)",
        "Failure mode and effects analysis",
        "Root cause analysis",
        "Mean time between failures",
        "Availability (engineering)",
        "Safety engineering",
        "Hazard analysis",
        "Safety integrity level",
        "Requirements engineering",
        "Model-based systems engineering",
        "SysML",
        "V-model (systems engineering)",
        "Verification and validation",
        "Robotics",
        "Robot kinematics",
        "Inverse kinematics",
        "Robot dynamics",
        "Motion planning",
        "Rapidly-exploring random tree",
        "Simultaneous localization and mapping",
        "Visual odometry",
        "Sensor fusion",
        "Inertial measurement unit",
        "Lidar",
        "Actuator",
        "Servo motor",
        "Stepper motor",
        "Soft robotics",
        "Swarm robotics",
        "Human-robot interaction",
        "Autonomous vehicle",
        "Unmanned aerial vehicle",
        "Materials science",
        "Crystal structure",
        "Defect (crystallography)",
        "Mechanical properties of materials",
        "Stress-strain curve",
        "Fatigue (material)",
        "Fracture mechanics",
        "Composite material",
        "Polymer",
        "Ceramic (material)",
        "Nanomaterial",
        "Semiconductor device",
        "MOSFET",
        "Integrated circuit",
        "CMOS technology",
        "VLSI design",
        "Field-programmable gate array",
        "Application-specific integrated circuit",
        "Power electronics",
        "Electric motor theory",
        "Heat transfer",
        "Conduction (heat transfer)",
        "Convection",
        "Radiation (heat transfer)",
        "Heat exchanger design",
        "Finite element analysis",
        "Computational fluid dynamics",
        "Topology optimization",
        "Additive manufacturing",
        "3D printing",
        "Computer-aided design",
        "Computer-aided manufacturing",
        "Digital twin",
        "Model-based design",
        "Mechatronics",
        "Embedded system",
        "Real-time operating system",
        "Programmable logic controller",
        "SCADA system",
        "Industrial control system",
        "Cyber-physical system",
        "Internet of Things",
        "Edge computing",
        "Fog computing",
        "5G technology",
        "Antenna design",
        "Radar signal processing",
        "Sonar",
        "Vibration analysis",
        "Modal analysis (engineering)",
        "Structural dynamics",
        "Earthquake engineering",
        "Wind engineering",
        "Aerodynamics",
        "Orbital mechanics (engineering)",
        "Propulsion systems",
    ],
    "chemistry": [
        "Atom",
        "Periodic table",
        "Chemical bond",
        "Covalent bond",
        "Ionic bond",
        "Metallic bonding",
        "Hydrogen bond",
        "Van der Waals force",
        "Electronegativity",
        "Molecular orbital theory",
        "Valence bond theory",
        "Hybridization (chemistry)",
        "Lewis structure",
        "VSEPR theory",
        "Chemical reaction",
        "Reaction rate",
        "Rate equation",
        "Activation energy",
        "Arrhenius equation",
        "Catalyst",
        "Enzyme kinetics",
        "Michaelis-Menten kinetics",
        "Chemical equilibrium",
        "Le Chatelier's principle",
        "Acid-base chemistry",
        "pH",
        "Buffer solution",
        "Oxidation-reduction reaction",
        "Electrochemistry",
        "Galvanic cell",
        "Electrolysis",
        "Nernst equation",
        "Thermochemistry",
        "Enthalpy",
        "Gibbs free energy (chemistry)",
        "Hess's law",
        "Chemical thermodynamics",
        "Entropy (chemistry)",
        "Phase diagram (chemistry)",
        "Colligative properties",
        "Organic chemistry",
        "Functional group",
        "Alkane",
        "Alkene",
        "Aromatic compound",
        "Benzene",
        "Alcohol (chemistry)",
        "Aldehyde",
        "Ketone",
        "Carboxylic acid",
        "Ester",
        "Amine",
        "Amide",
        "Stereochemistry",
        "Chirality (chemistry)",
        "Enantiomer",
        "Diastereomer",
        "Conformational isomerism",
        "Nucleophilic substitution",
        "Elimination reaction",
        "Electrophilic addition",
        "Electrophilic aromatic substitution",
        "Grignard reaction",
        "Aldol reaction",
        "Diels-Alder reaction",
        "Suzuki reaction",
        "Olefin metathesis",
        "Organometallic chemistry",
        "Coordination chemistry",
        "Crystal field theory",
        "Ligand field theory",
        "Transition metal complex",
        "Bioinorganic chemistry",
        "Solid-state chemistry",
        "X-ray crystallography",
        "Spectroscopy",
        "Nuclear magnetic resonance spectroscopy",
        "Infrared spectroscopy",
        "Mass spectrometry",
        "UV-visible spectroscopy",
        "Chromatography",
        "High-performance liquid chromatography",
        "Gas chromatography",
        "Biochemistry",
        "Amino acid",
        "Protein folding",
        "Enzyme",
        "Lipid",
        "Carbohydrate",
        "Nucleic acid",
        "ATP (biochemistry)",
        "Cofactor (biochemistry)",
        "Metabolism",
        "Polymer chemistry",
        "Polymerization",
        "Supramolecular chemistry",
        "Self-assembly (chemistry)",
        "Colloid chemistry",
        "Surface chemistry",
        "Photochemistry",
        "Green chemistry",
        "Computational chemistry",
        "Molecular dynamics simulation",
        "Monte Carlo simulation (chemistry)",
        "Density functional theory (chemistry)",
        "Ab initio quantum chemistry",
        "Semi-empirical quantum chemistry",
        "Force field (chemistry)",
        "Molecular mechanics",
        "Quantum chemistry",
        "Born-Oppenheimer approximation",
        "Basis set (chemistry)",
        "Gaussian-type orbital",
        "Slater-type orbital",
        "Moller-Plesset perturbation theory",
        "Multireference method",
        "Complete active space",
        "Electrochemistry (advanced)",
        "Fuel cell chemistry",
        "Battery chemistry",
        "Lithium-ion battery",
        "Solid-state battery",
        "Catalysis",
        "Heterogeneous catalysis",
        "Homogeneous catalysis",
        "Asymmetric catalysis",
        "Organocatalysis",
        "Click chemistry",
        "Flow chemistry",
        "Retrosynthetic analysis",
        "Total synthesis",
    ],
    "astronomy_cosmology": [
        "Astronomy",
        "Observational astronomy",
        "Telescope",
        "Radio telescope",
        "Space telescope",
        "James Webb Space Telescope",
        "Hubble Space Telescope",
        "Adaptive optics",
        "Interferometry (astronomy)",
        "Photometry (astronomy)",
        "Astrometry",
        "Stellar classification",
        "Hertzsprung-Russell diagram",
        "Main sequence",
        "Red giant",
        "White dwarf",
        "Neutron star",
        "Pulsar",
        "Magnetar",
        "Black hole",
        "Stellar black hole",
        "Supermassive black hole",
        "Active galactic nucleus",
        "Quasar",
        "Blazar",
        "Accretion disk",
        "Eddington luminosity",
        "Stellar evolution",
        "Star formation",
        "Molecular cloud",
        "Protostar",
        "T Tauri star",
        "Stellar nucleosynthesis",
        "Supernova",
        "Type Ia supernova",
        "Core-collapse supernova",
        "Supernova remnant",
        "Planetary nebula",
        "Gamma-ray burst",
        "Kilonova",
        "Gravitational wave astronomy",
        "Binary star",
        "Eclipsing binary",
        "X-ray binary",
        "Cepheid variable",
        "RR Lyrae variable",
        "Solar physics",
        "Solar wind",
        "Solar flare",
        "Coronal mass ejection",
        "Helioseismology",
        "Exoplanet",
        "Exoplanet detection methods",
        "Transit photometry",
        "Radial velocity method",
        "Direct imaging (exoplanets)",
        "Habitable zone",
        "Hot Jupiter",
        "Super-Earth",
        "Kepler mission",
        "TESS (space telescope)",
        "Planet formation",
        "Protoplanetary disk",
        "Planetesimal",
        "Solar System",
        "Terrestrial planet",
        "Gas giant",
        "Ice giant",
        "Asteroid belt",
        "Kuiper belt",
        "Oort cloud",
        "Milky Way",
        "Galaxy",
        "Spiral galaxy",
        "Elliptical galaxy",
        "Galaxy morphological classification",
        "Galaxy cluster",
        "Galaxy supercluster",
        "Large-scale structure of the universe",
        "Cosmic web",
        "Void (astronomy)",
        "Galaxy formation and evolution",
        "Galaxy merger",
        "Tidal disruption event",
        "Interstellar medium",
        "H II region",
        "Dark nebula",
        "Cosmic dust",
        "Cosmology",
        "Big Bang theory",
        "Cosmic microwave background radiation",
        "Cosmic inflation theory",
        "Lambda-CDM model",
        "Dark matter (astronomy)",
        "Dark energy (astronomy)",
        "Hubble's law",
        "Redshift",
        "Cosmic distance ladder",
        "Type Ia supernova cosmology",
        "Baryon acoustic oscillations (cosmology)",
        "Primordial nucleosynthesis",
        "Cosmic neutrino background",
        "Gravitational lensing (astronomy)",
        "Weak lensing",
        "Strong lensing",
        "Microlensing",
        "Tully-Fisher relation",
        "Faber-Jackson relation",
        "Fundamental plane (astronomy)",
        "Cepheid distance scale",
        "Tip of the red-giant branch",
        "Surface brightness fluctuation",
        "Sunyaev-Zeldovich effect",
        "Sachs-Wolfe effect",
        "Cosmic variance",
        "Power spectrum (cosmology)",
        "Angular power spectrum",
        "Matter power spectrum",
        "Halo model (cosmology)",
        "Press-Schechter formalism",
        "Navarro-Frenk-White profile",
        "Bullet Cluster",
        "Dark matter halo",
        "Modified Newtonian dynamics",
        "Tensor-vector-scalar gravity",
        "f(R) gravity",
        "Quintessence (physics)",
        "Phantom energy",
        "Big Rip",
        "Heat death of the universe",
        "Multiverse hypothesis",
    ],
    "linguistics": [
        "Linguistics",
        "Phonetics",
        "Phonology",
        "Phoneme",
        "Allophone",
        "Distinctive feature",
        "Syllable structure",
        "Prosody (linguistics)",
        "Intonation (linguistics)",
        "Tone (linguistics)",
        "Stress (linguistics)",
        "Morphology (linguistics)",
        "Morpheme",
        "Inflection",
        "Derivation (linguistics)",
        "Compounding (linguistics)",
        "Agglutination",
        "Fusional language",
        "Syntax",
        "Phrase structure grammar",
        "Generative grammar",
        "Transformational grammar",
        "Minimalist program",
        "X-bar theory",
        "Government and binding theory",
        "Lexical-functional grammar",
        "Head-driven phrase structure grammar",
        "Dependency grammar",
        "Construction grammar",
        "Semantics (linguistics)",
        "Lexical semantics",
        "Compositional semantics",
        "Formal semantics (linguistics)",
        "Model-theoretic semantics",
        "Possible worlds semantics",
        "Truth-conditional semantics",
        "Pragmatics",
        "Speech act",
        "Implicature",
        "Gricean maxims",
        "Relevance theory",
        "Presupposition",
        "Deixis",
        "Discourse analysis",
        "Historical linguistics",
        "Sound change",
        "Grimm's law",
        "Language family",
        "Proto-language",
        "Indo-European languages",
        "Comparative method (linguistics)",
        "Language contact",
        "Pidgin",
        "Creole language",
        "Sociolinguistics",
        "Language variation",
        "Dialect",
        "Register (sociolinguistics)",
        "Code-switching",
        "Language and gender",
        "Language policy",
        "Language death",
        "Psycholinguistics",
        "Language processing",
        "Sentence parsing (psycholinguistics)",
        "Garden-path sentence",
        "Lexical access",
        "Speech production",
        "Speech perception",
        "Neurolinguistics",
        "Aphasia",
        "Broca's aphasia",
        "Wernicke's aphasia",
        "Computational linguistics",
        "Corpus linguistics",
        "Natural language understanding",
        "Formal language (linguistics)",
        "Chomsky hierarchy",
        "Context-free grammar",
        "Typology (linguistics)",
        "Linguistic universal",
        "Word order typology",
        "Ergative-absolutive language",
        "Morphological typology",
        "Polysynthetic language",
        "Analytic language",
        "Grammaticalization",
        "Lexicalization",
        "Semantic change",
        "Etymology",
        "Cognate",
        "Loanword",
        "Language isolate",
        "Endangered language",
        "Language revitalization",
        "Sign language linguistics",
        "American Sign Language",
        "Phonological rule",
        "Optimality theory (linguistics)",
        "Autosegmental phonology",
        "Metrical phonology",
    ],
    "medicine_health": [
        "Immunology",
        "Immune system",
        "Innate immunity",
        "Adaptive immunity",
        "T lymphocyte",
        "B lymphocyte",
        "Antibody structure and function",
        "Antigen",
        "Major histocompatibility complex (medicine)",
        "Immunoglobulin",
        "Complement system",
        "Cytokine",
        "Inflammation",
        "Autoimmune disease",
        "Immunodeficiency",
        "Vaccination",
        "mRNA vaccine",
        "Monoclonal antibody therapy",
        "Chimeric antigen receptor T cell",
        "Transplant immunology",
        "Pharmacology",
        "Pharmacokinetics",
        "Pharmacodynamics",
        "Drug metabolism",
        "Cytochrome P450",
        "Drug-drug interaction",
        "Dose-response relationship",
        "Receptor theory (pharmacology)",
        "Agonist and antagonist",
        "Drug discovery",
        "Clinical trial",
        "Randomized controlled trial",
        "Double-blind experiment",
        "Placebo effect",
        "Pharmacogenomics",
        "Epidemiology",
        "Incidence and prevalence",
        "Cohort study",
        "Case-control study",
        "Relative risk",
        "Odds ratio",
        "Confounding variable (epidemiology)",
        "Selection bias",
        "Information bias (epidemiology)",
        "Herd immunity",
        "Basic reproduction number",
        "Epidemic curve",
        "Pandemic preparedness",
        "Contact tracing",
        "Surveillance (epidemiology)",
        "Genetics in medicine",
        "Human genome",
        "Single-nucleotide polymorphism",
        "Genome-wide association study",
        "Mendelian inheritance",
        "Polygenic inheritance",
        "Genetic disorder",
        "Chromosomal abnormality",
        "Genetic testing",
        "Genetic counseling",
        "Precision medicine",
        "Oncology",
        "Carcinogenesis",
        "Tumor suppressor gene",
        "Oncogene",
        "Cancer immunotherapy",
        "Chemotherapy",
        "Targeted therapy (oncology)",
        "Radiation therapy",
        "Cancer staging",
        "Tumor microenvironment",
        "Cardiology",
        "Atherosclerosis",
        "Myocardial infarction",
        "Heart failure",
        "Cardiac arrhythmia",
        "Hypertension",
        "Echocardiography",
        "Cardiac catheterization",
        "Infectious disease",
        "Bacterial pathogenesis",
        "Viral pathogenesis",
        "Antimicrobial resistance",
        "Sepsis",
        "Tuberculosis",
        "HIV/AIDS pathology",
        "Malaria pathology",
        "SARS-CoV-2",
        "Neurology",
        "Alzheimer's disease (clinical)",
        "Parkinson's disease (clinical)",
        "Epilepsy (clinical)",
        "Multiple sclerosis (clinical)",
        "Stroke (clinical)",
        "Endocrinology",
        "Diabetes mellitus",
        "Thyroid disease",
        "Adrenal gland disorders",
        "Diagnostic imaging",
        "Magnetic resonance imaging (medical)",
        "Computed tomography",
        "Ultrasound imaging",
        "Positron emission tomography",
        "X-ray imaging",
        "Fluoroscopy",
        "Nuclear medicine",
        "Pathology",
        "Histology",
        "Cytology",
        "Hematology",
        "Blood coagulation",
        "Platelet biology",
        "Anemia",
        "Leukemia",
        "Lymphoma",
        "Nephrology",
        "Glomerular filtration",
        "Dialysis",
        "Kidney transplantation",
        "Pulmonology",
        "Respiratory physiology",
        "Asthma pathophysiology",
        "Chronic obstructive pulmonary disease",
        "Gastroenterology",
        "Inflammatory bowel disease",
        "Hepatitis",
        "Cirrhosis",
        "Dermatology",
        "Wound healing",
        "Rheumatology",
        "Systemic lupus erythematosus",
        "Rheumatoid arthritis",
    ],
}
