//! Knowledge Fabric types.

use serde::{Deserialize, Serialize};

/// Provenance — where a knowledge vector came from.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub enum Provenance {
    /// Extracted from a mined block.
    Block { height: u64 },
    /// Submitted by a user interaction.
    UserInteraction { session_id: String },
    /// Ingested from an external feed.
    External { source: String },
    /// Generated by the reasoning engine.
    Inferred { reasoning_id: String },
    /// Seeded at genesis / initialization.
    Genesis,
}

/// A knowledge vector in the fabric.
///
/// NOT a "node" — a point in continuous embedding space.
/// Relationships are geometric (cosine similarity), not explicit edges.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct KnowledgeVector {
    /// Unique identifier.
    pub id: u64,
    /// Dense embedding (e.g. 1024-dimensional).
    pub embedding: Vec<f32>,
    /// Sephirot domain (0-9).
    pub domain: u8,
    /// Human-readable content that was embedded (for display/debug).
    pub content: String,
    /// Where this knowledge came from.
    pub provenance: Provenance,
    /// Block height when this was created.
    pub block_height: u64,
    /// Learned confidence (updated by training).
    pub confidence: f32,
}
