SET DATABASE = qubitcoin;

-- ================================================================
-- CONTRACT EXECUTIONS - All contract calls
-- Aligned with SQLAlchemy ContractExecutionModel (database/manager.py)
-- ================================================================
CREATE TABLE IF NOT EXISTS contract_executions (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    contract_id VARCHAR(66) NOT NULL,
    executor_address VARCHAR NOT NULL,
    method VARCHAR(100),
    params JSONB,
    gas_paid DECIMAL(18, 8) DEFAULT 0,
    success BOOL,
    result JSONB,
    error_message TEXT,
    block_height BIGINT,
    executed_at TIMESTAMP DEFAULT now(),

    INDEX contract_idx (contract_id),
    INDEX executor_idx (executor_address),
    INDEX block_idx (block_height DESC),
    INDEX success_idx (success)
);

-- ================================================================
-- CONTRACT LOGS - Event emissions
-- Aligned with SQLAlchemy ContractLogModel (database/manager.py)
-- ================================================================
CREATE TABLE IF NOT EXISTS contract_logs (
    log_id VARCHAR(36) PRIMARY KEY DEFAULT gen_random_uuid()::STRING,
    execution_id VARCHAR(36) NOT NULL,
    tx_hash BYTES NOT NULL,
    block_height BIGINT NOT NULL,
    contract_address BYTES NOT NULL,
    log_index INT NOT NULL,
    topic0 BYTES NOT NULL,
    topic1 BYTES,
    topic2 BYTES,
    topic3 BYTES,
    data BYTES NOT NULL,
    event_name VARCHAR(255),
    decoded_data JSONB,
    timestamp TIMESTAMP NOT NULL DEFAULT now(),

    INDEX tx_idx (tx_hash),
    INDEX contract_idx (contract_address),
    INDEX topic0_idx (topic0),
    INDEX block_idx (block_height DESC)
);

INSERT INTO schema_version (version, component, description)
VALUES ('2.0.0', 'qvm_execution', 'Contract execution — aligned with SQLAlchemy ORM')
ON CONFLICT DO NOTHING;
