SET DATABASE = qubitcoin;

-- ================================================================
-- CONTRACT STORAGE - Key-value storage for contracts
-- Aligned with SQLAlchemy ContractStorageModel (database/manager.py)
-- The ORM uses String types for contract_address/storage_key/value
-- to match the hex-encoded values used by the Python QVM.
-- ================================================================
CREATE TABLE IF NOT EXISTS contract_storage (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    contract_address VARCHAR(42) NOT NULL,
    storage_key VARCHAR(64) NOT NULL,
    storage_value VARCHAR(64) NOT NULL,
    block_height BIGINT,

    UNIQUE INDEX contract_key_idx (contract_address, storage_key),
    INDEX contract_idx (contract_address)
);

-- ================================================================
-- CONTRACT STATE SNAPSHOTS - Periodic state checkpoints
-- Aligned with SQLAlchemy ContractStateSnapshotModel
-- ================================================================
CREATE TABLE IF NOT EXISTS contract_state_snapshots (
    snapshot_id VARCHAR(36) PRIMARY KEY DEFAULT gen_random_uuid()::STRING,
    contract_address BYTES NOT NULL,
    block_height BIGINT NOT NULL,
    block_hash BYTES NOT NULL,
    storage_root BYTES NOT NULL,
    state_data JSONB NOT NULL,
    storage_size BIGINT NOT NULL,
    ipfs_hash VARCHAR(100),
    created_timestamp TIMESTAMP NOT NULL DEFAULT now()
);

INSERT INTO schema_version (version, component, description)
VALUES ('2.0.0', 'qvm_storage', 'Contract state storage — aligned with SQLAlchemy ORM')
ON CONFLICT DO NOTHING;
