SET DATABASE = qubitcoin;

-- ================================================================
-- KNOWLEDGE NODES - Core knowledge representation
-- Aligned with SQLAlchemy KnowledgeNodeModel (database/manager.py)
-- Uses GENERATED BY DEFAULT to allow explicit ID inserts from code
-- ================================================================
CREATE TABLE IF NOT EXISTS knowledge_nodes (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,

    -- Node identity
    node_type VARCHAR(50) NOT NULL,
    content_hash VARCHAR(64) NOT NULL,

    -- Content (JSONB for flexible schema)
    content JSONB NOT NULL,

    -- Confidence & validation
    confidence FLOAT NOT NULL DEFAULT 0.5,

    -- Blockchain anchoring
    source_block BIGINT,

    -- Timestamps
    created_at TIMESTAMP NOT NULL DEFAULT now(),

    INDEX type_idx (node_type),
    INDEX confidence_idx (confidence DESC),
    INDEX source_block_idx (source_block)
);

-- ================================================================
-- KNOWLEDGE EDGES - Relationships between nodes
-- Aligned with SQLAlchemy KnowledgeEdgeModel (database/manager.py)
-- ================================================================
CREATE TABLE IF NOT EXISTS knowledge_edges (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,

    -- Edge definition
    from_node_id BIGINT NOT NULL,
    to_node_id BIGINT NOT NULL,
    edge_type VARCHAR(50) NOT NULL,
    weight FLOAT NOT NULL DEFAULT 1.0,

    -- Timestamps
    created_at TIMESTAMP NOT NULL DEFAULT now(),

    UNIQUE INDEX edge_unique_idx (from_node_id, to_node_id, edge_type),
    INDEX from_idx (from_node_id),
    INDEX to_idx (to_node_id),
    INDEX type_idx (edge_type)
);

INSERT INTO schema_version (version, component, description)
VALUES ('2.1.0', 'agi_knowledge_graph', 'Knowledge graph — BY DEFAULT identity for explicit ID inserts')
ON CONFLICT DO NOTHING;
