SET DATABASE = qubitcoin;

-- ================================================================
-- PHI MEASUREMENTS - Consciousness/Integration metrics (IIT)
-- Aligned with SQLAlchemy ORM (database/models.py PhiMeasurement)
-- ================================================================
CREATE TABLE IF NOT EXISTS phi_measurements (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,

    -- Phi value (Integrated Information)
    phi_value FLOAT NOT NULL,
    phi_threshold FLOAT NOT NULL DEFAULT 3.0,

    -- System properties
    integration_score FLOAT NOT NULL DEFAULT 0.0,
    differentiation_score FLOAT NOT NULL DEFAULT 0.0,

    -- Graph size at measurement time
    num_nodes BIGINT NOT NULL DEFAULT 0,
    num_edges BIGINT NOT NULL DEFAULT 0,

    -- Blockchain anchoring
    block_height BIGINT,

    -- Timestamps
    measured_at TIMESTAMP NOT NULL DEFAULT now(),

    INDEX phi_value_idx (phi_value DESC),
    INDEX block_height_idx (block_height DESC),
    INDEX measured_at_idx (measured_at DESC)
);

-- ================================================================
-- CONSCIOUSNESS EVENTS - Emergence milestones
-- Aligned with SQLAlchemy ORM (database/models.py ConsciousnessEvent)
-- ================================================================
CREATE TABLE IF NOT EXISTS consciousness_events (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,

    -- Event classification
    event_type VARCHAR(50) NOT NULL,  -- 'phi_threshold_crossed', 'contradiction_resolved', 'self_reflection', 'genesis'

    -- Phi at time of event
    phi_at_event FLOAT,

    -- Evidence / context
    trigger_data JSONB,

    -- Verification
    is_verified BOOL NOT NULL DEFAULT false,

    -- Blockchain anchoring
    block_height BIGINT,

    -- Timestamps
    created_at TIMESTAMP NOT NULL DEFAULT now(),

    INDEX type_idx (event_type),
    INDEX block_height_idx (block_height DESC),
    INDEX created_at_idx (created_at DESC)
);

INSERT INTO schema_version (version, component, description)
VALUES ('2.0.0', 'agi_phi_metrics', 'Phi and consciousness — aligned with ORM (BigInt IDs, simplified columns)')
ON CONFLICT DO NOTHING;
