SET DATABASE = qubitcoin;

-- ================================================================
-- CONVERSATION SESSIONS — Per-user persistent chat sessions
-- Tracks wallet address → conversation threads across sessions
-- ================================================================
CREATE TABLE IF NOT EXISTS conversation_sessions (
    session_id UUID PRIMARY KEY DEFAULT gen_random_uuid(),

    -- User identity (wallet address or anonymous fingerprint)
    user_id VARCHAR(128) NOT NULL,
    user_address VARCHAR(128) NOT NULL DEFAULT '',

    -- Session metadata
    title VARCHAR(256) NOT NULL DEFAULT '',
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    last_activity TIMESTAMPTZ NOT NULL DEFAULT now(),
    expires_at TIMESTAMPTZ NOT NULL DEFAULT (now() + INTERVAL '30 days'),

    -- Counters
    message_count INT NOT NULL DEFAULT 0,
    fees_paid_atoms BIGINT NOT NULL DEFAULT 0,

    -- Session state
    status VARCHAR(20) NOT NULL DEFAULT 'active',  -- active, archived, expired

    -- Context summary (compressed older messages)
    context_summary TEXT NOT NULL DEFAULT '',

    -- Topic tracking
    primary_topic VARCHAR(128) NOT NULL DEFAULT '',
    topics JSONB NOT NULL DEFAULT '[]',

    -- Indexes
    INDEX idx_conv_user (user_id, last_activity DESC),
    INDEX idx_conv_status (status, last_activity DESC),
    INDEX idx_conv_expires (expires_at) WHERE status = 'active'
);

-- ================================================================
-- CONVERSATION MESSAGES — Individual messages within sessions
-- ================================================================
CREATE TABLE IF NOT EXISTS conversation_messages (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,

    -- Foreign key to session
    session_id UUID NOT NULL REFERENCES conversation_sessions(session_id) ON DELETE CASCADE,

    -- Message content
    role VARCHAR(20) NOT NULL,  -- 'user' or 'aether'
    content TEXT NOT NULL,
    content_hash VARCHAR(64) NOT NULL DEFAULT '',

    -- Timestamp
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),

    -- Aether-specific metadata (only for role='aether')
    reasoning_trace JSONB NOT NULL DEFAULT '[]',
    phi_at_response FLOAT NOT NULL DEFAULT 0.0,
    knowledge_nodes_referenced JSONB NOT NULL DEFAULT '[]',
    proof_of_thought_hash VARCHAR(128) NOT NULL DEFAULT '',
    quality_score FLOAT NOT NULL DEFAULT 0.0,

    -- Intent & entity tracking
    intent VARCHAR(64) NOT NULL DEFAULT '',
    entities JSONB NOT NULL DEFAULT '{}',

    -- Ordering
    INDEX idx_msg_session (session_id, created_at ASC),
    INDEX idx_msg_user_time (session_id, id ASC)
);

-- ================================================================
-- USER MEMORY — Cross-session persistent user memory
-- Replaces the JSON-file ChatMemory with DB-backed storage
-- ================================================================
CREATE TABLE IF NOT EXISTS user_memory (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,

    user_id VARCHAR(128) NOT NULL,
    memory_key VARCHAR(128) NOT NULL,
    memory_value TEXT NOT NULL,

    -- Metadata
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    source VARCHAR(64) NOT NULL DEFAULT 'chat',  -- chat, explicit, inferred

    -- Unique per user+key
    UNIQUE (user_id, memory_key),

    INDEX idx_umem_user (user_id)
);

-- ================================================================
-- CONVERSATION INSIGHTS — Knowledge extracted from conversations
-- Links conversations to KG nodes for cross-session intelligence
-- ================================================================
CREATE TABLE IF NOT EXISTS conversation_insights (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,

    session_id UUID NOT NULL REFERENCES conversation_sessions(session_id) ON DELETE CASCADE,
    user_id VARCHAR(128) NOT NULL,

    -- Extracted insight
    insight_type VARCHAR(64) NOT NULL,  -- question, preference, feedback, discovery
    content TEXT NOT NULL,
    confidence FLOAT NOT NULL DEFAULT 0.5,

    -- Link to knowledge graph (if a KG node was created from this insight)
    knowledge_node_id BIGINT,

    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),

    INDEX idx_insight_user (user_id, created_at DESC),
    INDEX idx_insight_session (session_id)
);
